// Code generated by generategomodels; DO NOT EDIT.

// Package runtime_session_started contains generated Go models for the Kiln event/payload/runtime-session-started schema.
package runtime_session_started
