// Code generated by generategomodels; DO NOT EDIT.

package runtime_session_started

import (
	validator "github.com/go-playground/validator/v10"
	"time"
)

type RuntimeSessionStartedStartupMode string

const (
	RuntimeSessionStartedStartupModeFresh RuntimeSessionStartedStartupMode = "fresh"

	RuntimeSessionStartedStartupModeResume RuntimeSessionStartedStartupMode = "resume"

	RuntimeSessionStartedStartupModeRestart RuntimeSessionStartedStartupMode = "restart"

	RuntimeSessionStartedStartupModeRecovery RuntimeSessionStartedStartupMode = "recovery"

	RuntimeSessionStartedStartupModeTest RuntimeSessionStartedStartupMode = "test"
)

type RuntimeSessionStarted struct {
	DatabaseID            string                            `json:"database_id" validate:"required,min=1"`
	DatabaseSchemaVersion *string                           `json:"database_schema_version,omitempty" validate:"omitempty,min=1"`
	ParentProcess         map[string]any                    `json:"parent_process" validate:"required"`
	ProtocolVersion       string                            `json:"protocol_version" validate:"required,min=1"`
	RuntimeSessionID      string                            `json:"runtime_session_id" validate:"required,min=1"`
	RuntimeVersion        string                            `json:"runtime_version" validate:"required,min=1"`
	StartupMode           *RuntimeSessionStartedStartupMode `json:"startup_mode,omitempty" validate:"omitempty"`
	StartupReason         *string                           `json:"startup_reason,omitempty" validate:"omitempty,min=1"`
	StartupTimestamp      time.Time                         `json:"startup_timestamp" validate:"required"`
}

func (value RuntimeSessionStarted) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
