// Code generated by generategomodels; DO NOT EDIT.

// Package repository_query_started contains generated Go models for the Kiln event/payload/repository-query-started schema.
package repository_query_started
