// Code generated by generategomodels; DO NOT EDIT.

package repository_query_started

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type RepositoryQueryStartedQueryKind string

const (
	RepositoryQueryStartedQueryKindSearch RepositoryQueryStartedQueryKind = "search"

	RepositoryQueryStartedQueryKindSource RepositoryQueryStartedQueryKind = "source"

	RepositoryQueryStartedQueryKindContent RepositoryQueryStartedQueryKind = "content"

	RepositoryQueryStartedQueryKindVersion RepositoryQueryStartedQueryKind = "version"

	RepositoryQueryStartedQueryKindDiagnostics RepositoryQueryStartedQueryKind = "diagnostics"
)

type RepositoryQueryStarted struct {
	QueryKind             RepositoryQueryStartedQueryKind `json:"query_kind" validate:"required"`
	QueryOperationID      string                          `json:"query_operation_id" validate:"required,min=1"`
	QueryRequestReference *artifact_reference.Reference   `json:"query_request_reference,omitempty" validate:"omitempty"`
	QueryStartedAt        time.Time                       `json:"query_started_at" validate:"required"`
	QuerySummary          map[string]any                  `json:"query_summary,omitempty" validate:"omitempty"`
	RepositorySessionID   string                          `json:"repository_session_id" validate:"required,min=1"`
}

func (value RepositoryQueryStarted) Validate() error {
	return shared.Validate(value)
}
