// Code generated by generategomodels; DO NOT EDIT.

// Package model_response_interpreted contains generated Go models for the Kiln event/payload/model-response-interpreted schema.
package model_response_interpreted
