// Code generated by generategomodels; DO NOT EDIT.

package model_response_interpreted

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	"time"
)

type ModelResponseInterpretedInterpretationKind string

const (
	ModelResponseInterpretedInterpretationKindAssistantMessage ModelResponseInterpretedInterpretationKind = "assistant_message"

	ModelResponseInterpretedInterpretationKindToolCallRequest ModelResponseInterpretedInterpretationKind = "tool_call_request"

	ModelResponseInterpretedInterpretationKindFinalAnswerCandidate ModelResponseInterpretedInterpretationKind = "final_answer_candidate"

	ModelResponseInterpretedInterpretationKindPatchCandidate ModelResponseInterpretedInterpretationKind = "patch_candidate"

	ModelResponseInterpretedInterpretationKindReportCandidate ModelResponseInterpretedInterpretationKind = "report_candidate"

	ModelResponseInterpretedInterpretationKindValidationJudgment ModelResponseInterpretedInterpretationKind = "validation_judgment"

	ModelResponseInterpretedInterpretationKindUnstructured ModelResponseInterpretedInterpretationKind = "unstructured"
)

type ModelResponseInterpreted struct {
	InterpretationKind         ModelResponseInterpretedInterpretationKind `json:"interpretation_kind" validate:"required"`
	InterpretationWarnings     []map[string]any                           `json:"interpretation_warnings,omitempty" validate:"omitempty,min=1"`
	InterpretedAt              time.Time                                  `json:"interpreted_at" validate:"required"`
	InterpretedOutputReference *artifact_reference.Reference              `json:"interpreted_output_reference,omitempty" validate:"omitempty"`
	ModelInvocationID          string                                     `json:"model_invocation_id" validate:"required,min=1"`
	ResponseArtifactReference  artifact_reference.Reference               `json:"response_artifact_reference" validate:"required"`
	ToolCallRequests           []map[string]any                           `json:"tool_call_requests,omitempty" validate:"omitempty,min=1"`
}

func (value ModelResponseInterpreted) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
