// Code generated by generategomodels; DO NOT EDIT.

package budget_exhausted

import (
	budget_state "github.com/julianstephens/kiln/go/schema/budget/state"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type BudgetExhaustedExhaustedDimensionsItem string

const (
	BudgetExhaustedExhaustedDimensionsItemModelInputTokens BudgetExhaustedExhaustedDimensionsItem = "model_input_tokens"

	BudgetExhaustedExhaustedDimensionsItemModelOutputTokens BudgetExhaustedExhaustedDimensionsItem = "model_output_tokens"

	BudgetExhaustedExhaustedDimensionsItemModelCalls BudgetExhaustedExhaustedDimensionsItem = "model_calls"

	BudgetExhaustedExhaustedDimensionsItemToolCalls BudgetExhaustedExhaustedDimensionsItem = "tool_calls"

	BudgetExhaustedExhaustedDimensionsItemRepositoryRequests BudgetExhaustedExhaustedDimensionsItem = "repository_requests"

	BudgetExhaustedExhaustedDimensionsItemElapsedWallTimeSeconds BudgetExhaustedExhaustedDimensionsItem = "elapsed_wall_time_seconds"

	BudgetExhaustedExhaustedDimensionsItemMonetaryCostUsd BudgetExhaustedExhaustedDimensionsItem = "monetary_cost_usd"

	BudgetExhaustedExhaustedDimensionsItemCommandTimeSeconds BudgetExhaustedExhaustedDimensionsItem = "command_time_seconds"

	BudgetExhaustedExhaustedDimensionsItemCommandOutputSizeBytes BudgetExhaustedExhaustedDimensionsItem = "command_output_size_bytes"

	BudgetExhaustedExhaustedDimensionsItemArtifactSizeBytes BudgetExhaustedExhaustedDimensionsItem = "artifact_size_bytes"

	BudgetExhaustedExhaustedDimensionsItemRepeatedTokenCostUsd BudgetExhaustedExhaustedDimensionsItem = "repeated_token_cost_usd"
)

type BudgetExhaustedExhaustionReason string

const (
	BudgetExhaustedExhaustionReasonCommittedUsageReachedLimit BudgetExhaustedExhaustionReason = "committed_usage_reached_limit"

	BudgetExhaustedExhaustionReasonReservationReachedLimit BudgetExhaustedExhaustionReason = "reservation_reached_limit"

	BudgetExhaustedExhaustionReasonReconciliationReachedLimit BudgetExhaustedExhaustionReason = "reconciliation_reached_limit"

	BudgetExhaustedExhaustionReasonExternalLimitReached BudgetExhaustedExhaustionReason = "external_limit_reached"

	BudgetExhaustedExhaustionReasonUnknown BudgetExhaustedExhaustionReason = "unknown"
)

// BudgetExhausted payload for budget.exhausted events.
type BudgetExhausted struct {
	BudgetID string `json:"budget_id" validate:"required,min=1"`
	// ExhaustedAt when budget exhaustion was detected.
	ExhaustedAt time.Time `json:"exhausted_at" validate:"required"`
	// ExhaustedDimensions budget dimensions that are exhausted.
	ExhaustedDimensions []BudgetExhaustedExhaustedDimensionsItem `json:"exhausted_dimensions" validate:"required,min=1"`
	// ExhaustionReason reason exhaustion was detected.
	ExhaustionReason *BudgetExhaustedExhaustionReason `json:"exhaustion_reason,omitempty" validate:"omitempty"`
	// StateAtExhaustion budget state when exhaustion was detected.
	StateAtExhaustion budget_state.State `json:"state_at_exhaustion" validate:"required"`
	// TriggeringCommitmentID commitment that caused exhaustion, when applicable.
	TriggeringCommitmentID *string `json:"triggering_commitment_id,omitempty" validate:"omitempty,min=1"`
	// TriggeringReservationID reservation that caused exhaustion, when applicable.
	TriggeringReservationID *string `json:"triggering_reservation_id,omitempty" validate:"omitempty,min=1"`
}

func (value BudgetExhausted) Validate() error {
	return shared.Validate(value)
}
