// Code generated by generategomodels; DO NOT EDIT.

package generate_payload

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	context_rendered "github.com/julianstephens/kiln/go/schema/context/rendered"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type GeneratePayload struct {
	GenerationParameters     map[string]any                `json:"generation_parameters" validate:"required"`
	LocalAdapterID           *string                       `json:"local_adapter_id,omitempty" validate:"omitempty,min=1"`
	ModelID                  string                        `json:"model_id" validate:"required,min=1"`
	ProviderID               *string                       `json:"provider_id,omitempty" validate:"omitempty,min=1"`
	RenderedContext          context_rendered.Rendered     `json:"rendered_context" validate:"required"`
	RequestArtifactReference *artifact_reference.Reference `json:"request_artifact_reference,omitempty" validate:"omitempty"`
	ResponseConstraints      map[string]any                `json:"response_constraints" validate:"required"`
	UserQuestion             *string                       `json:"user_question,omitempty" validate:"omitempty,min=1"`
}

func (value GeneratePayload) Validate() error {
	return shared.Validate(value)
}
