// Code generated by generategomodels; DO NOT EDIT.

package state

import (
	validator "github.com/go-playground/validator/v10"
)

type StateMode string

const (
	StateModeInstallationDefault StateMode = "installation_default"

	StateModeUnlimited StateMode = "unlimited"

	StateModeCustom StateMode = "custom"
)

type State struct {
	ArtifactSizeBytes         any            `json:"artifact_size_bytes,omitempty" validate:"omitempty"`
	CommandOutputSizeBytes    any            `json:"command_output_size_bytes,omitempty" validate:"omitempty"`
	CommandTimeSeconds        any            `json:"command_time_seconds,omitempty" validate:"omitempty"`
	ElapsedWallTimeSeconds    any            `json:"elapsed_wall_time_seconds,omitempty" validate:"omitempty"`
	EstimateVsActuals         map[string]any `json:"estimate_vs_actuals" validate:"required"`
	LatestTransactionSequence int            `json:"latest_transaction_sequence" validate:"required,gte=0"`
	Mode                      StateMode      `json:"mode" validate:"required"`
	ModelCalls                any            `json:"model_calls,omitempty" validate:"omitempty"`
	ModelInputTokens          any            `json:"model_input_tokens,omitempty" validate:"omitempty"`
	ModelOutputTokens         any            `json:"model_output_tokens,omitempty" validate:"omitempty"`
	MonetaryCostUsd           any            `json:"monetary_cost_usd,omitempty" validate:"omitempty"`
	RepeatedTokenCostUsd      any            `json:"repeated_token_cost_usd,omitempty" validate:"omitempty"`
	RepositoryRequests        any            `json:"repository_requests,omitempty" validate:"omitempty"`
	StateRevision             int            `json:"state_revision" validate:"required,gte=0"`
	ToolCalls                 any            `json:"tool_calls,omitempty" validate:"omitempty"`
}

func (value State) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
