// Code generated by generategomodels; DO NOT EDIT.

package context_plan_requested

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ContextPlanRequestedPlanningGoal string

const (
	ContextPlanRequestedPlanningGoalInitialContext ContextPlanRequestedPlanningGoal = "initial_context"

	ContextPlanRequestedPlanningGoalTurnContext ContextPlanRequestedPlanningGoal = "turn_context"

	ContextPlanRequestedPlanningGoalToolContext ContextPlanRequestedPlanningGoal = "tool_context"

	ContextPlanRequestedPlanningGoalOutputProduction ContextPlanRequestedPlanningGoal = "output_production"

	ContextPlanRequestedPlanningGoalValidation ContextPlanRequestedPlanningGoal = "validation"

	ContextPlanRequestedPlanningGoalRecovery ContextPlanRequestedPlanningGoal = "recovery"
)

type ContextPlanRequested struct {
	ActiveItemCount      *int                             `json:"active_item_count,omitempty" validate:"omitempty,gte=0"`
	AvailableItemCount   *int                             `json:"available_item_count,omitempty" validate:"omitempty,gte=0"`
	Constraints          map[string]any                   `json:"constraints,omitempty" validate:"omitempty"`
	ContextID            string                           `json:"context_id" validate:"required,min=1"`
	ContextPlanRequestID string                           `json:"context_plan_request_id" validate:"required,min=1"`
	CurrentTokenEstimate int                              `json:"current_token_estimate" validate:"required,gte=0"`
	ModelContextLimit    int                              `json:"model_context_limit" validate:"required,gte=0"`
	PinnedItemIds        []string                         `json:"pinned_item_ids,omitempty" validate:"omitempty"`
	PlanningGoal         ContextPlanRequestedPlanningGoal `json:"planning_goal" validate:"required"`
}

func (value ContextPlanRequested) Validate() error {
	return shared.Validate(value)
}
