// Code generated by generategomodels; DO NOT EDIT.

// Package model_request_rendered contains generated Go models for the Kiln event/payload/model-request-rendered schema.
package model_request_rendered
