// Code generated by generategomodels; DO NOT EDIT.

package model_request_rendered

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	model_configuration "github.com/julianstephens/kiln/go/schema/model/configuration"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type ModelRequestRenderedRequestKind string

const (
	ModelRequestRenderedRequestKindInitialResponse ModelRequestRenderedRequestKind = "initial_response"

	ModelRequestRenderedRequestKindTurnResponse ModelRequestRenderedRequestKind = "turn_response"

	ModelRequestRenderedRequestKindToolSelection ModelRequestRenderedRequestKind = "tool_selection"

	ModelRequestRenderedRequestKindToolResultFollowup ModelRequestRenderedRequestKind = "tool_result_followup"

	ModelRequestRenderedRequestKindOutputProduction ModelRequestRenderedRequestKind = "output_production"

	ModelRequestRenderedRequestKindValidation ModelRequestRenderedRequestKind = "validation"

	ModelRequestRenderedRequestKindRecovery ModelRequestRenderedRequestKind = "recovery"
)

// ModelRequestRendered payload for model.request_rendered events.
type ModelRequestRendered struct {
	// ModelConfiguration model configuration selected for the invocation.
	ModelConfiguration model_configuration.Configuration `json:"model_configuration" validate:"required"`
	// ModelInvocationID operation-local identity for the model invocation this rendered request belongs to.
	ModelInvocationID string `json:"model_invocation_id" validate:"required,min=1"`
	// RenderID context render identity used to produce the model request.
	RenderID string `json:"render_id" validate:"required,min=1"`
	// RenderedAt when the model request was rendered.
	RenderedAt time.Time `json:"rendered_at" validate:"required"`
	// RenderedMessagesCount number of messages rendered into the model request.
	RenderedMessagesCount *int `json:"rendered_messages_count,omitempty" validate:"omitempty,gte=0"`
	// RenderedTokenEstimate estimated number of input tokens in the rendered model request.
	RenderedTokenEstimate int `json:"rendered_token_estimate" validate:"required,gte=0"`
	// RenderedToolCount number of tool definitions rendered into the model request.
	RenderedToolCount *int `json:"rendered_tool_count,omitempty" validate:"omitempty,gte=0"`
	// RequestArtifactReference optional artifact reference for the rendered model request.
	RequestArtifactReference *artifact_reference.Reference `json:"request_artifact_reference,omitempty" validate:"omitempty"`
	// RequestKind logical kind of model request being rendered.
	RequestKind *ModelRequestRenderedRequestKind `json:"request_kind,omitempty" validate:"omitempty"`
}

func (value ModelRequestRendered) Validate() error {
	return shared.Validate(value)
}
