// Code generated by generategomodels; DO NOT EDIT.

package model_request_rendered

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	model_configuration "github.com/julianstephens/kiln/go/schema/model/configuration"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type ModelRequestRenderedRequestKind string

const (
	ModelRequestRenderedRequestKindInitialResponse ModelRequestRenderedRequestKind = "initial_response"

	ModelRequestRenderedRequestKindTurnResponse ModelRequestRenderedRequestKind = "turn_response"

	ModelRequestRenderedRequestKindToolSelection ModelRequestRenderedRequestKind = "tool_selection"

	ModelRequestRenderedRequestKindToolResultFollowup ModelRequestRenderedRequestKind = "tool_result_followup"

	ModelRequestRenderedRequestKindOutputProduction ModelRequestRenderedRequestKind = "output_production"

	ModelRequestRenderedRequestKindValidation ModelRequestRenderedRequestKind = "validation"

	ModelRequestRenderedRequestKindRecovery ModelRequestRenderedRequestKind = "recovery"
)

type ModelRequestRendered struct {
	ModelConfiguration       model_configuration.Configuration `json:"model_configuration" validate:"required"`
	ModelInvocationID        string                            `json:"model_invocation_id" validate:"required,min=1"`
	RenderID                 string                            `json:"render_id" validate:"required,min=1"`
	RenderedAt               time.Time                         `json:"rendered_at" validate:"required"`
	RenderedMessagesCount    *int                              `json:"rendered_messages_count,omitempty" validate:"omitempty,gte=0"`
	RenderedTokenEstimate    int                               `json:"rendered_token_estimate" validate:"required,gte=0"`
	RenderedToolCount        *int                              `json:"rendered_tool_count,omitempty" validate:"omitempty,gte=0"`
	RequestArtifactReference *artifact_reference.Reference     `json:"request_artifact_reference,omitempty" validate:"omitempty"`
	RequestKind              *ModelRequestRenderedRequestKind  `json:"request_kind,omitempty" validate:"omitempty"`
}

func (value ModelRequestRendered) Validate() error {
	return shared.Validate(value)
}
