// Code generated by generategomodels; DO NOT EDIT.

package turn_events

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// TurnEvents is generated from a nested JSON Schema object.
type TurnEvents struct {
}

func (value TurnEvents) Validate() error {
	return shared.Validate(value)
}
