// Code generated by generategomodels; DO NOT EDIT.

package turn_events

import (
	validator "github.com/go-playground/validator/v10"
)

type TurnEvents struct {
}

func (value TurnEvents) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
