// Code generated by generategomodels; DO NOT EDIT.

package run_created

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	budget_limits "github.com/julianstephens/kiln/go/schema/budget/limits"
	capability_security_profile "github.com/julianstephens/kiln/go/schema/capability/security_profile"
	repository_identifier "github.com/julianstephens/kiln/go/schema/repository/identifier"
	validation_requirement "github.com/julianstephens/kiln/go/schema/validation/requirement"
)

type RunCreated struct {
	Repository               repository_identifier.IDentifier            `json:"repository" validate:"required"`
	RequestedBudgets         budget_limits.Limits                        `json:"requested_budgets" validate:"required"`
	RequestedModel           string                                      `json:"requested_model" validate:"required,min=1"`
	RequestedSecurityProfile capability_security_profile.SecurityProfile `json:"requested_security_profile" validate:"required"`
	RunSpecificationID       string                                      `json:"run_specification_id" validate:"required,min=1"`
	TaskArtifactReferences   []artifact_reference.Reference              `json:"task_artifact_references,omitempty" validate:"omitempty,min=1"`
	TaskHash                 *string                                     `json:"task_hash,omitempty" validate:"omitempty,min=1"`
	TaskID                   *string                                     `json:"task_id,omitempty" validate:"omitempty,min=1"`
	ValidationRequirements   []validation_requirement.Requirement        `json:"validation_requirements,omitempty" validate:"omitempty,min=1"`
}

func (value RunCreated) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
