// Code generated by generategomodels; DO NOT EDIT.

package run_completed

import (
	artifact_validation_report_reference "github.com/julianstephens/kiln/go/schema/artifact/validation_report_reference"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	run_stop_reason "github.com/julianstephens/kiln/go/schema/run/stop_reason"
	run_terminal_result_reference "github.com/julianstephens/kiln/go/schema/run/terminal_result_reference"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type RunCompleted struct {
	FinalResultReference      run_terminal_result_reference.TerminalResultReference           `json:"final_result_reference" validate:"required"`
	FinalUsage                budget_usage.Usage                                              `json:"final_usage" validate:"required"`
	StopReason                run_stop_reason.StopReason                                      `json:"stop_reason" validate:"required"`
	ValidationReportReference *artifact_validation_report_reference.ValidationReportReference `json:"validation_report_reference,omitempty" validate:"omitempty"`
}

func (value RunCompleted) Validate() error {
	return shared.Validate(value)
}
