// Code generated by generategomodels; DO NOT EDIT.

// Package search_request_payload contains generated Go models for the Kiln repository/search-request-payload schema.
package search_request_payload
