// Code generated by generategomodels; DO NOT EDIT.

package decision

import (
	capability_grant "github.com/julianstephens/kiln/go/schema/capability/grant"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type DecisionDecision string

const (
	DecisionDecisionGranted DecisionDecision = "granted"

	DecisionDecisionDenied DecisionDecision = "denied"
)

// Decision is generated from a nested JSON Schema object.
type Decision struct {
	// Decision the decision that was made for this capability request.
	Decision DecisionDecision `json:"decision" validate:"required"`
	// Grant the grant that was issued for this capability request.
	Grant capability_grant.Grant `json:"grant" validate:"required"`
	// Reason the reason that this capability request was granted or denied.
	Reason string `json:"reason" validate:"required,min=1"`
}

func (value Decision) Validate() error {
	return shared.Validate(value)
}
