// Code generated by generategomodels; DO NOT EDIT.

package decision

import (
	capability_grant "github.com/julianstephens/kiln/go/schema/capability/grant"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type DecisionDecision string

const (
	DecisionDecisionGranted DecisionDecision = "granted"

	DecisionDecisionDenied DecisionDecision = "denied"
)

type Decision struct {
	Decision DecisionDecision       `json:"decision" validate:"required"`
	Grant    capability_grant.Grant `json:"grant" validate:"required"`
	Reason   string                 `json:"reason" validate:"required,min=1"`
}

func (value Decision) Validate() error {
	return shared.Validate(value)
}
