// Code generated by generategomodels; DO NOT EDIT.

package error

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type Error struct {
	KilnError map[string]any `json:"kiln_error" validate:"required"`
}

func (value Error) Validate() error {
	return shared.Validate(value)
}
