// Code generated by generategomodels; DO NOT EDIT.

package error

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// Error is generated from a nested JSON Schema object.
type Error struct {
	// KilnError information about the error that occurred.
	KilnError ErrorKilnError `json:"kiln_error" validate:"required"`
}

type ErrorKilnErrorCategory string

const (
	ErrorKilnErrorCategoryCompatibility ErrorKilnErrorCategory = "compatibility"

	ErrorKilnErrorCategoryValidation ErrorKilnErrorCategory = "validation"

	ErrorKilnErrorCategoryLifecycle ErrorKilnErrorCategory = "lifecycle"

	ErrorKilnErrorCategoryShutdown ErrorKilnErrorCategory = "shutdown"

	ErrorKilnErrorCategoryInternal ErrorKilnErrorCategory = "internal"
)

// ErrorKilnError information about the error that occurred.
type ErrorKilnError struct {
	// Category the error category.
	Category ErrorKilnErrorCategory `json:"category" validate:"required"`
	// Code the error code.
	Code string `json:"code" validate:"required,min=1"`
	// CorrelationID a correlation ID for the error, if available.
	CorrelationID *string `json:"correlation_id,omitempty" validate:"omitempty,min=1"`
	// Details additional details about the error.
	Details map[string]any `json:"details" validate:"required"`
	// Message a human-readable message describing the error.
	Message string `json:"message" validate:"required,min=1"`
	// Retryable whether the error is retryable.
	Retryable bool `json:"retryable"`
	// RuntimeID the unique identifier of the runtime that generated the error.
	RuntimeID *string `json:"runtime_id,omitempty" validate:"omitempty,min=1"`
}

func (value Error) Validate() error {
	return shared.Validate(value)
}
