// Code generated by generategomodels; DO NOT EDIT.

package schema_requirement

import (
	validator "github.com/go-playground/validator/v10"
)

type SchemaRequirementMode string

const (
	SchemaRequirementModeStrict SchemaRequirementMode = "strict"

	SchemaRequirementModePermissive SchemaRequirementMode = "permissive"
)

type SchemaRequirement struct {
	InstanceRef string                `json:"instance_ref" validate:"required,min=1"`
	Mode        SchemaRequirementMode `json:"mode" validate:"required"`
	SchemaID    string                `json:"schema_id" validate:"required,min=1"`
}

func (value SchemaRequirement) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
