// Code generated by generategomodels; DO NOT EDIT.

package schema_requirement

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type SchemaRequirementMode string

const (
	SchemaRequirementModeStrict SchemaRequirementMode = "strict"

	SchemaRequirementModePermissive SchemaRequirementMode = "permissive"
)

// SchemaRequirement is generated from a nested JSON Schema object.
type SchemaRequirement struct {
	InstanceRef string                `json:"instance_ref" validate:"required,min=1"`
	Mode        SchemaRequirementMode `json:"mode" validate:"required"`
	SchemaID    string                `json:"schema_id" validate:"required,min=1"`
}

func (value SchemaRequirement) Validate() error {
	return shared.Validate(value)
}
