// Code generated by generategomodels; DO NOT EDIT.

package schema

import "github.com/go-playground/validator/v10"

var validate = validator.New()

type Validatable interface {
	Validate() error
}

func Validate(value any) error {
	return validate.Struct(value)
}
