// Code generated by generategomodels; DO NOT EDIT.

package run_lifecycle_events

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type RunLifecycleEvents struct {
}

func (value RunLifecycleEvents) Validate() error {
	return shared.Validate(value)
}
