// Code generated by generategomodels; DO NOT EDIT.

package run_lifecycle_events

import (
	validator "github.com/go-playground/validator/v10"
)

type RunLifecycleEvents struct {
}

func (value RunLifecycleEvents) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
