// Code generated by generategomodels; DO NOT EDIT.

package reservation

import (
	budget_limits "github.com/julianstephens/kiln/go/schema/budget/limits"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type ReservationReservationReason string

const (
	ReservationReservationReasonModelInvocation ReservationReservationReason = "model_invocation"

	ReservationReservationReasonToolInvocation ReservationReservationReason = "tool_invocation"

	ReservationReservationReasonRepositoryOperation ReservationReservationReason = "repository_operation"

	ReservationReservationReasonOutputProduction ReservationReservationReason = "output_production"

	ReservationReservationReasonValidation ReservationReservationReason = "validation"

	ReservationReservationReasonArtifactWrite ReservationReservationReason = "artifact_write"

	ReservationReservationReasonRuntimeOperation ReservationReservationReason = "runtime_operation"

	ReservationReservationReasonOther ReservationReservationReason = "other"
)

type ReservationReservationScope string

const (
	ReservationReservationScopeRun ReservationReservationScope = "run"

	ReservationReservationScopeTurn ReservationReservationScope = "turn"

	ReservationReservationScopeOperation ReservationReservationScope = "operation"

	ReservationReservationScopeComponent ReservationReservationScope = "component"
)

type ReservationReservationStatus string

const (
	ReservationReservationStatusActive ReservationReservationStatus = "active"

	ReservationReservationStatusPartiallyCommitted ReservationReservationStatus = "partially_committed"

	ReservationReservationStatusCommitted ReservationReservationStatus = "committed"

	ReservationReservationStatusReleased ReservationReservationStatus = "released"

	ReservationReservationStatusExpired ReservationReservationStatus = "expired"

	ReservationReservationStatusCanceled ReservationReservationStatus = "canceled"
)

// Reservation a reservation of budget capacity for a run, turn, operation, or component before usage is committed or released.
type Reservation struct {
	// BudgetID budget ledger or accounting scope this reservation belongs to.
	BudgetID string `json:"budget_id" validate:"required,min=1"`
	// ClosedAt when the reservation reached a terminal status.
	ClosedAt *time.Time `json:"closed_at,omitempty" validate:"omitempty"`
	// CommittedUsage usage already committed against this reservation.
	CommittedUsage *budget_usage.Usage `json:"committed_usage,omitempty" validate:"omitempty"`
	// Component logical component associated with this reservation, when applicable.
	Component *string `json:"component,omitempty" validate:"omitempty,min=1"`
	// CreatedAt when the reservation was created.
	CreatedAt time.Time `json:"created_at" validate:"required"`
	// ExpiresAt when the reservation expires if not committed or released.
	ExpiresAt *time.Time `json:"expires_at,omitempty" validate:"omitempty"`
	// OperationID operation associated with this reservation, when applicable.
	OperationID *string `json:"operation_id,omitempty" validate:"omitempty,min=1"`
	// ReservationID stable identity for this budget reservation.
	ReservationID string `json:"reservation_id" validate:"required,min=1"`
	// ReservationReason reason the reservation was created.
	ReservationReason *ReservationReservationReason `json:"reservation_reason,omitempty" validate:"omitempty"`
	// ReservationScope scope for which budget capacity was reserved.
	ReservationScope ReservationReservationScope `json:"reservation_scope" validate:"required"`
	// ReservationStatus current status of the reservation.
	ReservationStatus ReservationReservationStatus `json:"reservation_status" validate:"required"`
	// ReservedAmounts budget amounts reserved by dimension.
	ReservedAmounts budget_limits.Limits `json:"reserved_amounts" validate:"required"`
	// RunID run associated with this reservation, when applicable.
	RunID *string `json:"run_id,omitempty" validate:"omitempty,min=1"`
	// TurnID turn associated with this reservation, when applicable.
	TurnID *string `json:"turn_id,omitempty" validate:"omitempty,min=1"`
}

func (value Reservation) Validate() error {
	return shared.Validate(value)
}
