// Code generated by generategomodels; DO NOT EDIT.

package reservation

import (
	validator "github.com/go-playground/validator/v10"
	budget_limits "github.com/julianstephens/kiln/go/schema/budget/limits"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	"time"
)

type ReservationReservationReason string

const (
	ReservationReservationReasonModelInvocation ReservationReservationReason = "model_invocation"

	ReservationReservationReasonToolInvocation ReservationReservationReason = "tool_invocation"

	ReservationReservationReasonRepositoryOperation ReservationReservationReason = "repository_operation"

	ReservationReservationReasonOutputProduction ReservationReservationReason = "output_production"

	ReservationReservationReasonValidation ReservationReservationReason = "validation"

	ReservationReservationReasonArtifactWrite ReservationReservationReason = "artifact_write"

	ReservationReservationReasonRuntimeOperation ReservationReservationReason = "runtime_operation"

	ReservationReservationReasonOther ReservationReservationReason = "other"
)

type ReservationReservationScope string

const (
	ReservationReservationScopeRun ReservationReservationScope = "run"

	ReservationReservationScopeTurn ReservationReservationScope = "turn"

	ReservationReservationScopeOperation ReservationReservationScope = "operation"

	ReservationReservationScopeComponent ReservationReservationScope = "component"
)

type ReservationReservationStatus string

const (
	ReservationReservationStatusActive ReservationReservationStatus = "active"

	ReservationReservationStatusPartiallyCommitted ReservationReservationStatus = "partially_committed"

	ReservationReservationStatusCommitted ReservationReservationStatus = "committed"

	ReservationReservationStatusReleased ReservationReservationStatus = "released"

	ReservationReservationStatusExpired ReservationReservationStatus = "expired"

	ReservationReservationStatusCanceled ReservationReservationStatus = "canceled"
)

type Reservation struct {
	BudgetID          string                        `json:"budget_id" validate:"required,min=1"`
	ClosedAt          *time.Time                    `json:"closed_at,omitempty" validate:"omitempty"`
	CommittedUsage    *budget_usage.Usage           `json:"committed_usage,omitempty" validate:"omitempty"`
	Component         *string                       `json:"component,omitempty" validate:"omitempty,min=1"`
	CreatedAt         time.Time                     `json:"created_at" validate:"required"`
	ExpiresAt         *time.Time                    `json:"expires_at,omitempty" validate:"omitempty"`
	OperationID       *string                       `json:"operation_id,omitempty" validate:"omitempty,min=1"`
	ReservationID     string                        `json:"reservation_id" validate:"required,min=1"`
	ReservationReason *ReservationReservationReason `json:"reservation_reason,omitempty" validate:"omitempty"`
	ReservationScope  ReservationReservationScope   `json:"reservation_scope" validate:"required"`
	ReservationStatus ReservationReservationStatus  `json:"reservation_status" validate:"required"`
	ReservedAmounts   budget_limits.Limits          `json:"reserved_amounts" validate:"required"`
	RunID             *string                       `json:"run_id,omitempty" validate:"omitempty,min=1"`
	TurnID            *string                       `json:"turn_id,omitempty" validate:"omitempty,min=1"`
}

func (value Reservation) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
