// Code generated by generategomodels; DO NOT EDIT.

package budget_events

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type BudgetEvents struct {
}

func (value BudgetEvents) Validate() error {
	return shared.Validate(value)
}
