// Code generated by generategomodels; DO NOT EDIT.

package budget_events

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// BudgetEvents is generated from a nested JSON Schema object.
type BudgetEvents struct {
}

func (value BudgetEvents) Validate() error {
	return shared.Validate(value)
}
