// Code generated by generategomodels; DO NOT EDIT.

package budget_events

import (
	validator "github.com/go-playground/validator/v10"
)

type BudgetEvents struct {
}

func (value BudgetEvents) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
