// Code generated by generategomodels; DO NOT EDIT.

// Package run_initialization_completed contains generated Go models for the Kiln event/payload/run-initialization-completed schema.
package run_initialization_completed
