// Code generated by generategomodels; DO NOT EDIT.

package run_initialization_completed

import (
	budget_state "github.com/julianstephens/kiln/go/schema/budget/state"
	capability_security_profile "github.com/julianstephens/kiln/go/schema/capability/security_profile"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type RunInitializationCompleted struct {
	Deadline                   *time.Time                                  `json:"deadline,omitempty" validate:"omitempty"`
	EffectiveBudgets           budget_state.State                          `json:"effective_budgets" validate:"required"`
	EffectiveCapabilityProfile capability_security_profile.SecurityProfile `json:"effective_capability_profile" validate:"required"`
	InitializationDuration     int                                         `json:"initialization_duration" validate:"required,gte=0"`
	SelectedAdapterIds         []string                                    `json:"selected_adapter_ids,omitempty" validate:"omitempty,min=1"`
}

func (value RunInitializationCompleted) Validate() error {
	return shared.Validate(value)
}
