// Code generated by generategomodels; DO NOT EDIT.

package run_initialization_completed

import (
	validator "github.com/go-playground/validator/v10"
	budget_state "github.com/julianstephens/kiln/go/schema/budget/state"
	capability_security_profile "github.com/julianstephens/kiln/go/schema/capability/security_profile"
	"time"
)

type RunInitializationCompleted struct {
	Deadline                   *time.Time                                  `json:"deadline,omitempty" validate:"omitempty"`
	EffectiveBudgets           budget_state.State                          `json:"effective_budgets" validate:"required"`
	EffectiveCapabilityProfile capability_security_profile.SecurityProfile `json:"effective_capability_profile" validate:"required"`
	InitializationDuration     int                                         `json:"initialization_duration" validate:"required,gte=0"`
	SelectedAdapterIDs         []string                                    `json:"selected_adapter_ids,omitempty" validate:"omitempty,min=1"`
}

func (value RunInitializationCompleted) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
