// Code generated by generategomodels; DO NOT EDIT.

package open_session_response

import (
	validator "github.com/go-playground/validator/v10"
)

type OpenSessionResponse struct {
}

func (value OpenSessionResponse) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
