// Code generated by generategomodels; DO NOT EDIT.

package open_session_response

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type OpenSessionResponse struct {
}

func (value OpenSessionResponse) Validate() error {
	return shared.Validate(value)
}
