// Code generated by generategomodels; DO NOT EDIT.

package generate_request

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type GenerateRequest struct {
}

func (value GenerateRequest) Validate() error {
	return shared.Validate(value)
}
