// Code generated by generategomodels; DO NOT EDIT.

package generate_request

import (
	validator "github.com/go-playground/validator/v10"
)

type GenerateRequest struct {
}

func (value GenerateRequest) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
