// Code generated by generategomodels; DO NOT EDIT.

package run_execution_started

import (
	validator "github.com/go-playground/validator/v10"
	repository_version "github.com/julianstephens/kiln/go/schema/repository/version"
	workspace_version "github.com/julianstephens/kiln/go/schema/workspace/version"
)

type RunExecutionStarted struct {
	InitialTurnID       string                     `json:"initial_turn_id" validate:"required,min=1"`
	RepositorySessionID string                     `json:"repository_session_id" validate:"required,min=1"`
	RepositoryVersion   repository_version.Version `json:"repository_version" validate:"required"`
	WorkspaceVersion    workspace_version.Version  `json:"workspace_version" validate:"required"`
}

func (value RunExecutionStarted) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
