// Code generated by generategomodels; DO NOT EDIT.

package policy_requirement

import (
	validator "github.com/go-playground/validator/v10"
)

type PolicyRequirementPolicyKind string

const (
	PolicyRequirementPolicyKindSecurity PolicyRequirementPolicyKind = "security"

	PolicyRequirementPolicyKindPrivacy PolicyRequirementPolicyKind = "privacy"

	PolicyRequirementPolicyKindCompliance PolicyRequirementPolicyKind = "compliance"
)

type PolicyRequirement struct {
	FailureCode string                      `json:"failure_code" validate:"required,min=1"`
	Inputs      []string                    `json:"inputs" validate:"required,min=1"`
	PolicyID    string                      `json:"policy_id" validate:"required,min=1"`
	PolicyKind  PolicyRequirementPolicyKind `json:"policy_kind" validate:"required"`
}

func (value PolicyRequirement) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
