// Code generated by generategomodels; DO NOT EDIT.

package relevance

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// Relevance search and ranking metadata describing why a repository candidate is relevant to a query.
type Relevance struct {
	GraphDistance    int      `json:"graph_distance" validate:"required,gte=0"`
	HybridScore      int      `json:"hybrid_score" validate:"required,gte=0"`
	LexicalScore     int      `json:"lexical_score" validate:"required,gte=0"`
	MatchTerms       []string `json:"match_terms" validate:"required"`
	Rank             int      `json:"rank" validate:"required,gte=1"`
	ScoreExplanation string   `json:"score_explanation" validate:"required,min=1"`
	SemanticScore    int      `json:"semantic_score" validate:"required,gte=0"`
}

func (value Relevance) Validate() error {
	return shared.Validate(value)
}
