// Code generated by generategomodels; DO NOT EDIT.

package budget_initialized

import (
	validator "github.com/go-playground/validator/v10"
	budget_limits "github.com/julianstephens/kiln/go/schema/budget/limits"
	budget_state "github.com/julianstephens/kiln/go/schema/budget/state"
	"time"
)

type BudgetInitializedBudgetScope string

const (
	BudgetInitializedBudgetScopeRun BudgetInitializedBudgetScope = "run"

	BudgetInitializedBudgetScopeTurn BudgetInitializedBudgetScope = "turn"

	BudgetInitializedBudgetScopeOperation BudgetInitializedBudgetScope = "operation"

	BudgetInitializedBudgetScopeComponent BudgetInitializedBudgetScope = "component"
)

type BudgetInitialized struct {
	BudgetID      string                       `json:"budget_id" validate:"required,min=1"`
	BudgetScope   BudgetInitializedBudgetScope `json:"budget_scope" validate:"required"`
	Component     *string                      `json:"component,omitempty" validate:"omitempty,min=1"`
	InitialState  budget_state.State           `json:"initial_state" validate:"required"`
	InitializedAt time.Time                    `json:"initialized_at" validate:"required"`
	Limits        budget_limits.Limits         `json:"limits" validate:"required"`
	OperationID   *string                      `json:"operation_id,omitempty" validate:"omitempty,min=1"`
	RunID         *string                      `json:"run_id,omitempty" validate:"omitempty,min=1"`
	TurnID        *string                      `json:"turn_id,omitempty" validate:"omitempty,min=1"`
}

func (value BudgetInitialized) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
