// Code generated by generategomodels; DO NOT EDIT.

package context_events

import (
	validator "github.com/go-playground/validator/v10"
)

type ContextEvents struct {
}

func (value ContextEvents) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
