// Code generated by generategomodels; DO NOT EDIT.

package context_events

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ContextEvents struct {
}

func (value ContextEvents) Validate() error {
	return shared.Validate(value)
}
