// Code generated by generategomodels; DO NOT EDIT.

package context_events

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// ContextEvents is generated from a nested JSON Schema object.
type ContextEvents struct {
}

func (value ContextEvents) Validate() error {
	return shared.Validate(value)
}
