// Code generated by generategomodels; DO NOT EDIT.

package state

import (
	validator "github.com/go-playground/validator/v10"
)

type State struct {
	ActiveItemIDs        []map[string]any `json:"active_item_ids,omitempty" validate:"omitempty"`
	AvailableItemIDs     []string         `json:"available_item_ids,omitempty" validate:"omitempty"`
	ContextID            string           `json:"context_id" validate:"required,min=1"`
	ContextStateRevision int              `json:"context_state_revision" validate:"required,gte=0"`
	CurrentTokenEstimate int              `json:"current_token_estimate" validate:"required,gte=0"`
	ModelContextLimit    int              `json:"model_context_limit" validate:"required,gte=0"`
	ObservedItemIDs      []string         `json:"observed_item_ids,omitempty" validate:"omitempty"`
	PinnedItemIDs        []string         `json:"pinned_item_ids,omitempty" validate:"omitempty"`
	StaleItemIDs         []string         `json:"stale_item_ids,omitempty" validate:"omitempty"`
}

func (value State) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
