// Code generated by generategomodels; DO NOT EDIT.

package artifact_created

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	"time"
)

type ArtifactCreatedCreatedBy string

const (
	ArtifactCreatedCreatedByRuntime ArtifactCreatedCreatedBy = "runtime"

	ArtifactCreatedCreatedByContextRenderer ArtifactCreatedCreatedBy = "context_renderer"

	ArtifactCreatedCreatedByModelAdapter ArtifactCreatedCreatedBy = "model_adapter"

	ArtifactCreatedCreatedByModelInterpreter ArtifactCreatedCreatedBy = "model_interpreter"

	ArtifactCreatedCreatedByRepositoryWorker ArtifactCreatedCreatedBy = "repository_worker"

	ArtifactCreatedCreatedByArtifactStore ArtifactCreatedCreatedBy = "artifact_store"

	ArtifactCreatedCreatedByOutputProducer ArtifactCreatedCreatedBy = "output_producer"

	ArtifactCreatedCreatedByValidator ArtifactCreatedCreatedBy = "validator"

	ArtifactCreatedCreatedByTestHarness ArtifactCreatedCreatedBy = "test_harness"

	ArtifactCreatedCreatedByUnknown ArtifactCreatedCreatedBy = "unknown"
)

type ArtifactCreatedCreationReason string

const (
	ArtifactCreatedCreationReasonModelRequestRendered ArtifactCreatedCreationReason = "model_request_rendered"

	ArtifactCreatedCreationReasonModelResponseReceived ArtifactCreatedCreationReason = "model_response_received"

	ArtifactCreatedCreationReasonCandidateBatchMaterialized ArtifactCreatedCreationReason = "candidate_batch_materialized"

	ArtifactCreatedCreationReasonFinalResultBundleCreated ArtifactCreatedCreationReason = "final_result_bundle_created"

	ArtifactCreatedCreationReasonOutputProduction ArtifactCreatedCreationReason = "output_production"

	ArtifactCreatedCreationReasonValidation ArtifactCreatedCreationReason = "validation"

	ArtifactCreatedCreationReasonDiagnostic ArtifactCreatedCreationReason = "diagnostic"

	ArtifactCreatedCreationReasonRepositorySnapshot ArtifactCreatedCreationReason = "repository_snapshot"

	ArtifactCreatedCreationReasonOther ArtifactCreatedCreationReason = "other"
)

type ArtifactCreated struct {
	Artifact                 artifact_reference.Reference   `json:"artifact" validate:"required"`
	ArtifactMetadata         map[string]any                 `json:"artifact_metadata,omitempty" validate:"omitempty"`
	CreatedAt                time.Time                      `json:"created_at" validate:"required"`
	CreatedBy                ArtifactCreatedCreatedBy       `json:"created_by" validate:"required"`
	CreationReason           ArtifactCreatedCreationReason  `json:"creation_reason" validate:"required"`
	ProducerOperationID      *string                        `json:"producer_operation_id,omitempty" validate:"omitempty,min=1"`
	SourceArtifactReferences []artifact_reference.Reference `json:"source_artifact_references,omitempty" validate:"omitempty,min=1"`
}

func (value ArtifactCreated) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
