// Code generated by generategomodels; DO NOT EDIT.

package validity

import (
	validator "github.com/go-playground/validator/v10"
)

type ValidityContentCompleteness string

const (
	ValidityContentCompletenessComplete ValidityContentCompleteness = "complete"

	ValidityContentCompletenessTruncated ValidityContentCompleteness = "truncated"
)

type ValidityContentStatus string

const (
	ValidityContentStatusCurrent ValidityContentStatus = "current"

	ValidityContentStatusStale ValidityContentStatus = "stale"
)

type ValiditySynchronizationStatus string

const (
	ValiditySynchronizationStatusSynchronized ValiditySynchronizationStatus = "synchronized"

	ValiditySynchronizationStatusOutOfSync ValiditySynchronizationStatus = "out_of_sync"
)

type Validity struct {
	ContentCompleteness   *ValidityContentCompleteness   `json:"content_completeness,omitempty" validate:"omitempty"`
	ContentStatus         *ValidityContentStatus         `json:"content_status,omitempty" validate:"omitempty"`
	InvalidationReason    *string                        `json:"invalidation_reason,omitempty" validate:"omitempty,min=1"`
	SynchronizationStatus *ValiditySynchronizationStatus `json:"synchronization_status,omitempty" validate:"omitempty"`
	Version               *string                        `json:"version,omitempty" validate:"omitempty,min=1"`
}

func (value Validity) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
