// Code generated by generategomodels; DO NOT EDIT.

package validity

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ValidityContentCompleteness string

const (
	ValidityContentCompletenessComplete ValidityContentCompleteness = "complete"

	ValidityContentCompletenessTruncated ValidityContentCompleteness = "truncated"
)

type ValidityContentStatus string

const (
	ValidityContentStatusCurrent ValidityContentStatus = "current"

	ValidityContentStatusStale ValidityContentStatus = "stale"
)

type ValiditySynchronizationStatus string

const (
	ValiditySynchronizationStatusSynchronized ValiditySynchronizationStatus = "synchronized"

	ValiditySynchronizationStatusOutOfSync ValiditySynchronizationStatus = "out_of_sync"
)

type Validity struct {
	ContentCompleteness   *ValidityContentCompleteness   `json:"content_completeness,omitempty" validate:"omitempty"`
	ContentStatus         *ValidityContentStatus         `json:"content_status,omitempty" validate:"omitempty"`
	InvalidationReason    *string                        `json:"invalidation_reason,omitempty" validate:"omitempty,min=1"`
	SynchronizationStatus *ValiditySynchronizationStatus `json:"synchronization_status,omitempty" validate:"omitempty"`
	Version               *string                        `json:"version,omitempty" validate:"omitempty,min=1"`
}

func (value Validity) Validate() error {
	return shared.Validate(value)
}
