// Code generated by generategomodels; DO NOT EDIT.

package task_specification

import (
	run_task_provenance "github.com/julianstephens/kiln/go/schema/run/task_provenance"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type TaskSpecification struct {
	Constraints        []string                           `json:"constraints" validate:"required"`
	Deliverables       []string                           `json:"deliverables" validate:"required"`
	Description        string                             `json:"description" validate:"required,min=1"`
	IssueReferences    []string                           `json:"issue_references,omitempty" validate:"omitempty"`
	Provenance         run_task_provenance.TaskProvenance `json:"provenance" validate:"required"`
	SuccessCriteria    []string                           `json:"success_criteria" validate:"required,min=1"`
	Targets            []string                           `json:"targets,omitempty" validate:"omitempty"`
	WorkflowReferences []string                           `json:"workflow_references,omitempty" validate:"omitempty"`
}

func (value TaskSpecification) Validate() error {
	return shared.Validate(value)
}
