// Code generated by generategomodels; DO NOT EDIT.

package output_mode

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// OutputMode is generated from a nested JSON Schema object.
type OutputMode struct {
}

func (value OutputMode) Validate() error {
	return shared.Validate(value)
}
