// Code generated by generategomodels; DO NOT EDIT.

package output_mode

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type OutputMode struct {
}

func (value OutputMode) Validate() error {
	return shared.Validate(value)
}
