// Code generated by generategomodels; DO NOT EDIT.

package output_mode

import (
	validator "github.com/go-playground/validator/v10"
)

type OutputMode struct {
}

func (value OutputMode) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
