// Code generated by generategomodels; DO NOT EDIT.

package identifier

import (
	validator "github.com/go-playground/validator/v10"
)

type IDentifier struct {
	ID                 string  `json:"id" validate:"required,min=1"`
	VersionID          string  `json:"version_id" validate:"required,min=1"`
	WorkspaceID        *string `json:"workspace_id,omitempty" validate:"omitempty,min=1"`
	WorkspaceVersionID string  `json:"workspace_version_id" validate:"required,min=1"`
}

func (value IDentifier) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
