// Code generated by generategomodels; DO NOT EDIT.

package identifier

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// Identifier is generated from a nested JSON Schema object.
type Identifier struct {
	ID                 string  `json:"id" validate:"required,min=1"`
	VersionID          string  `json:"version_id" validate:"required,min=1"`
	WorkspaceID        *string `json:"workspace_id,omitempty" validate:"omitempty,min=1"`
	WorkspaceVersionID string  `json:"workspace_version_id" validate:"required,min=1"`
}

func (value Identifier) Validate() error {
	return shared.Validate(value)
}
