// Code generated by generategomodels; DO NOT EDIT.

package search_request

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type SearchRequest struct {
}

func (value SearchRequest) Validate() error {
	return shared.Validate(value)
}
