// Code generated by generategomodels; DO NOT EDIT.

package search_request

import (
	validator "github.com/go-playground/validator/v10"
)

type SearchRequest struct {
}

func (value SearchRequest) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
