// Code generated by generategomodels; DO NOT EDIT.

package protocol_request

import (
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type ProtocolRequest struct {
	CorrelationID   *string        `json:"correlation_id,omitempty" validate:"omitempty,min=1"`
	Deadline        *time.Time     `json:"deadline,omitempty" validate:"omitempty"`
	Operation       string         `json:"operation" validate:"required,min=1"`
	Payload         map[string]any `json:"payload" validate:"required"`
	ProtocolVersion string         `json:"protocol_version" validate:"required"`
	RequestID       string         `json:"request_id" validate:"required,min=1"`
}

func (value ProtocolRequest) Validate() error {
	return shared.Validate(value)
}
