// Code generated by generategomodels; DO NOT EDIT.

// Package validation_report_reference contains generated Go models for the Kiln artifact/validation-report-reference schema.
package validation_report_reference
