// Code generated by generategomodels; DO NOT EDIT.

package validation_report_reference

import (
	validator "github.com/go-playground/validator/v10"
)

type ValidationReportReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value ValidationReportReference) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
