// Code generated by generategomodels; DO NOT EDIT.

package validation_report_reference

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ValidationReportReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value ValidationReportReference) Validate() error {
	return shared.Validate(value)
}
