// Code generated by generategomodels; DO NOT EDIT.

package protocol_response

import (
	validator "github.com/go-playground/validator/v10"
)

type ProtocolResponse struct {
}

func (value ProtocolResponse) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
