// Code generated by generategomodels; DO NOT EDIT.

// Package repository_worker_started contains generated Go models for the Kiln event/payload/repository-worker-started schema.
package repository_worker_started
