// Code generated by generategomodels; DO NOT EDIT.

package repository_worker_started

import (
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type RepositoryWorkerStartedSupportedOperationsItem string

const (
	RepositoryWorkerStartedSupportedOperationsItemRepositoryOpenSession RepositoryWorkerStartedSupportedOperationsItem = "repository.open_session"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryCloseSession RepositoryWorkerStartedSupportedOperationsItem = "repository.close_session"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryPrepare RepositoryWorkerStartedSupportedOperationsItem = "repository.prepare"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryGetPreparationStatus RepositoryWorkerStartedSupportedOperationsItem = "repository.get_preparation_status"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryGetVersion RepositoryWorkerStartedSupportedOperationsItem = "repository.get_version"

	RepositoryWorkerStartedSupportedOperationsItemRepositorySearch RepositoryWorkerStartedSupportedOperationsItem = "repository.search"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryGetSource RepositoryWorkerStartedSupportedOperationsItem = "repository.get_source"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryGetContent RepositoryWorkerStartedSupportedOperationsItem = "repository.get_content"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryGetDiagnostics RepositoryWorkerStartedSupportedOperationsItem = "repository.get_diagnostics"
)

type RepositoryWorkerStartedSupportedRepositoryKindsItem string

const (
	RepositoryWorkerStartedSupportedRepositoryKindsItemGit RepositoryWorkerStartedSupportedRepositoryKindsItem = "git"

	RepositoryWorkerStartedSupportedRepositoryKindsItemGithub RepositoryWorkerStartedSupportedRepositoryKindsItem = "github"

	RepositoryWorkerStartedSupportedRepositoryKindsItemFilesystem RepositoryWorkerStartedSupportedRepositoryKindsItem = "filesystem"

	RepositoryWorkerStartedSupportedRepositoryKindsItemArchive RepositoryWorkerStartedSupportedRepositoryKindsItem = "archive"

	RepositoryWorkerStartedSupportedRepositoryKindsItemUnknown RepositoryWorkerStartedSupportedRepositoryKindsItem = "unknown"
)

type RepositoryWorkerStartedWorkerKind string

const (
	RepositoryWorkerStartedWorkerKindLocalGit RepositoryWorkerStartedWorkerKind = "local_git"

	RepositoryWorkerStartedWorkerKindRemoteGit RepositoryWorkerStartedWorkerKind = "remote_git"

	RepositoryWorkerStartedWorkerKindIndexService RepositoryWorkerStartedWorkerKind = "index_service"

	RepositoryWorkerStartedWorkerKindMock RepositoryWorkerStartedWorkerKind = "mock"

	RepositoryWorkerStartedWorkerKindUnknown RepositoryWorkerStartedWorkerKind = "unknown"
)

type RepositoryWorkerStarted struct {
	RepositoryWorkerID       string                                                `json:"repository_worker_id" validate:"required,min=1"`
	RuntimeSessionID         string                                                `json:"runtime_session_id" validate:"required,min=1"`
	StartedAt                time.Time                                             `json:"started_at" validate:"required"`
	SupportedOperations      []RepositoryWorkerStartedSupportedOperationsItem      `json:"supported_operations" validate:"required,min=1"`
	SupportedRepositoryKinds []RepositoryWorkerStartedSupportedRepositoryKindsItem `json:"supported_repository_kinds,omitempty" validate:"omitempty,min=1"`
	WorkerKind               RepositoryWorkerStartedWorkerKind                     `json:"worker_kind" validate:"required"`
	WorkerVersion            *string                                               `json:"worker_version,omitempty" validate:"omitempty,min=1"`
}

func (value RepositoryWorkerStarted) Validate() error {
	return shared.Validate(value)
}
