// Code generated by generategomodels; DO NOT EDIT.

package repository_worker_started

import (
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type RepositoryWorkerStartedSupportedOperationsItem string

const (
	RepositoryWorkerStartedSupportedOperationsItemRepositoryOpenSession RepositoryWorkerStartedSupportedOperationsItem = "repository.open_session"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryCloseSession RepositoryWorkerStartedSupportedOperationsItem = "repository.close_session"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryPrepare RepositoryWorkerStartedSupportedOperationsItem = "repository.prepare"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryGetPreparationStatus RepositoryWorkerStartedSupportedOperationsItem = "repository.get_preparation_status"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryGetVersion RepositoryWorkerStartedSupportedOperationsItem = "repository.get_version"

	RepositoryWorkerStartedSupportedOperationsItemRepositorySearch RepositoryWorkerStartedSupportedOperationsItem = "repository.search"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryGetSource RepositoryWorkerStartedSupportedOperationsItem = "repository.get_source"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryGetContent RepositoryWorkerStartedSupportedOperationsItem = "repository.get_content"

	RepositoryWorkerStartedSupportedOperationsItemRepositoryGetDiagnostics RepositoryWorkerStartedSupportedOperationsItem = "repository.get_diagnostics"
)

type RepositoryWorkerStartedSupportedRepositoryKindsItem string

const (
	RepositoryWorkerStartedSupportedRepositoryKindsItemGit RepositoryWorkerStartedSupportedRepositoryKindsItem = "git"

	RepositoryWorkerStartedSupportedRepositoryKindsItemGithub RepositoryWorkerStartedSupportedRepositoryKindsItem = "github"

	RepositoryWorkerStartedSupportedRepositoryKindsItemFilesystem RepositoryWorkerStartedSupportedRepositoryKindsItem = "filesystem"

	RepositoryWorkerStartedSupportedRepositoryKindsItemArchive RepositoryWorkerStartedSupportedRepositoryKindsItem = "archive"

	RepositoryWorkerStartedSupportedRepositoryKindsItemUnknown RepositoryWorkerStartedSupportedRepositoryKindsItem = "unknown"
)

type RepositoryWorkerStartedWorkerKind string

const (
	RepositoryWorkerStartedWorkerKindLocalGit RepositoryWorkerStartedWorkerKind = "local_git"

	RepositoryWorkerStartedWorkerKindRemoteGit RepositoryWorkerStartedWorkerKind = "remote_git"

	RepositoryWorkerStartedWorkerKindIndexService RepositoryWorkerStartedWorkerKind = "index_service"

	RepositoryWorkerStartedWorkerKindMock RepositoryWorkerStartedWorkerKind = "mock"

	RepositoryWorkerStartedWorkerKindUnknown RepositoryWorkerStartedWorkerKind = "unknown"
)

// RepositoryWorkerStarted payload for repository.worker_started events.
type RepositoryWorkerStarted struct {
	// RepositoryWorkerID runtime-local identity for the repository worker.
	RepositoryWorkerID string `json:"repository_worker_id" validate:"required,min=1"`
	// RuntimeSessionID runtime session that started this repository worker.
	RuntimeSessionID string `json:"runtime_session_id" validate:"required,min=1"`
	// StartedAt when the repository worker started.
	StartedAt time.Time `json:"started_at" validate:"required"`
	// SupportedOperations repository protocol operations supported by this repository worker.
	SupportedOperations []RepositoryWorkerStartedSupportedOperationsItem `json:"supported_operations" validate:"required,min=1"`
	// SupportedRepositoryKinds repository kinds this worker can handle.
	SupportedRepositoryKinds []RepositoryWorkerStartedSupportedRepositoryKindsItem `json:"supported_repository_kinds,omitempty" validate:"omitempty,min=1"`
	// WorkerKind kind of repository worker.
	WorkerKind RepositoryWorkerStartedWorkerKind `json:"worker_kind" validate:"required"`
	// WorkerVersion repository worker implementation version.
	WorkerVersion *string `json:"worker_version,omitempty" validate:"omitempty,min=1"`
}

func (value RepositoryWorkerStarted) Validate() error {
	return shared.Validate(value)
}
