// Code generated by generategomodels; DO NOT EDIT.

package error_category

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ErrorCategory struct {
}

func (value ErrorCategory) Validate() error {
	return shared.Validate(value)
}
