// Code generated by generategomodels; DO NOT EDIT.

package error_category

import (
	validator "github.com/go-playground/validator/v10"
)

type ErrorCategory struct {
}

func (value ErrorCategory) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
