// Code generated by generategomodels; DO NOT EDIT.

package search_response

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type SearchResponse struct {
}

func (value SearchResponse) Validate() error {
	return shared.Validate(value)
}
