// Code generated by generategomodels; DO NOT EDIT.

package search_response

import (
	validator "github.com/go-playground/validator/v10"
)

type SearchResponse struct {
}

func (value SearchResponse) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
