// Code generated by generategomodels; DO NOT EDIT.

package error

import (
	artifact_diagnostic_log_reference "github.com/julianstephens/kiln/go/schema/artifact/diagnostic_log_reference"
	repository_diagnostic "github.com/julianstephens/kiln/go/schema/repository/diagnostic"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ErrorCategory string

const (
	ErrorCategoryProtocol ErrorCategory = "protocol"

	ErrorCategoryAuthorization ErrorCategory = "authorization"

	ErrorCategorySession ErrorCategory = "session"

	ErrorCategoryVersion ErrorCategory = "version"

	ErrorCategoryRepository ErrorCategory = "repository"

	ErrorCategoryIndexing ErrorCategory = "indexing"

	ErrorCategoryParsing ErrorCategory = "parsing"

	ErrorCategorySearch ErrorCategory = "search"

	ErrorCategoryGraph ErrorCategory = "graph"

	ErrorCategoryRepresentation ErrorCategory = "representation"

	ErrorCategoryResource ErrorCategory = "resource"

	ErrorCategoryPersistence ErrorCategory = "persistence"

	ErrorCategoryCancellation ErrorCategory = "cancellation"

	ErrorCategoryInternal ErrorCategory = "internal"
)

// Error repository-protocol error details including category, diagnostics, operation context, and related artifacts.
type Error struct {
	ArtifactReferences  []artifact_diagnostic_log_reference.DiagnosticLogReference `json:"artifact_references" validate:"required"`
	Category            ErrorCategory                                              `json:"category" validate:"required"`
	CauseErrorID        *string                                                    `json:"cause_error_id,omitempty" validate:"omitempty,min=1"`
	Code                string                                                     `json:"code" validate:"required,min=1"`
	Diagnostics         []repository_diagnostic.Diagnostic                         `json:"diagnostics" validate:"required"`
	Message             string                                                     `json:"message" validate:"required,min=1"`
	OperationID         string                                                     `json:"operation_id" validate:"required,min=1"`
	RepositorySessionID string                                                     `json:"repository_session_id" validate:"required,min=1"`
	RepositoryVersion   map[string]any                                             `json:"repository_version" validate:"required"`
	Retryable           bool                                                       `json:"retryable"`
	WorkspaceVersion    map[string]any                                             `json:"workspace_version" validate:"required"`
}

func (value Error) Validate() error {
	return shared.Validate(value)
}
