// Code generated by generategomodels; DO NOT EDIT.

package byte_range

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ByteRange struct {
	End   int `json:"end" validate:"required,gte=0"`
	Start int `json:"start" validate:"required,gte=0"`
}

func (value ByteRange) Validate() error {
	return shared.Validate(value)
}
