// Code generated by generategomodels; DO NOT EDIT.

package byte_range

import (
	validator "github.com/go-playground/validator/v10"
)

type ByteRange struct {
	End   int `json:"end" validate:"required,gte=0"`
	Start int `json:"start" validate:"required,gte=0"`
}

func (value ByteRange) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
