// Code generated by generategomodels; DO NOT EDIT.

// Package shutdown_request_payload contains generated Go models for the Kiln runtime/shutdown-request-payload schema.
package shutdown_request_payload
