// Code generated by generategomodels; DO NOT EDIT.

package runtime_session_events

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type RuntimeSessionEvents struct {
}

func (value RuntimeSessionEvents) Validate() error {
	return shared.Validate(value)
}
