// Code generated by generategomodels; DO NOT EDIT.

package runtime_session_events

import (
	validator "github.com/go-playground/validator/v10"
)

type RuntimeSessionEvents struct {
}

func (value RuntimeSessionEvents) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
