// Code generated by generategomodels; DO NOT EDIT.

// Package repository_snapshot_reference contains generated Go models for the Kiln artifact/repository-snapshot-reference schema.
package repository_snapshot_reference
