// Code generated by generategomodels; DO NOT EDIT.

package repository_snapshot_reference

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// RepositorySnapshotReference is generated from a nested JSON Schema object.
type RepositorySnapshotReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value RepositorySnapshotReference) Validate() error {
	return shared.Validate(value)
}
