// Code generated by generategomodels; DO NOT EDIT.

package repository_snapshot_reference

import (
	validator "github.com/go-playground/validator/v10"
)

type RepositorySnapshotReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value RepositorySnapshotReference) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
