// Code generated by generategomodels; DO NOT EDIT.

package source_response

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type SourceResponse struct {
}

func (value SourceResponse) Validate() error {
	return shared.Validate(value)
}
