// Code generated by generategomodels; DO NOT EDIT.

package source_response

import (
	validator "github.com/go-playground/validator/v10"
)

type SourceResponse struct {
}

func (value SourceResponse) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
