// Code generated by generategomodels; DO NOT EDIT.

// Package context_item_available contains generated Go models for the Kiln event/payload/context-item-available schema.
package context_item_available
