// Code generated by generategomodels; DO NOT EDIT.

package context_item_available

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
)

type ContextItemAvailableAvailabilityReason string

const (
	ContextItemAvailableAvailabilityReasonObserved ContextItemAvailableAvailabilityReason = "observed"

	ContextItemAvailableAvailabilityReasonRetrieved ContextItemAvailableAvailabilityReason = "retrieved"

	ContextItemAvailableAvailabilityReasonGenerated ContextItemAvailableAvailabilityReason = "generated"

	ContextItemAvailableAvailabilityReasonPinned ContextItemAvailableAvailabilityReason = "pinned"

	ContextItemAvailableAvailabilityReasonRestored ContextItemAvailableAvailabilityReason = "restored"

	ContextItemAvailableAvailabilityReasonManual ContextItemAvailableAvailabilityReason = "manual"
)

type ContextItemAvailableItemKind string

const (
	ContextItemAvailableItemKindSystemInstruction ContextItemAvailableItemKind = "system_instruction"

	ContextItemAvailableItemKindUserMessage ContextItemAvailableItemKind = "user_message"

	ContextItemAvailableItemKindAssistantMessage ContextItemAvailableItemKind = "assistant_message"

	ContextItemAvailableItemKindToolResult ContextItemAvailableItemKind = "tool_result"

	ContextItemAvailableItemKindRepositorySource ContextItemAvailableItemKind = "repository_source"

	ContextItemAvailableItemKindRepositorySearchResult ContextItemAvailableItemKind = "repository_search_result"

	ContextItemAvailableItemKindArtifact ContextItemAvailableItemKind = "artifact"

	ContextItemAvailableItemKindSummary ContextItemAvailableItemKind = "summary"

	ContextItemAvailableItemKindMemory ContextItemAvailableItemKind = "memory"

	ContextItemAvailableItemKindValidationResult ContextItemAvailableItemKind = "validation_result"

	ContextItemAvailableItemKindDiagnostic ContextItemAvailableItemKind = "diagnostic"
)

type ContextItemAvailablePriority string

const (
	ContextItemAvailablePriorityLow ContextItemAvailablePriority = "low"

	ContextItemAvailablePriorityNormal ContextItemAvailablePriority = "normal"

	ContextItemAvailablePriorityHigh ContextItemAvailablePriority = "high"

	ContextItemAvailablePriorityRequired ContextItemAvailablePriority = "required"
)

type ContextItemAvailable struct {
	AvailabilityReason ContextItemAvailableAvailabilityReason `json:"availability_reason" validate:"required"`
	ContextID          string                                 `json:"context_id" validate:"required,min=1"`
	EstimatedTokens    int                                    `json:"estimated_tokens" validate:"required,gte=0"`
	ItemID             string                                 `json:"item_id" validate:"required,min=1"`
	ItemKind           ContextItemAvailableItemKind           `json:"item_kind" validate:"required"`
	Metadata           map[string]any                         `json:"metadata,omitempty" validate:"omitempty"`
	Pinned             *bool                                  `json:"pinned,omitempty" validate:"omitempty"`
	Priority           *ContextItemAvailablePriority          `json:"priority,omitempty" validate:"omitempty"`
	SourceReference    *artifact_reference.Reference          `json:"source_reference,omitempty" validate:"omitempty"`
}

func (value ContextItemAvailable) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
