// Code generated by generategomodels; DO NOT EDIT.

package error

import (
	validator "github.com/go-playground/validator/v10"
	artifact_diagnostic_log_reference "github.com/julianstephens/kiln/go/schema/artifact/diagnostic_log_reference"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
)

type ErrorCategory string

const (
	ErrorCategoryInvalidRequest ErrorCategory = "invalid_request"

	ErrorCategoryAuthentication ErrorCategory = "authentication"

	ErrorCategoryAuthorization ErrorCategory = "authorization"

	ErrorCategoryRateLimited ErrorCategory = "rate_limited"

	ErrorCategoryQuotaExceeded ErrorCategory = "quota_exceeded"

	ErrorCategoryTimeout ErrorCategory = "timeout"

	ErrorCategoryProviderUnavailable ErrorCategory = "provider_unavailable"

	ErrorCategoryModelUnavailable ErrorCategory = "model_unavailable"

	ErrorCategoryContentFilter ErrorCategory = "content_filter"

	ErrorCategoryEgressDenied ErrorCategory = "egress_denied"

	ErrorCategoryContextLengthExceeded ErrorCategory = "context_length_exceeded"

	ErrorCategoryAdapterError ErrorCategory = "adapter_error"

	ErrorCategoryCanceled ErrorCategory = "canceled"

	ErrorCategoryUnknown ErrorCategory = "unknown"
)

type Error struct {
	Category                         ErrorCategory                                             `json:"category" validate:"required"`
	Code                             string                                                    `json:"code" validate:"required,min=1"`
	DiagnosticArtifactReference      *artifact_diagnostic_log_reference.DiagnosticLogReference `json:"diagnostic_artifact_reference,omitempty" validate:"omitempty"`
	ErrorID                          string                                                    `json:"error_id" validate:"required,min=1"`
	Message                          string                                                    `json:"message" validate:"required,min=1"`
	ModelID                          *string                                                   `json:"model_id,omitempty" validate:"omitempty,min=1"`
	ModelInvocationID                *string                                                   `json:"model_invocation_id,omitempty" validate:"omitempty,min=1"`
	PartialResponseArtifactReference *artifact_reference.Reference                             `json:"partial_response_artifact_reference,omitempty" validate:"omitempty"`
	ProviderCode                     *string                                                   `json:"provider_code,omitempty" validate:"omitempty,min=1"`
	ProviderID                       *string                                                   `json:"provider_id,omitempty" validate:"omitempty,min=1"`
	RetryAfterSeconds                *int                                                      `json:"retry_after_seconds,omitempty" validate:"omitempty,gte=0"`
	Retryable                        bool                                                      `json:"retryable" validate:"required"`
}

func (value Error) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
