// Code generated by generategomodels; DO NOT EDIT.

package protocol_request

import (
	validator "github.com/go-playground/validator/v10"
)

type ProtocolRequest struct {
}

func (value ProtocolRequest) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
