// Code generated by generategomodels; DO NOT EDIT.

package item

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	repository_candidate "github.com/julianstephens/kiln/go/schema/repository/candidate"
	repository_source "github.com/julianstephens/kiln/go/schema/repository/source"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type ItemAdmissionReason string

const (
	ItemAdmissionReasonPinned ItemAdmissionReason = "pinned"

	ItemAdmissionReasonRecent ItemAdmissionReason = "recent"

	ItemAdmissionReasonRelevant ItemAdmissionReason = "relevant"

	ItemAdmissionReasonRequired ItemAdmissionReason = "required"

	ItemAdmissionReasonDependency ItemAdmissionReason = "dependency"

	ItemAdmissionReasonManual ItemAdmissionReason = "manual"

	ItemAdmissionReasonPlanApplied ItemAdmissionReason = "plan_applied"
)

type ItemEvictionReason string

const (
	ItemEvictionReasonTokenBudget ItemEvictionReason = "token_budget"

	ItemEvictionReasonStale ItemEvictionReason = "stale"

	ItemEvictionReasonSuperseded ItemEvictionReason = "superseded"

	ItemEvictionReasonLowRelevance ItemEvictionReason = "low_relevance"

	ItemEvictionReasonManual ItemEvictionReason = "manual"

	ItemEvictionReasonPlanApplied ItemEvictionReason = "plan_applied"

	ItemEvictionReasonContextReset ItemEvictionReason = "context_reset"
)

type ItemItemKind string

const (
	ItemItemKindSystemInstruction ItemItemKind = "system_instruction"

	ItemItemKindDeveloperInstruction ItemItemKind = "developer_instruction"

	ItemItemKindUserMessage ItemItemKind = "user_message"

	ItemItemKindAssistantMessage ItemItemKind = "assistant_message"

	ItemItemKindToolRequest ItemItemKind = "tool_request"

	ItemItemKindToolResult ItemItemKind = "tool_result"

	ItemItemKindRepositorySource ItemItemKind = "repository_source"

	ItemItemKindRepositorySearchResult ItemItemKind = "repository_search_result"

	ItemItemKindArtifact ItemItemKind = "artifact"

	ItemItemKindSummary ItemItemKind = "summary"

	ItemItemKindMemory ItemItemKind = "memory"

	ItemItemKindValidationResult ItemItemKind = "validation_result"

	ItemItemKindDiagnostic ItemItemKind = "diagnostic"

	ItemItemKindRunState ItemItemKind = "run_state"

	ItemItemKindOther ItemItemKind = "other"
)

type ItemItemStatus string

const (
	ItemItemStatusAvailable ItemItemStatus = "available"

	ItemItemStatusActive ItemItemStatus = "active"

	ItemItemStatusEvicted ItemItemStatus = "evicted"

	ItemItemStatusStale ItemItemStatus = "stale"

	ItemItemStatusInvalidated ItemItemStatus = "invalidated"
)

type ItemPriority string

const (
	ItemPriorityLow ItemPriority = "low"

	ItemPriorityNormal ItemPriority = "normal"

	ItemPriorityHigh ItemPriority = "high"

	ItemPriorityRequired ItemPriority = "required"
)

// Item a durable item of context that may be made available, admitted into active context, rendered, evicted, or marked stale.
type Item struct {
	// ActiveOrder order of this item when admitted into active context.
	ActiveOrder *int `json:"active_order,omitempty" validate:"omitempty,gte=0"`
	// AdmissionReason reason this item was admitted into active context.
	AdmissionReason *ItemAdmissionReason `json:"admission_reason,omitempty" validate:"omitempty"`
	// AdmittedAt when this item was admitted into active context.
	AdmittedAt *time.Time `json:"admitted_at,omitempty" validate:"omitempty"`
	// ContentReference reference to the item's underlying content.
	ContentReference ItemContentReference `json:"content_reference" validate:"required"`
	// ContextID context ledger this item belongs to.
	ContextID string `json:"context_id" validate:"required,min=1"`
	// CreatedAt when this context item was created.
	CreatedAt time.Time `json:"created_at" validate:"required"`
	// EstimatedTokens estimated token cost of admitting this item into context.
	EstimatedTokens int `json:"estimated_tokens" validate:"required,gte=0"`
	// EvictedAt when this item was evicted from active context.
	EvictedAt *time.Time `json:"evicted_at,omitempty" validate:"omitempty"`
	// EvictionReason reason this item was evicted from active context.
	EvictionReason *ItemEvictionReason `json:"eviction_reason,omitempty" validate:"omitempty"`
	// InvalidatedAt when this item was invalidated.
	InvalidatedAt *time.Time `json:"invalidated_at,omitempty" validate:"omitempty"`
	// ItemID stable identity for this context item.
	ItemID string `json:"item_id" validate:"required,min=1"`
	// ItemKind kind of content represented by this context item.
	ItemKind ItemItemKind `json:"item_kind" validate:"required"`
	// ItemStatus current lifecycle status of the context item.
	ItemStatus ItemItemStatus `json:"item_status" validate:"required"`
	// Metadata small non-sensitive item metadata.
	Metadata map[string]any `json:"metadata,omitempty" validate:"omitempty"`
	// Pinned whether this item should be treated as pinned by context planning.
	Pinned *bool `json:"pinned,omitempty" validate:"omitempty"`
	// Priority planner-visible priority for this context item.
	Priority *ItemPriority `json:"priority,omitempty" validate:"omitempty"`
	// SourceEventID event that made this item available, when applicable.
	SourceEventID *string `json:"source_event_id,omitempty" validate:"omitempty,min=1"`
	// SourceOperationID operation that produced or retrieved this item, when applicable.
	SourceOperationID *string `json:"source_operation_id,omitempty" validate:"omitempty,min=1"`
	// StaleAt when this item became stale.
	StaleAt *time.Time `json:"stale_at,omitempty" validate:"omitempty"`
}

type ItemContentReferenceReferenceKind string

const (
	ItemContentReferenceReferenceKindInline ItemContentReferenceReferenceKind = "inline"

	ItemContentReferenceReferenceKindArtifact ItemContentReferenceReferenceKind = "artifact"

	ItemContentReferenceReferenceKindRepositorySource ItemContentReferenceReferenceKind = "repository_source"

	ItemContentReferenceReferenceKindRepositoryCandidate ItemContentReferenceReferenceKind = "repository_candidate"

	ItemContentReferenceReferenceKindMessage ItemContentReferenceReferenceKind = "message"

	ItemContentReferenceReferenceKindState ItemContentReferenceReferenceKind = "state"

	ItemContentReferenceReferenceKindExternal ItemContentReferenceReferenceKind = "external"
)

// ItemContentReference reference to the item's underlying content.
type ItemContentReference struct {
	// ArtifactReference artifact containing the item content.
	ArtifactReference *artifact_reference.Reference `json:"artifact_reference,omitempty" validate:"omitempty"`
	// ExternalReference external reference represented by this item.
	ExternalReference *string `json:"external_reference,omitempty" validate:"omitempty,min=1"`
	// InlineContent inline context content for small items.
	InlineContent *string `json:"inline_content,omitempty" validate:"omitempty,min=1"`
	// MessageID message identity represented by this item.
	MessageID *string `json:"message_id,omitempty" validate:"omitempty,min=1"`
	// ReferenceKind kind of content reference used by the item.
	ReferenceKind ItemContentReferenceReferenceKind `json:"reference_kind" validate:"required"`
	// RepositoryCandidate repository candidate represented by this item.
	RepositoryCandidate *repository_candidate.Candidate `json:"repository_candidate,omitempty" validate:"omitempty"`
	// RepositorySource repository source location represented by this item.
	RepositorySource *repository_source.Source `json:"repository_source,omitempty" validate:"omitempty"`
	// StateReference opaque state reference represented by this item.
	StateReference *string `json:"state_reference,omitempty" validate:"omitempty,min=1"`
}

func (value Item) Validate() error {
	return shared.Validate(value)
}
