// Code generated by generategomodels; DO NOT EDIT.

package item

import (
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type ItemAdmissionReason string

const (
	ItemAdmissionReasonPinned ItemAdmissionReason = "pinned"

	ItemAdmissionReasonRecent ItemAdmissionReason = "recent"

	ItemAdmissionReasonRelevant ItemAdmissionReason = "relevant"

	ItemAdmissionReasonRequired ItemAdmissionReason = "required"

	ItemAdmissionReasonDependency ItemAdmissionReason = "dependency"

	ItemAdmissionReasonManual ItemAdmissionReason = "manual"

	ItemAdmissionReasonPlanApplied ItemAdmissionReason = "plan_applied"
)

type ItemEvictionReason string

const (
	ItemEvictionReasonTokenBudget ItemEvictionReason = "token_budget"

	ItemEvictionReasonStale ItemEvictionReason = "stale"

	ItemEvictionReasonSuperseded ItemEvictionReason = "superseded"

	ItemEvictionReasonLowRelevance ItemEvictionReason = "low_relevance"

	ItemEvictionReasonManual ItemEvictionReason = "manual"

	ItemEvictionReasonPlanApplied ItemEvictionReason = "plan_applied"

	ItemEvictionReasonContextReset ItemEvictionReason = "context_reset"
)

type ItemItemKind string

const (
	ItemItemKindSystemInstruction ItemItemKind = "system_instruction"

	ItemItemKindDeveloperInstruction ItemItemKind = "developer_instruction"

	ItemItemKindUserMessage ItemItemKind = "user_message"

	ItemItemKindAssistantMessage ItemItemKind = "assistant_message"

	ItemItemKindToolRequest ItemItemKind = "tool_request"

	ItemItemKindToolResult ItemItemKind = "tool_result"

	ItemItemKindRepositorySource ItemItemKind = "repository_source"

	ItemItemKindRepositorySearchResult ItemItemKind = "repository_search_result"

	ItemItemKindArtifact ItemItemKind = "artifact"

	ItemItemKindSummary ItemItemKind = "summary"

	ItemItemKindMemory ItemItemKind = "memory"

	ItemItemKindValidationResult ItemItemKind = "validation_result"

	ItemItemKindDiagnostic ItemItemKind = "diagnostic"

	ItemItemKindRunState ItemItemKind = "run_state"

	ItemItemKindOther ItemItemKind = "other"
)

type ItemItemStatus string

const (
	ItemItemStatusAvailable ItemItemStatus = "available"

	ItemItemStatusActive ItemItemStatus = "active"

	ItemItemStatusEvicted ItemItemStatus = "evicted"

	ItemItemStatusStale ItemItemStatus = "stale"

	ItemItemStatusInvalidated ItemItemStatus = "invalidated"
)

type ItemPriority string

const (
	ItemPriorityLow ItemPriority = "low"

	ItemPriorityNormal ItemPriority = "normal"

	ItemPriorityHigh ItemPriority = "high"

	ItemPriorityRequired ItemPriority = "required"
)

type Item struct {
	ActiveOrder       *int                 `json:"active_order,omitempty" validate:"omitempty,gte=0"`
	AdmissionReason   *ItemAdmissionReason `json:"admission_reason,omitempty" validate:"omitempty"`
	AdmittedAt        *time.Time           `json:"admitted_at,omitempty" validate:"omitempty"`
	ContentReference  map[string]any       `json:"content_reference" validate:"required"`
	ContextID         string               `json:"context_id" validate:"required,min=1"`
	CreatedAt         time.Time            `json:"created_at" validate:"required"`
	EstimatedTokens   int                  `json:"estimated_tokens" validate:"required,gte=0"`
	EvictedAt         *time.Time           `json:"evicted_at,omitempty" validate:"omitempty"`
	EvictionReason    *ItemEvictionReason  `json:"eviction_reason,omitempty" validate:"omitempty"`
	InvalidatedAt     *time.Time           `json:"invalidated_at,omitempty" validate:"omitempty"`
	ItemID            string               `json:"item_id" validate:"required,min=1"`
	ItemKind          ItemItemKind         `json:"item_kind" validate:"required"`
	ItemStatus        ItemItemStatus       `json:"item_status" validate:"required"`
	Metadata          map[string]any       `json:"metadata,omitempty" validate:"omitempty"`
	Pinned            *bool                `json:"pinned,omitempty" validate:"omitempty"`
	Priority          *ItemPriority        `json:"priority,omitempty" validate:"omitempty"`
	SourceEventID     *string              `json:"source_event_id,omitempty" validate:"omitempty,min=1"`
	SourceOperationID *string              `json:"source_operation_id,omitempty" validate:"omitempty,min=1"`
	StaleAt           *time.Time           `json:"stale_at,omitempty" validate:"omitempty"`
}

func (value Item) Validate() error {
	return shared.Validate(value)
}
