// Code generated by generategomodels; DO NOT EDIT.

package envelope

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type Envelope struct {
	ArtifactReferences  []artifact_reference.Reference `json:"artifact_references,omitempty" validate:"omitempty,min=1"`
	CausationID         *string                        `json:"causation_id,omitempty" validate:"omitempty,min=1"`
	CorrelationID       *string                        `json:"correlation_id,omitempty" validate:"omitempty,min=1"`
	EventID             string                         `json:"event_id" validate:"required,min=1"`
	EventSchemaVersion  string                         `json:"event_schema_version" validate:"required,min=1"`
	EventType           string                         `json:"event_type" validate:"required"`
	OccurredAt          time.Time                      `json:"occurred_at" validate:"required"`
	OperationID         *string                        `json:"operation_id,omitempty" validate:"omitempty,min=1"`
	Payload             map[string]any                 `json:"payload" validate:"required"`
	Producer            string                         `json:"producer" validate:"required,min=1"`
	RepositorySessionID *string                        `json:"repository_session_id,omitempty" validate:"omitempty,min=1"`
	RunID               *string                        `json:"run_id,omitempty" validate:"omitempty,min=1"`
	Sequence            int                            `json:"sequence" validate:"required,gte=1"`
	TurnID              *string                        `json:"turn_id,omitempty" validate:"omitempty,min=1"`
}

func (value Envelope) Validate() error {
	return shared.Validate(value)
}
