// Code generated by generategomodels; DO NOT EDIT.

package state

import (
	validator "github.com/go-playground/validator/v10"
	budget_state "github.com/julianstephens/kiln/go/schema/budget/state"
	context_state "github.com/julianstephens/kiln/go/schema/context/state"
	repository_identifier "github.com/julianstephens/kiln/go/schema/repository/identifier"
	run_lifecycle_state "github.com/julianstephens/kiln/go/schema/run/lifecycle_state"
	run_task_state "github.com/julianstephens/kiln/go/schema/run/task_state"
	run_terminal_result_reference "github.com/julianstephens/kiln/go/schema/run/terminal_result_reference"
)

type State struct {
	ActiveCapabilityGrantReferences []string                                               `json:"active_capability_grant_references" validate:"required,min=1"`
	ActiveRepository                *repository_identifier.IDentifier                      `json:"active_repository,omitempty" validate:"omitempty"`
	BudgetSummary                   budget_state.State                                     `json:"budget_summary" validate:"required"`
	CurrentContextLedgerSummary     context_state.State                                    `json:"current_context_ledger_summary" validate:"required"`
	CurrentTaskState                run_task_state.TaskState                               `json:"current_task_state" validate:"required"`
	CurrentTurn                     int                                                    `json:"current_turn" validate:"required,gte=0"`
	LastCommittedEventSequence      *int                                                   `json:"last_committed_event_sequence,omitempty" validate:"omitempty,gte=0"`
	LifecycleState                  run_lifecycle_state.LifecycleState                     `json:"lifecycle_state" validate:"required"`
	PendingOperationReference       map[string]any                                         `json:"pending_operation_reference,omitempty" validate:"omitempty"`
	RecoveryMetadata                map[string]any                                         `json:"recovery_metadata,omitempty" validate:"omitempty"`
	TerminalResultReference         *run_terminal_result_reference.TerminalResultReference `json:"terminal_result_reference,omitempty" validate:"omitempty"`
}

func (value State) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
