// Code generated by generategomodels; DO NOT EDIT.

package version

import (
	validator "github.com/go-playground/validator/v10"
	"time"
)

type VersionPreparationStatus string

const (
	VersionPreparationStatusPending VersionPreparationStatus = "pending"

	VersionPreparationStatusPreparing VersionPreparationStatus = "preparing"

	VersionPreparationStatusPrepared VersionPreparationStatus = "prepared"

	VersionPreparationStatusFailed VersionPreparationStatus = "failed"
)

type Version struct {
	ContentDigest              string                   `json:"content_digest" validate:"required,min=1"`
	CreatedAt                  time.Time                `json:"created_at" validate:"required"`
	CreationReason             string                   `json:"creation_reason" validate:"required,min=1"`
	IndexCompatibilityMetadata map[string]any           `json:"index_compatibility_metadata" validate:"required"`
	ParentRepositoryVersionID  *string                  `json:"parent_repository_version_id,omitempty" validate:"omitempty,min=1"`
	PreparationStatus          VersionPreparationStatus `json:"preparation_status" validate:"required"`
	RepositoryID               string                   `json:"repository_id" validate:"required,min=1"`
	SnapshotID                 *string                  `json:"snapshot_id,omitempty" validate:"omitempty,min=1"`
	SourceRevision             *string                  `json:"source_revision,omitempty" validate:"omitempty,min=1"`
	VersionID                  string                   `json:"version_id" validate:"required,min=1"`
}

func (value Version) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
