// Code generated by generategomodels; DO NOT EDIT.

package usage

import (
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type UsageMeasurement string

const (
	UsageMeasurementEstimated UsageMeasurement = "estimated"

	UsageMeasurementActual UsageMeasurement = "actual"

	UsageMeasurementReconciled UsageMeasurement = "reconciled"
)

type UsageUsageScope string

const (
	UsageUsageScopeRun UsageUsageScope = "run"

	UsageUsageScopeTurn UsageUsageScope = "turn"

	UsageUsageScopeOperation UsageUsageScope = "operation"

	UsageUsageScopeComponent UsageUsageScope = "component"
)

// Usage is generated from a nested JSON Schema object.
type Usage struct {
	ArtifactSizeBytes      *int              `json:"artifact_size_bytes,omitempty" validate:"omitempty,gte=0"`
	CommandOutputSizeBytes *int              `json:"command_output_size_bytes,omitempty" validate:"omitempty,gte=0"`
	CommandTimeSeconds     *float64          `json:"command_time_seconds,omitempty" validate:"omitempty,gte=0"`
	Component              *string           `json:"component,omitempty" validate:"omitempty,min=1"`
	ElapsedWallTimeSeconds *float64          `json:"elapsed_wall_time_seconds,omitempty" validate:"omitempty,gte=0"`
	Measurement            *UsageMeasurement `json:"measurement,omitempty" validate:"omitempty"`
	ModelCalls             *int              `json:"model_calls,omitempty" validate:"omitempty,gte=0"`
	ModelInputTokens       *int              `json:"model_input_tokens,omitempty" validate:"omitempty,gte=0"`
	ModelOutputTokens      *int              `json:"model_output_tokens,omitempty" validate:"omitempty,gte=0"`
	MonetaryCostUsd        *float64          `json:"monetary_cost_usd,omitempty" validate:"omitempty,gte=0"`
	OperationID            *string           `json:"operation_id,omitempty" validate:"omitempty,min=1"`
	RecordedAt             time.Time         `json:"recorded_at" validate:"required"`
	RepeatedTokenCostUsd   *float64          `json:"repeated_token_cost_usd,omitempty" validate:"omitempty,gte=0"`
	RepositoryRequests     *int              `json:"repository_requests,omitempty" validate:"omitempty,gte=0"`
	RunID                  *string           `json:"run_id,omitempty" validate:"omitempty,min=1"`
	Source                 *string           `json:"source,omitempty" validate:"omitempty,min=1"`
	ToolCalls              *int              `json:"tool_calls,omitempty" validate:"omitempty,gte=0"`
	TurnID                 *string           `json:"turn_id,omitempty" validate:"omitempty,min=1"`
	UsageScope             UsageUsageScope   `json:"usage_scope" validate:"required"`
}

func (value Usage) Validate() error {
	return shared.Validate(value)
}
