// Code generated by generategomodels; DO NOT EDIT.

package error

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	run_error_category "github.com/julianstephens/kiln/go/schema/run/error_category"
	"time"
)

type ErrorCode string

const (
	ErrorCodeValidationFailed ErrorCode = "validation_failed"

	ErrorCodeValidationError ErrorCode = "validation_error"

	ErrorCodeCapabilityDenied ErrorCode = "capability_denied"

	ErrorCodeCapabilityUnavailable ErrorCode = "capability_unavailable"

	ErrorCodeRepositoryUnavailable ErrorCode = "repository_unavailable"

	ErrorCodeRepositoryDirty ErrorCode = "repository_dirty"

	ErrorCodeRepositoryPreparationFailed ErrorCode = "repository_preparation_failed"

	ErrorCodeRepositorySessionInvalid ErrorCode = "repository_session_invalid"

	ErrorCodeToolFailed ErrorCode = "tool_failed"

	ErrorCodeToolTimedOut ErrorCode = "tool_timed_out"

	ErrorCodeToolResultInvalid ErrorCode = "tool_result_invalid"

	ErrorCodeExternalOperationFailed ErrorCode = "external_operation_failed"

	ErrorCodeExternalOperationTimedOut ErrorCode = "external_operation_timed_out"

	ErrorCodeExternalOperationResultInvalid ErrorCode = "external_operation_result_invalid"

	ErrorCodeOutputProductionFailed ErrorCode = "output_production_failed"

	ErrorCodeArtifactWriteFailed ErrorCode = "artifact_write_failed"

	ErrorCodeAnswerAssemblyFailed ErrorCode = "answer_assembly_failed"

	ErrorCodePatchGenerationFailed ErrorCode = "patch_generation_failed"

	ErrorCodeRuntimeInterrupted ErrorCode = "runtime_interrupted"

	ErrorCodeWorkerInterrupted ErrorCode = "worker_interrupted"

	ErrorCodeShutdownInterrupted ErrorCode = "shutdown_interrupted"

	ErrorCodeLeaseLost ErrorCode = "lease_lost"

	ErrorCodeInternalError ErrorCode = "internal_error"

	ErrorCodeInvariantViolation ErrorCode = "invariant_violation"

	ErrorCodePersistenceFailed ErrorCode = "persistence_failed"
)

type ErrorLifecycleState string

const (
	ErrorLifecycleStateCreated ErrorLifecycleState = "created"

	ErrorLifecycleStateInitializing ErrorLifecycleState = "initializing"

	ErrorLifecycleStatePreparingRepository ErrorLifecycleState = "preparing_repository"

	ErrorLifecycleStateRunning ErrorLifecycleState = "running"

	ErrorLifecycleStateProducingOutput ErrorLifecycleState = "producing_output"

	ErrorLifecycleStateValidating ErrorLifecycleState = "validating"

	ErrorLifecycleStateCompleted ErrorLifecycleState = "completed"

	ErrorLifecycleStateFailed ErrorLifecycleState = "failed"

	ErrorLifecycleStateCanceled ErrorLifecycleState = "canceled"

	ErrorLifecycleStateExhausted ErrorLifecycleState = "exhausted"
)

type ErrorSeverity string

const (
	ErrorSeverityWarning ErrorSeverity = "warning"

	ErrorSeverityError ErrorSeverity = "error"

	ErrorSeverityFatal ErrorSeverity = "fatal"
)

type Error struct {
	ArtifactReferences []artifact_reference.Reference   `json:"artifact_references,omitempty" validate:"omitempty"`
	Category           run_error_category.ErrorCategory `json:"category" validate:"required"`
	Cause              map[string]any                   `json:"cause,omitempty" validate:"omitempty"`
	Code               ErrorCode                        `json:"code" validate:"required"`
	Details            map[string]any                   `json:"details,omitempty" validate:"omitempty"`
	ErrorID            string                           `json:"error_id" validate:"required,min=1"`
	LifecycleState     *ErrorLifecycleState             `json:"lifecycle_state,omitempty" validate:"omitempty"`
	Message            string                           `json:"message" validate:"required,min=1"`
	OccurredAt         time.Time                        `json:"occurred_at" validate:"required"`
	OperationReference map[string]any                   `json:"operation_reference,omitempty" validate:"omitempty"`
	Retryable          *bool                            `json:"retryable,omitempty" validate:"omitempty"`
	RunID              string                           `json:"run_id" validate:"required,min=1"`
	Severity           *ErrorSeverity                   `json:"severity,omitempty" validate:"omitempty"`
	Source             *string                          `json:"source,omitempty" validate:"omitempty,min=1"`
}

func (value Error) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
