// Code generated by generategomodels; DO NOT EDIT.

package error

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	run_error_category "github.com/julianstephens/kiln/go/schema/run/error_category"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type ErrorCode string

const (
	ErrorCodeValidationFailed ErrorCode = "validation_failed"

	ErrorCodeValidationError ErrorCode = "validation_error"

	ErrorCodeCapabilityDenied ErrorCode = "capability_denied"

	ErrorCodeCapabilityUnavailable ErrorCode = "capability_unavailable"

	ErrorCodeRepositoryUnavailable ErrorCode = "repository_unavailable"

	ErrorCodeRepositoryDirty ErrorCode = "repository_dirty"

	ErrorCodeRepositoryPreparationFailed ErrorCode = "repository_preparation_failed"

	ErrorCodeRepositorySessionInvalid ErrorCode = "repository_session_invalid"

	ErrorCodeToolFailed ErrorCode = "tool_failed"

	ErrorCodeToolTimedOut ErrorCode = "tool_timed_out"

	ErrorCodeToolResultInvalid ErrorCode = "tool_result_invalid"

	ErrorCodeExternalOperationFailed ErrorCode = "external_operation_failed"

	ErrorCodeExternalOperationTimedOut ErrorCode = "external_operation_timed_out"

	ErrorCodeExternalOperationResultInvalid ErrorCode = "external_operation_result_invalid"

	ErrorCodeOutputProductionFailed ErrorCode = "output_production_failed"

	ErrorCodeArtifactWriteFailed ErrorCode = "artifact_write_failed"

	ErrorCodeAnswerAssemblyFailed ErrorCode = "answer_assembly_failed"

	ErrorCodePatchGenerationFailed ErrorCode = "patch_generation_failed"

	ErrorCodeRuntimeInterrupted ErrorCode = "runtime_interrupted"

	ErrorCodeWorkerInterrupted ErrorCode = "worker_interrupted"

	ErrorCodeShutdownInterrupted ErrorCode = "shutdown_interrupted"

	ErrorCodeLeaseLost ErrorCode = "lease_lost"

	ErrorCodeInternalError ErrorCode = "internal_error"

	ErrorCodeInvariantViolation ErrorCode = "invariant_violation"

	ErrorCodePersistenceFailed ErrorCode = "persistence_failed"
)

type ErrorLifecycleState string

const (
	ErrorLifecycleStateCreated ErrorLifecycleState = "created"

	ErrorLifecycleStateInitializing ErrorLifecycleState = "initializing"

	ErrorLifecycleStatePreparingRepository ErrorLifecycleState = "preparing_repository"

	ErrorLifecycleStateRunning ErrorLifecycleState = "running"

	ErrorLifecycleStateProducingOutput ErrorLifecycleState = "producing_output"

	ErrorLifecycleStateValidating ErrorLifecycleState = "validating"

	ErrorLifecycleStateCompleted ErrorLifecycleState = "completed"

	ErrorLifecycleStateFailed ErrorLifecycleState = "failed"

	ErrorLifecycleStateCanceled ErrorLifecycleState = "canceled"

	ErrorLifecycleStateExhausted ErrorLifecycleState = "exhausted"
)

type ErrorSeverity string

const (
	ErrorSeverityWarning ErrorSeverity = "warning"

	ErrorSeverityError ErrorSeverity = "error"

	ErrorSeverityFatal ErrorSeverity = "fatal"
)

// Error structured error record associated with a failed run or failed run operation.
type Error struct {
	// ArtifactReferences artifacts containing supporting diagnostics, logs, reports, or partial outputs.
	ArtifactReferences []artifact_reference.Reference `json:"artifact_references,omitempty" validate:"omitempty"`
	// Category broad class of run error.
	Category run_error_category.ErrorCategory `json:"category" validate:"required"`
	// Cause optional nested causal error reference or summary.
	Cause *ErrorCause `json:"cause,omitempty" validate:"omitempty"`
	// Code specific machine-readable run error code.
	Code ErrorCode `json:"code" validate:"required"`
	// Details optional structured diagnostic details. Intended for machine-readable context, not arbitrary logs.
	Details map[string]any `json:"details,omitempty" validate:"omitempty"`
	// ErrorID stable identifier for this error record.
	ErrorID string `json:"error_id" validate:"required,min=1"`
	// LifecycleState run lifecycle state in which the error occurred.
	LifecycleState *ErrorLifecycleState `json:"lifecycle_state,omitempty" validate:"omitempty"`
	// Message human-readable explanation of the error.
	Message string `json:"message" validate:"required,min=1"`
	// OccurredAt when the error occurred.
	OccurredAt time.Time `json:"occurred_at" validate:"required"`
	// OperationReference optional reference to the operation that produced the error.
	OperationReference *ErrorOperationReference `json:"operation_reference,omitempty" validate:"omitempty"`
	// Retryable whether retry may be attempted by policy.
	Retryable *bool `json:"retryable,omitempty" validate:"omitempty"`
	// RunID identifier of the run associated with this error.
	RunID string `json:"run_id" validate:"required,min=1"`
	// Severity severity of the error.
	Severity *ErrorSeverity `json:"severity,omitempty" validate:"omitempty"`
	// Source component or subsystem that reported the error.
	Source *string `json:"source,omitempty" validate:"omitempty,min=1"`
}

// ErrorCause optional nested causal error reference or summary.
type ErrorCause struct {
	Code    *string `json:"code,omitempty" validate:"omitempty,min=1"`
	ErrorID *string `json:"error_id,omitempty" validate:"omitempty,min=1"`
	Message *string `json:"message,omitempty" validate:"omitempty,min=1"`
}

type ErrorOperationReferenceKind string

const (
	ErrorOperationReferenceKindRepositoryPreparation ErrorOperationReferenceKind = "repository_preparation"

	ErrorOperationReferenceKindRepositoryQuery ErrorOperationReferenceKind = "repository_query"

	ErrorOperationReferenceKindContextPlan ErrorOperationReferenceKind = "context_plan"

	ErrorOperationReferenceKindModelInvocation ErrorOperationReferenceKind = "model_invocation"

	ErrorOperationReferenceKindToolCall ErrorOperationReferenceKind = "tool_call"

	ErrorOperationReferenceKindExternalJob ErrorOperationReferenceKind = "external_job"

	ErrorOperationReferenceKindOutputProduction ErrorOperationReferenceKind = "output_production"

	ErrorOperationReferenceKindValidation ErrorOperationReferenceKind = "validation"

	ErrorOperationReferenceKindRecovery ErrorOperationReferenceKind = "recovery"
)

// ErrorOperationReference optional reference to the operation that produced the error.
type ErrorOperationReference struct {
	CorrelationID *string                     `json:"correlation_id,omitempty" validate:"omitempty,min=1"`
	ID            string                      `json:"id" validate:"required,min=1"`
	Kind          ErrorOperationReferenceKind `json:"kind" validate:"required"`
}

func (value Error) Validate() error {
	return shared.Validate(value)
}
