// Code generated by generategomodels; DO NOT EDIT.

// Package model_invocation_completed contains generated Go models for the Kiln event/payload/model-invocation-completed schema.
package model_invocation_completed
