// Code generated by generategomodels; DO NOT EDIT.

package model_invocation_completed

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type ModelInvocationCompletedFinishReason string

const (
	ModelInvocationCompletedFinishReasonStop ModelInvocationCompletedFinishReason = "stop"

	ModelInvocationCompletedFinishReasonLength ModelInvocationCompletedFinishReason = "length"

	ModelInvocationCompletedFinishReasonToolCall ModelInvocationCompletedFinishReason = "tool_call"

	ModelInvocationCompletedFinishReasonContentFilter ModelInvocationCompletedFinishReason = "content_filter"

	ModelInvocationCompletedFinishReasonError ModelInvocationCompletedFinishReason = "error"

	ModelInvocationCompletedFinishReasonUnknown ModelInvocationCompletedFinishReason = "unknown"
)

type ModelInvocationCompleted struct {
	BudgetUsage               *budget_usage.Usage                  `json:"budget_usage,omitempty" validate:"omitempty"`
	CompletedAt               time.Time                            `json:"completed_at" validate:"required"`
	FinishReason              ModelInvocationCompletedFinishReason `json:"finish_reason" validate:"required"`
	LatencyMs                 *int                                 `json:"latency_ms,omitempty" validate:"omitempty,gte=0"`
	ModelInvocationID         string                               `json:"model_invocation_id" validate:"required,min=1"`
	ResponseArtifactReference artifact_reference.Reference         `json:"response_artifact_reference" validate:"required"`
	Usage                     map[string]any                       `json:"usage" validate:"required"`
}

func (value ModelInvocationCompleted) Validate() error {
	return shared.Validate(value)
}
