// Code generated by generategomodels; DO NOT EDIT.

package task_provenance

import (
	validator "github.com/go-playground/validator/v10"
	"time"
)

type TaskProvenance struct {
	CreatedAt  time.Time `json:"created_at" validate:"required"`
	SourceID   string    `json:"source_id" validate:"required,min=1"`
	SourceKind string    `json:"source_kind" validate:"required,min=1"`
	Trusted    bool      `json:"trusted" validate:"required"`
}

func (value TaskProvenance) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
