// Code generated by generategomodels; DO NOT EDIT.

package preparation_status

import (
	repository_diagnostic "github.com/julianstephens/kiln/go/schema/repository/diagnostic"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type PreparationStatusRefreshState string

const (
	PreparationStatusRefreshStateNotStarted PreparationStatusRefreshState = "not_started"

	PreparationStatusRefreshStateInProgress PreparationStatusRefreshState = "in_progress"

	PreparationStatusRefreshStateCompleted PreparationStatusRefreshState = "completed"

	PreparationStatusRefreshStateFailed PreparationStatusRefreshState = "failed"
)

type PreparationStatus struct {
	CurrentIndexState      *string                            `json:"current_index_state,omitempty" validate:"omitempty,min=1"`
	Diagnostics            []repository_diagnostic.Diagnostic `json:"diagnostics" validate:"required"`
	PreparationCheckpoints []map[string]any                   `json:"preparation_checkpoints" validate:"required"`
	RefreshState           *PreparationStatusRefreshState     `json:"refresh_state,omitempty" validate:"omitempty"`
	RepositoryVersion      map[string]any                     `json:"repository_version,omitempty" validate:"omitempty"`
	StaleFileCount         *int                               `json:"stale_file_count,omitempty" validate:"omitempty,gte=0"`
	WorkspaceVersion       map[string]any                     `json:"workspace_version,omitempty" validate:"omitempty"`
}

func (value PreparationStatus) Validate() error {
	return shared.Validate(value)
}
