// Code generated by generategomodels; DO NOT EDIT.

// Package run_initialization_started contains generated Go models for the Kiln event/payload/run-initialization-started schema.
package run_initialization_started
