// Code generated by generategomodels; DO NOT EDIT.

package run_initialization_started

import (
	validator "github.com/go-playground/validator/v10"
)

type RunInitializationStarted struct {
	InitializedOperationID string   `json:"initialized_operation_id" validate:"required,min=1"`
	RequestedAdapters      []string `json:"requested_adapters,omitempty" validate:"omitempty,min=1"`
	RuntimeSessionID       string   `json:"runtime_session_id" validate:"required,min=1"`
}

func (value RunInitializationStarted) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
