// Code generated by generategomodels; DO NOT EDIT.

package configuration

import (
	validator "github.com/go-playground/validator/v10"
)

type ConfigurationToolCallMode string

const (
	ConfigurationToolCallModeNone ConfigurationToolCallMode = "none"

	ConfigurationToolCallModeRestricted ConfigurationToolCallMode = "restricted"

	ConfigurationToolCallModeUnrestricted ConfigurationToolCallMode = "unrestricted"
)

type Configuration struct {
	ContextLimit         int                       `json:"context_limit" validate:"required,gte=1"`
	GenerationParameters map[string]any            `json:"generation_parameters" validate:"required"`
	LocalAdapterID       *string                   `json:"local_adapter_id,omitempty" validate:"omitempty,min=1"`
	ModelID              string                    `json:"model_id" validate:"required,min=1"`
	ProviderID           *string                   `json:"provider_id,omitempty" validate:"omitempty,min=1"`
	StreamingPreference  string                    `json:"streaming_preference" validate:"required,min=1"`
	TokenizerStrategy    string                    `json:"tokenizer_strategy" validate:"required,min=1"`
	ToolCallMode         ConfigurationToolCallMode `json:"tool_call_mode" validate:"required"`
}

func (value Configuration) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
