// Code generated by generategomodels; DO NOT EDIT.

package lifecycle_state

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// LifecycleState is generated from a nested JSON Schema object.
type LifecycleState struct {
}

func (value LifecycleState) Validate() error {
	return shared.Validate(value)
}
