// Code generated by generategomodels; DO NOT EDIT.

package lifecycle_state

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type LifecycleState struct {
}

func (value LifecycleState) Validate() error {
	return shared.Validate(value)
}
