// Code generated by generategomodels; DO NOT EDIT.

package lifecycle_state

import (
	validator "github.com/go-playground/validator/v10"
)

type LifecycleState struct {
}

func (value LifecycleState) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
