// Code generated by generategomodels; DO NOT EDIT.

package protocol_response

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ProtocolResponse struct {
}

func (value ProtocolResponse) Validate() error {
	return shared.Validate(value)
}
