// Code generated by generategomodels; DO NOT EDIT.

package source

import (
	common_byte_range "github.com/julianstephens/kiln/go/schema/common/byte_range"
	common_source_range "github.com/julianstephens/kiln/go/schema/common/source_range"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type Source struct {
	ByteRanges     []common_byte_range.ByteRange     `json:"byte_ranges" validate:"required"`
	Language       *string                           `json:"language,omitempty" validate:"omitempty,min=1"`
	LineRanges     []common_source_range.SourceRange `json:"line_ranges" validate:"required"`
	QualifiedName  *string                           `json:"qualified_name,omitempty" validate:"omitempty,min=1"`
	RepositoryPath string                            `json:"repository_path" validate:"required,min=1"`
	SourceDigest   string                            `json:"source_digest" validate:"required,min=1"`
}

func (value Source) Validate() error {
	return shared.Validate(value)
}
