// Code generated by generategomodels; DO NOT EDIT.

// Package repository_query_completed contains generated Go models for the Kiln event/payload/repository-query-completed schema.
package repository_query_completed
