// Code generated by generategomodels; DO NOT EDIT.

package repository_query_completed

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	repository_usage "github.com/julianstephens/kiln/go/schema/repository/usage"
	"time"
)

type RepositoryQueryCompletedQueryKind string

const (
	RepositoryQueryCompletedQueryKindSearch RepositoryQueryCompletedQueryKind = "search"

	RepositoryQueryCompletedQueryKindSource RepositoryQueryCompletedQueryKind = "source"

	RepositoryQueryCompletedQueryKindContent RepositoryQueryCompletedQueryKind = "content"

	RepositoryQueryCompletedQueryKindVersion RepositoryQueryCompletedQueryKind = "version"

	RepositoryQueryCompletedQueryKindDiagnostics RepositoryQueryCompletedQueryKind = "diagnostics"
)

type RepositoryQueryCompleted struct {
	BudgetUsage         *budget_usage.Usage               `json:"budget_usage,omitempty" validate:"omitempty"`
	CompletedAt         time.Time                         `json:"completed_at" validate:"required"`
	QueryKind           RepositoryQueryCompletedQueryKind `json:"query_kind" validate:"required"`
	QueryOperationID    string                            `json:"query_operation_id" validate:"required,min=1"`
	RepositorySessionID string                            `json:"repository_session_id" validate:"required,min=1"`
	ResultReference     *artifact_reference.Reference     `json:"result_reference,omitempty" validate:"omitempty"`
	ResultSummary       map[string]any                    `json:"result_summary" validate:"required"`
	Usage               repository_usage.Usage            `json:"usage" validate:"required"`
}

func (value RepositoryQueryCompleted) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
