// Code generated by generategomodels; DO NOT EDIT.

package plan

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	context_action "github.com/julianstephens/kiln/go/schema/context/action"
	"time"
)

type PlanPlanningGoal string

const (
	PlanPlanningGoalInitialContext PlanPlanningGoal = "initial_context"

	PlanPlanningGoalTurnContext PlanPlanningGoal = "turn_context"

	PlanPlanningGoalToolContext PlanPlanningGoal = "tool_context"

	PlanPlanningGoalModelInvocation PlanPlanningGoal = "model_invocation"

	PlanPlanningGoalOutputProduction PlanPlanningGoal = "output_production"

	PlanPlanningGoalValidation PlanPlanningGoal = "validation"

	PlanPlanningGoalRecovery PlanPlanningGoal = "recovery"
)

type PlanPlanningStatus string

const (
	PlanPlanningStatusProduced PlanPlanningStatus = "produced"

	PlanPlanningStatusApplied PlanPlanningStatus = "applied"

	PlanPlanningStatusRejected PlanPlanningStatus = "rejected"

	PlanPlanningStatusSuperseded PlanPlanningStatus = "superseded"

	PlanPlanningStatusFailed PlanPlanningStatus = "failed"
)

type PlanPlanningStrategy string

const (
	PlanPlanningStrategyRecency PlanPlanningStrategy = "recency"

	PlanPlanningStrategyRelevance PlanPlanningStrategy = "relevance"

	PlanPlanningStrategyPinnedFirst PlanPlanningStrategy = "pinned_first"

	PlanPlanningStrategyBudgetFit PlanPlanningStrategy = "budget_fit"

	PlanPlanningStrategyHybrid PlanPlanningStrategy = "hybrid"

	PlanPlanningStrategyManual PlanPlanningStrategy = "manual"
)

type Plan struct {
	AppliedAt                  *time.Time                    `json:"applied_at,omitempty" validate:"omitempty"`
	ClosedAt                   *time.Time                    `json:"closed_at,omitempty" validate:"omitempty"`
	ContextID                  string                        `json:"context_id" validate:"required,min=1"`
	ContextPlanID              string                        `json:"context_plan_id" validate:"required,min=1"`
	ContextPlanRequestID       *string                       `json:"context_plan_request_id,omitempty" validate:"omitempty,min=1"`
	CreatedAt                  time.Time                     `json:"created_at" validate:"required"`
	EstimatedTokenCount        int                           `json:"estimated_token_count" validate:"required,gte=0"`
	ModelContextLimit          int                           `json:"model_context_limit" validate:"required,gte=1"`
	PlanArtifactReference      *artifact_reference.Reference `json:"plan_artifact_reference,omitempty" validate:"omitempty"`
	PlannedActions             []context_action.Action       `json:"planned_actions" validate:"required,min=1"`
	PlannedActiveItems         []map[string]any              `json:"planned_active_items,omitempty" validate:"omitempty"`
	PlanningGoal               PlanPlanningGoal              `json:"planning_goal" validate:"required"`
	PlanningStatus             PlanPlanningStatus            `json:"planning_status" validate:"required"`
	PlanningStrategy           *PlanPlanningStrategy         `json:"planning_strategy,omitempty" validate:"omitempty"`
	ResultContextStateRevision *int                          `json:"result_context_state_revision,omitempty" validate:"omitempty,gte=0"`
	SourceContextStateRevision *int                          `json:"source_context_state_revision,omitempty" validate:"omitempty,gte=0"`
	TargetTokenBudget          *int                          `json:"target_token_budget,omitempty" validate:"omitempty,gte=0"`
}

func (value Plan) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
