// Code generated by generategomodels; DO NOT EDIT.

package plan

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	context_action "github.com/julianstephens/kiln/go/schema/context/action"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type PlanPlanningGoal string

const (
	PlanPlanningGoalInitialContext PlanPlanningGoal = "initial_context"

	PlanPlanningGoalTurnContext PlanPlanningGoal = "turn_context"

	PlanPlanningGoalToolContext PlanPlanningGoal = "tool_context"

	PlanPlanningGoalModelInvocation PlanPlanningGoal = "model_invocation"

	PlanPlanningGoalOutputProduction PlanPlanningGoal = "output_production"

	PlanPlanningGoalValidation PlanPlanningGoal = "validation"

	PlanPlanningGoalRecovery PlanPlanningGoal = "recovery"
)

type PlanPlanningStatus string

const (
	PlanPlanningStatusProduced PlanPlanningStatus = "produced"

	PlanPlanningStatusApplied PlanPlanningStatus = "applied"

	PlanPlanningStatusRejected PlanPlanningStatus = "rejected"

	PlanPlanningStatusSuperseded PlanPlanningStatus = "superseded"

	PlanPlanningStatusFailed PlanPlanningStatus = "failed"
)

type PlanPlanningStrategy string

const (
	PlanPlanningStrategyRecency PlanPlanningStrategy = "recency"

	PlanPlanningStrategyRelevance PlanPlanningStrategy = "relevance"

	PlanPlanningStrategyPinnedFirst PlanPlanningStrategy = "pinned_first"

	PlanPlanningStrategyBudgetFit PlanPlanningStrategy = "budget_fit"

	PlanPlanningStrategyHybrid PlanPlanningStrategy = "hybrid"

	PlanPlanningStrategyManual PlanPlanningStrategy = "manual"
)

// Plan a planned set of context actions that selects, orders, evicts, compresses, or otherwise prepares context items for rendering.
type Plan struct {
	// AppliedAt when the context plan was applied.
	AppliedAt *time.Time `json:"applied_at,omitempty" validate:"omitempty"`
	// ClosedAt when the context plan reached a terminal non-applied status.
	ClosedAt *time.Time `json:"closed_at,omitempty" validate:"omitempty"`
	// ContextID context ledger this plan applies to.
	ContextID string `json:"context_id" validate:"required,min=1"`
	// ContextPlanID stable identity for this context plan.
	ContextPlanID string `json:"context_plan_id" validate:"required,min=1"`
	// ContextPlanRequestID request identity that caused this plan to be produced.
	ContextPlanRequestID *string `json:"context_plan_request_id,omitempty" validate:"omitempty,min=1"`
	// CreatedAt when the context plan was created.
	CreatedAt time.Time `json:"created_at" validate:"required"`
	// EstimatedTokenCount estimated active-context token count after applying the plan.
	EstimatedTokenCount int `json:"estimated_token_count" validate:"required,gte=0"`
	// ModelContextLimit model context limit used during planning.
	ModelContextLimit int `json:"model_context_limit" validate:"required,gte=1"`
	// PlanArtifactReference artifact reference for this context plan, when stored durably outside the event stream.
	PlanArtifactReference *artifact_reference.Reference `json:"plan_artifact_reference,omitempty" validate:"omitempty"`
	// PlannedActions context mutations proposed by this plan.
	PlannedActions []context_action.Action `json:"planned_actions" validate:"required,min=1"`
	// PlannedActiveItems planned active context items in render order after applying the plan.
	PlannedActiveItems []PlanPlannedActiveItemsItem `json:"planned_active_items,omitempty" validate:"omitempty"`
	// PlanningGoal reason this context plan was produced.
	PlanningGoal PlanPlanningGoal `json:"planning_goal" validate:"required"`
	// PlanningStatus current status of the context plan.
	PlanningStatus PlanPlanningStatus `json:"planning_status" validate:"required"`
	// PlanningStrategy strategy used to produce this context plan.
	PlanningStrategy *PlanPlanningStrategy `json:"planning_strategy,omitempty" validate:"omitempty"`
	// ResultContextStateRevision context state revision after the plan was applied, when applicable.
	ResultContextStateRevision *int `json:"result_context_state_revision,omitempty" validate:"omitempty,gte=0"`
	// SourceContextStateRevision context state revision used as input to this plan.
	SourceContextStateRevision *int `json:"source_context_state_revision,omitempty" validate:"omitempty,gte=0"`
	// TargetTokenBudget planner target budget, when lower than the full model context limit.
	TargetTokenBudget *int `json:"target_token_budget,omitempty" validate:"omitempty,gte=0"`
}

// PlanPlannedActiveItemsItem is generated from a nested JSON Schema object.
type PlanPlannedActiveItemsItem struct {
	EstimatedTokens *int   `json:"estimated_tokens,omitempty" validate:"omitempty,gte=0"`
	ItemID          string `json:"item_id" validate:"required,min=1"`
	Order           int    `json:"order" validate:"required,gte=0"`
}

func (value Plan) Validate() error {
	return shared.Validate(value)
}
