// Code generated by generategomodels; DO NOT EDIT.

package scope

import (
	repository_identifier "github.com/julianstephens/kiln/go/schema/repository/identifier"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type Scope struct {
	Artifacts            map[string]any                    `json:"artifacts,omitempty" validate:"omitempty"`
	ExternalIntegrations []any                             `json:"external_integrations,omitempty" validate:"omitempty,min=1"`
	Filesystem           map[string]any                    `json:"filesystem,omitempty" validate:"omitempty"`
	InstallationID       *string                           `json:"installation_id,omitempty" validate:"omitempty,min=1"`
	ModelIds             []string                          `json:"model_ids,omitempty" validate:"omitempty,min=1"`
	NetworkDestinations  map[string]any                    `json:"network_destinations,omitempty" validate:"omitempty"`
	OperationKinds       []string                          `json:"operation_kinds,omitempty" validate:"omitempty,min=1"`
	Repository           *repository_identifier.Identifier `json:"repository,omitempty" validate:"omitempty"`
	RepositorySessionID  *string                           `json:"repository_session_id,omitempty" validate:"omitempty,min=1"`
	RunID                *string                           `json:"run_id,omitempty" validate:"omitempty,min=1"`
	TenantID             *string                           `json:"tenant_id,omitempty" validate:"omitempty,min=1"`
	Validation           map[string]any                    `json:"validation,omitempty" validate:"omitempty"`
}

func (value Scope) Validate() error {
	return shared.Validate(value)
}
