// Code generated by generategomodels; DO NOT EDIT.

package model_events

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// ModelEvents is generated from a nested JSON Schema object.
type ModelEvents struct {
}

func (value ModelEvents) Validate() error {
	return shared.Validate(value)
}
