// Code generated by generategomodels; DO NOT EDIT.

package model_events

import (
	validator "github.com/go-playground/validator/v10"
)

type ModelEvents struct {
}

func (value ModelEvents) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
