import argparse
import json
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DEFAULT_SCHEMA_ROOT = Path(__file__).resolve().parents[2] / "schemas"
DEFAULT_OUTPUT_ROOT = Path(__file__).resolve().parents[2] / "go" / "schema"
DEFAULT_MODULE_ROOT = "github.com/julianstephens/kiln/go/schema"
SCHEMA_ID_PREFIX = "https://kiln.cyborgdev.cloud/schemas/"

HEADER = """// Code generated by generategomodels; DO NOT EDIT.
"""

SHARED_VALIDATION_FILE = """// Code generated by generategomodels; DO NOT EDIT.

// Package shared contains helpers shared by generated Kiln schema models.
package shared

import "github.com/go-playground/validator/v10"

var validate = validator.New()

type Validatable interface {
	Validate() error
}

func Validate(value any) error {
	return validate.Struct(value)
}
"""

INITIALISMS = {
    "api": "API",
    "http": "HTTP",
    "https": "HTTPS",
    "id": "ID",
    "json": "JSON",
    "uri": "URI",
    "url": "URL",
    "uuid": "UUID",
}


class GenerateGoModelsError(Exception):
    pass


@dataclass(frozen=True)
class SchemaDefinition:
    key: str
    schema_id: str
    schema_path: Path
    document: dict[str, Any]


@dataclass(frozen=True)
class RefTarget:
    schema_key: str
    property_path: tuple[str, ...]


@dataclass(frozen=True)
class Field:
    name: str
    json_name: str
    go_type: str
    required: bool
    validate_tags: list[str]
    description: str | None


@dataclass(frozen=True)
class NestedType:
    name: str
    description: str | None
    fields: list[Field]
    properties: dict[str, Any]


def go_ident(value: str, *, exported: bool = True) -> str:
    parts = [part for part in re.split(r"[^0-9a-zA-Z]+", value) if part]
    if not parts:
        raise GenerateGoModelsError(f"could not convert {value!r} to a Go identifier")

    rendered: list[str] = []
    for part in parts:
        lower = part.lower()
        if lower in INITIALISMS:
            rendered.append(INITIALISMS[lower])
        else:
            rendered.append(part[:1].upper() + part[1:])

    ident = "".join(rendered)
    if ident[0].isdigit():
        ident = f"Schema{ident}"
    if not exported:
        ident = ident[:1].lower() + ident[1:]
    return ident


def go_package_name(value: str) -> str:
    normalized = re.sub(r"[^0-9a-zA-Z_]", "_", value)
    normalized = re.sub(r"_+", "_", normalized).strip("_").lower()
    if not normalized:
        raise GenerateGoModelsError(f"could not convert {value!r} to a Go package name")
    if normalized[0].isdigit():
        normalized = f"schema_{normalized}"
    return normalized


def parse_schema_key(schema_key: str) -> tuple[str, str]:
    parts = schema_key.split("/", maxsplit=1)
    if len(parts) != 2 or not parts[0] or not parts[1]:
        raise GenerateGoModelsError(
            f"invalid schema key {schema_key!r}; expected '<domain>/<contract>'"
        )
    return parts[0], parts[1]


def load_json(path: Path) -> Any:
    try:
        with path.open(encoding="utf-8") as file:
            return json.load(file)
    except FileNotFoundError as exc:
        raise GenerateGoModelsError(f"file does not exist: {path}") from exc
    except json.JSONDecodeError as exc:
        raise GenerateGoModelsError(
            f"{path}:{exc.lineno}:{exc.colno}: invalid JSON: {exc.msg}"
        ) from exc
    except OSError as exc:
        raise GenerateGoModelsError(f"could not read {path}: {exc}") from exc


def load_manifest(schema_root: Path) -> dict[str, Any]:
    manifest_path = schema_root / "manifest.json"
    manifest = load_json(manifest_path)
    if not isinstance(manifest, dict):
        raise GenerateGoModelsError(f"{manifest_path}: expected JSON object")

    schema_set_version = manifest.get("schema_set_version")
    if not isinstance(schema_set_version, str) or not schema_set_version:
        raise GenerateGoModelsError(
            f"{manifest_path}: schema_set_version must be a non-empty string"
        )

    compatibility_major = manifest.get("compatibility_major")
    if (
        not isinstance(compatibility_major, int)
        or isinstance(compatibility_major, bool)
        or compatibility_major < 1
    ):
        raise GenerateGoModelsError(
            f"{manifest_path}: compatibility_major must be a positive integer"
        )

    schemas = manifest.get("schemas")
    if not isinstance(schemas, list) or not schemas:
        raise GenerateGoModelsError(f"{manifest_path}: schemas must be a non-empty array")
    for index, schema_key in enumerate(schemas):
        if not isinstance(schema_key, str) or not schema_key:
            raise GenerateGoModelsError(
                f"{manifest_path}: schemas[{index}] must be a non-empty string"
            )
        parse_schema_key(schema_key)

    entrypoints = manifest.get("entrypoints")
    if entrypoints is not None:
        if not isinstance(entrypoints, list) or not entrypoints:
            raise GenerateGoModelsError(
                f"{manifest_path}: entrypoints must be a non-empty array"
            )
        schema_key_set = set(schemas)
        for index, schema_key in enumerate(entrypoints):
            if not isinstance(schema_key, str) or not schema_key:
                raise GenerateGoModelsError(
                    f"{manifest_path}: entrypoints[{index}] must be a non-empty string"
                )
            parse_schema_key(schema_key)
            if schema_key not in schema_key_set:
                raise GenerateGoModelsError(
                    f"{manifest_path}: entrypoint {schema_key!r} is not declared in schemas"
                )
    return manifest


def selected_schema_keys(manifest: dict[str, Any], *, only_entrypoints: bool) -> list[str]:
    field = "entrypoints" if only_entrypoints else "schemas"
    values = manifest.get(field)
    if not isinstance(values, list) or not values:
        raise GenerateGoModelsError(f"manifest field {field!r} must be a non-empty array")
    return list(values)


def schema_path_for_key(schema_root: Path, schema_key: str, *, major: int) -> Path:
    domain, contract = parse_schema_key(schema_key)
    contract_parts = contract.split("/")
    return (
        schema_root
        / domain
        / f"v{major}"
        / Path(*contract_parts[:-1])
        / f"{contract_parts[-1]}.schema.json"
    )


def schema_id_for_key(schema_key: str, *, major: int) -> str:
    domain, contract = parse_schema_key(schema_key)
    return f"{SCHEMA_ID_PREFIX}{domain}/v{major}/{contract}.schema.json"


def output_dir_for_key(output_root: Path, schema_key: str) -> Path:
    domain, contract = parse_schema_key(schema_key)
    contract_parts = [go_package_name(part) for part in contract.split("/")]
    return output_root / go_package_name(domain) / Path(*contract_parts)


def package_import_for_key(module_root: str, schema_key: str) -> str:
    domain, contract = parse_schema_key(schema_key)
    contract_parts = [go_package_name(part) for part in contract.split("/")]
    return "/".join([module_root.rstrip("/"), go_package_name(domain), *contract_parts])


def package_name_for_key(schema_key: str) -> str:
    _domain, contract = parse_schema_key(schema_key)
    return go_package_name(contract.split("/")[-1])


def type_name_for_key(schema_key: str) -> str:
    _domain, contract = parse_schema_key(schema_key)
    return go_ident(contract.split("/")[-1])


def type_name_for_ref_target(target: RefTarget) -> str:
    type_name = type_name_for_key(target.schema_key)
    for property_name in target.property_path:
        type_name += go_ident(property_name)
    return type_name


def load_schema_definitions(
    schema_root: Path,
    schema_keys: list[str],
    *,
    major: int,
) -> list[SchemaDefinition]:
    definitions: list[SchemaDefinition] = []
    for schema_key in schema_keys:
        schema_path = schema_path_for_key(schema_root, schema_key, major=major)
        document = load_json(schema_path)
        if not isinstance(document, dict):
            raise GenerateGoModelsError(f"{schema_path}: expected JSON object")

        schema_id = document.get("$id")
        expected_id = schema_id_for_key(schema_key, major=major)
        if not isinstance(schema_id, str) or not schema_id:
            raise GenerateGoModelsError(f"{schema_path}: missing non-empty $id")
        if schema_id != expected_id:
            raise GenerateGoModelsError(
                f"{schema_path}: $id mismatch: expected {expected_id!r}, got {schema_id!r}"
            )

        definitions.append(
            SchemaDefinition(
                key=schema_key,
                schema_id=schema_id,
                schema_path=schema_path,
                document=document,
            )
        )
    return definitions


def ref_to_target(ref: str, *, major: int) -> RefTarget | None:
    document_ref, separator, fragment = ref.partition("#")
    suffix = ".schema.json"
    if not document_ref.startswith(SCHEMA_ID_PREFIX) or not document_ref.endswith(suffix):
        return None

    relative = document_ref[len(SCHEMA_ID_PREFIX) : -len(suffix)]
    parts = relative.split("/")
    if len(parts) < 3:
        return None

    domain = parts[0]
    version = parts[1]
    if version != f"v{major}":
        return None

    property_path: tuple[str, ...] = ()
    if separator:
        fragment_parts = [part for part in fragment.split("/") if part]
        if len(fragment_parts) % 2 != 0:
            return None
        property_names: list[str] = []
        for index in range(0, len(fragment_parts), 2):
            if fragment_parts[index] != "properties":
                return None
            property_names.append(fragment_parts[index + 1])
        property_path = tuple(property_names)

    contract = "/".join(parts[2:])
    return RefTarget(schema_key=f"{domain}/{contract}", property_path=property_path)


def schema_type_value(schema: dict[str, Any]) -> str | list[str] | None:
    value = schema.get("type")
    if isinstance(value, str):
        return value
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return value
    return None


def schema_is_nullable(schema: dict[str, Any]) -> bool:
    value = schema_type_value(schema)
    return isinstance(value, list) and "null" in value


def non_null_schema_type(schema: dict[str, Any]) -> str | None:
    value = schema_type_value(schema)
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        non_null = [item for item in value if item != "null"]
        if len(non_null) == 1:
            return non_null[0]
    return None


def enum_type_name(parent_type_name: str, field_name: str) -> str:
    return f"{parent_type_name}{go_ident(field_name)}"


def nested_type_name(parent_type_name: str, field_name: str) -> str:
    return f"{parent_type_name}{go_ident(field_name)}"


def description_for_schema(schema: dict[str, Any]) -> str | None:
    description = schema.get("description")
    if isinstance(description, str) and description:
        return description
    return None


def inline_object_has_named_shape(schema: dict[str, Any]) -> bool:
    if non_null_schema_type(schema) != "object":
        return False
    properties = schema.get("properties")
    return isinstance(properties, dict) and bool(properties)


def go_type_for_schema(
    schema: dict[str, Any],
    *,
    major: int,
    module_root: str,
    imports: dict[str, str],
    parent_type_name: str,
    field_name: str,
    nested_types: dict[str, NestedType],
) -> str:
    ref = schema.get("$ref")
    if isinstance(ref, str):
        target = ref_to_target(ref, major=major)
        if target is None:
            return "any"

        import_path = package_import_for_key(module_root, target.schema_key)
        alias = import_alias_for_key(target.schema_key)
        imports[alias] = import_path
        return f"{alias}.{type_name_for_ref_target(target)}"

    if isinstance(schema.get("enum"), list):
        return enum_type_name(parent_type_name, field_name)

    schema_type = non_null_schema_type(schema)
    if schema_type == "string":
        if schema.get("format") == "date-time":
            imports["time"] = "time"
            return "time.Time"
        return "string"
    if schema_type == "integer":
        return "int"
    if schema_type == "number":
        return "float64"
    if schema_type == "boolean":
        return "bool"

    if schema_type == "array":
        items = schema.get("items")
        if isinstance(items, dict):
            item_type = go_type_for_schema(
                items,
                major=major,
                module_root=module_root,
                imports=imports,
                parent_type_name=parent_type_name,
                field_name=f"{field_name}_item",
                nested_types=nested_types,
            )
        else:
            item_type = "any"
        return f"[]{item_type}"

    if schema_type == "object":
        if inline_object_has_named_shape(schema):
            type_name = nested_type_name(parent_type_name, field_name)
            if type_name not in nested_types:
                properties = schema.get("properties")
                if not isinstance(properties, dict):
                    properties = {}
                nested_types[type_name] = NestedType(
                    name=type_name,
                    description=description_for_schema(schema),
                    fields=collect_fields_for_schema(
                        schema,
                        major=major,
                        module_root=module_root,
                        imports=imports,
                        parent_type_name=type_name,
                        nested_types=nested_types,
                    ),
                    properties=properties,
                )
            return type_name

        additional_properties = schema.get("additionalProperties")
        if isinstance(additional_properties, dict):
            value_type = go_type_for_schema(
                additional_properties,
                major=major,
                module_root=module_root,
                imports=imports,
                parent_type_name=parent_type_name,
                field_name=f"{field_name}_value",
                nested_types=nested_types,
            )
            return f"map[string]{value_type}"
        return "map[string]any"

    if "oneOf" in schema or "anyOf" in schema or "allOf" in schema:
        return "any"
    return "any"


def import_alias_for_key(schema_key: str) -> str:
    domain, contract = parse_schema_key(schema_key)
    parts = [domain, *contract.split("/")]
    return go_package_name("_".join(parts))


def validate_tags_for_schema(schema: dict[str, Any], *, required: bool) -> list[str]:
    tags: list[str] = []
    tags.append("required" if required else "omitempty")
    schema_type = non_null_schema_type(schema)

    min_length = schema.get("minLength")
    if schema_type == "string" and isinstance(min_length, int):
        tags.append(f"min={min_length}")
    max_length = schema.get("maxLength")
    if schema_type == "string" and isinstance(max_length, int):
        tags.append(f"max={max_length}")
    minimum = schema.get("minimum")
    if schema_type in {"integer", "number"} and isinstance(minimum, int | float):
        tags.append(f"gte={minimum}")
    exclusive_minimum = schema.get("exclusiveMinimum")
    if schema_type in {"integer", "number"} and isinstance(exclusive_minimum, int | float):
        tags.append(f"gt={exclusive_minimum}")
    maximum = schema.get("maximum")
    if schema_type in {"integer", "number"} and isinstance(maximum, int | float):
        tags.append(f"lte={maximum}")
    exclusive_maximum = schema.get("exclusiveMaximum")
    if schema_type in {"integer", "number"} and isinstance(exclusive_maximum, int | float):
        tags.append(f"lt={exclusive_maximum}")
    min_items = schema.get("minItems")
    if schema_type == "array" and isinstance(min_items, int):
        tags.append(f"min={min_items}")
    max_items = schema.get("maxItems")
    if schema_type == "array" and isinstance(max_items, int):
        tags.append(f"max={max_items}")

    fmt = schema.get("format")
    if schema_type == "string" and fmt == "uri":
        tags.append("url")
    elif schema_type == "string" and fmt == "email":
        tags.append("email")
    elif schema_type == "string" and fmt == "uuid":
        tags.append("uuid")
    return tags


def collect_fields_for_schema(
    schema: dict[str, Any],
    *,
    major: int,
    module_root: str,
    imports: dict[str, str],
    parent_type_name: str,
    nested_types: dict[str, NestedType],
) -> list[Field]:
    properties = schema.get("properties")
    if not isinstance(properties, dict):
        properties = {}
    required_value = schema.get("required")
    required = set(required_value) if isinstance(required_value, list) else set()
    fields: list[Field] = []

    for json_name, property_schema in sorted(properties.items()):
        if not isinstance(json_name, str) or not isinstance(property_schema, dict):
            continue
        is_required = json_name in required
        go_type = go_type_for_schema(
            property_schema,
            major=major,
            module_root=module_root,
            imports=imports,
            parent_type_name=parent_type_name,
            field_name=json_name,
            nested_types=nested_types,
        )

        if not is_required and not go_type.startswith("[]") and not go_type.startswith("map["):
            if go_type != "any":
                go_type = f"*{go_type}"
        if schema_is_nullable(property_schema) and not go_type.startswith("*"):
            if not go_type.startswith("[]") and not go_type.startswith("map[") and go_type != "any":
                go_type = f"*{go_type}"

        fields.append(
            Field(
                name=go_ident(json_name),
                json_name=json_name,
                go_type=go_type,
                required=is_required,
                validate_tags=validate_tags_for_schema(property_schema, required=is_required),
                description=description_for_schema(property_schema),
            )
        )
    return fields


def collect_enums(fields: list[Field], properties: dict[str, Any], *, parent_type_name: str) -> list[str]:
    chunks: list[str] = []
    emitted: set[str] = set()

    def emit_enum(enum_type: str, enum_values: list[Any]) -> None:
        if enum_type in emitted:
            return
        string_values = [value for value in enum_values if isinstance(value, str)]
        if not string_values:
            return
        emitted.add(enum_type)
        chunks.append(f"type {enum_type} string\n")
        chunks.append("const (\n")
        used_const_names: set[str] = set()
        for value in string_values:
            const_name = f"{enum_type}{go_ident(value)}"
            if const_name in used_const_names:
                suffix = 2
                while f"{const_name}{suffix}" in used_const_names:
                    suffix += 1
                const_name = f"{const_name}{suffix}"
            used_const_names.add(const_name)
            chunks.append(f'\t{const_name} {enum_type} = "{value}"\n')
        chunks.append(")\n")

    for field in fields:
        schema = properties.get(field.json_name)
        if not isinstance(schema, dict):
            continue
        enum_values = schema.get("enum")
        if isinstance(enum_values, list) and enum_values:
            emit_enum(enum_type_name(parent_type_name, field.json_name), enum_values)
        items = schema.get("items")
        if isinstance(items, dict):
            item_enum_values = items.get("enum")
            if isinstance(item_enum_values, list) and item_enum_values:
                emit_enum(enum_type_name(parent_type_name, f"{field.json_name}_item"), item_enum_values)
    return chunks


def render_imports(imports: dict[str, str]) -> str:
    if not imports:
        return ""
    lines = ["import (\n"]
    for alias, import_path in sorted(imports.items(), key=lambda item: item[1]):
        if alias == package_name_from_import_path(import_path):
            lines.append(f'\t"{import_path}"\n')
        else:
            lines.append(f'\t{alias} "{import_path}"\n')
    lines.append(")\n\n")
    return "".join(lines)


def package_name_from_import_path(import_path: str) -> str:
    return import_path.rstrip("/").split("/")[-1]


def go_comment(name: str, description: str | None) -> str:
    if not description:
        return f"// {name} is generated from a nested JSON Schema object.\n"
    normalized = " ".join(description.strip().split())
    if not normalized.endswith("."):
        normalized += "."
    return f"// {name} {normalized[:1].lower() + normalized[1:]}\n"


def render_fields(fields: list[Field]) -> str:
    chunks: list[str] = []
    for field in fields:
        if field.description:
            chunks.append(go_comment(field.name, field.description))
        json_tag = field.json_name
        if not field.required:
            json_tag += ",omitempty"
        validate_tag = ",".join(field.validate_tags)
        tags = [f'json:"{json_tag}"']
        if validate_tag:
            tags.append(f'validate:"{validate_tag}"')
        chunks.append(f"\t{field.name} {field.go_type} `{' '.join(tags)}`\n")
    return "".join(chunks)


def render_struct_type(type_name: str, fields: list[Field], description: str | None) -> str:
    chunks = [go_comment(type_name, description), f"type {type_name} struct {{\n"]
    chunks.append(render_fields(fields))
    chunks.append("}\n")
    return "".join(chunks)


def render_model_file(definition: SchemaDefinition, *, major: int, module_root: str) -> str:
    package_name = package_name_for_key(definition.key)
    type_name = type_name_for_key(definition.key)
    imports: dict[str, str] = {"shared": f"{module_root.rstrip('/')}/shared"}
    nested_types: dict[str, NestedType] = {}
    fields = collect_fields_for_schema(
        definition.document,
        major=major,
        module_root=module_root,
        imports=imports,
        parent_type_name=type_name,
        nested_types=nested_types,
    )

    root_properties = definition.document.get("properties")
    if not isinstance(root_properties, dict):
        root_properties = {}

    chunks: list[str] = [HEADER, "\n", f"package {package_name}\n\n", render_imports(imports)]
    chunks.extend(
        chunk + "\n"
        for chunk in collect_enums(fields, root_properties, parent_type_name=type_name)
    )
    chunks.append(render_struct_type(type_name, fields, description_for_schema(definition.document)))
    chunks.append("\n")

    for nested_type in nested_types.values():
        chunks.extend(
            chunk + "\n"
            for chunk in collect_enums(
                nested_type.fields,
                nested_type.properties,
                parent_type_name=nested_type.name,
            )
        )
        chunks.append(render_struct_type(nested_type.name, nested_type.fields, nested_type.description))
        chunks.append("\n")

    chunks.append(f"func (value {type_name}) Validate() error {{\n")
    chunks.append("\treturn shared.Validate(value)\n")
    chunks.append("}\n")
    return "".join(chunks)


def render_package_doc(definition: SchemaDefinition) -> str:
    package_name = package_name_for_key(definition.key)
    return (
        f"{HEADER}\n"
        f"// Package {package_name} contains generated Go models for the "
        f"Kiln {definition.key} schema.\n"
        f"package {package_name}\n"
    )


def render_version_file(*, compatibility_major: int, schema_set_version: str) -> str:
    return (
        f"{HEADER}\n"
        "// Package schema exposes generated Kiln schema metadata.\n"
        "package schema\n\n"
        "const (\n"
        f"\tCompatibilityMajor = {compatibility_major}\n"
        f'\tSchemaSetVersion = "{schema_set_version}"\n'
        ")\n"
    )


def write_model_files(
    output_root: Path,
    definitions: list[SchemaDefinition],
    *,
    major: int,
    module_root: str,
    dry_run: bool,
) -> None:
    for definition in definitions:
        package_dir = output_dir_for_key(output_root, definition.key)
        schema_path = package_dir / "schema.go"
        doc_path = package_dir / "doc.go"
        if dry_run:
            print(f"would write {schema_path}")
            print(f"would write {doc_path}")
            continue
        package_dir.mkdir(parents=True, exist_ok=True)
        schema_path.write_text(
            render_model_file(definition, major=major, module_root=module_root),
            encoding="utf-8",
        )
        doc_path.write_text(render_package_doc(definition), encoding="utf-8")


def write_shared_package(output_root: Path, *, dry_run: bool) -> None:
    shared_dir = output_root / "shared"
    validate_path = shared_dir / "validate.go"
    if dry_run:
        print(f"would write {validate_path}")
        return
    shared_dir.mkdir(parents=True, exist_ok=True)
    validate_path.write_text(SHARED_VALIDATION_FILE, encoding="utf-8")


def write_version_file(
    output_root: Path,
    *,
    compatibility_major: int,
    schema_set_version: str,
    dry_run: bool,
) -> None:
    version_path = output_root / "version.go"
    if dry_run:
        print(f"would write {version_path}")
        return
    output_root.mkdir(parents=True, exist_ok=True)
    version_path.write_text(
        render_version_file(
            compatibility_major=compatibility_major,
            schema_set_version=schema_set_version,
        ),
        encoding="utf-8",
    )


def clean_output_root(output_root: Path, *, dry_run: bool) -> None:
    if not output_root.exists():
        return
    if dry_run:
        print(f"would remove {output_root}")
        return
    shutil.rmtree(output_root)


def run_gofmt(output_root: Path, *, dry_run: bool) -> None:
    if dry_run:
        print(f"would run gofmt on {output_root}")
        return
    go_files = sorted(str(path) for path in output_root.rglob("*.go"))
    if not go_files:
        return
    try:
        subprocess.run(["gofmt", "-w", *go_files], check=True)
    except FileNotFoundError as exc:
        raise GenerateGoModelsError("gofmt not found") from exc
    except subprocess.CalledProcessError as exc:
        raise GenerateGoModelsError(f"gofmt failed with exit code {exc.returncode}") from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Kiln-specific Go models from JSON Schemas."
    )
    parser.add_argument(
        "--schema-root",
        type=Path,
        default=DEFAULT_SCHEMA_ROOT,
        help="Schema directory containing manifest.json.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=DEFAULT_OUTPUT_ROOT,
        help="Output root for generated Go schema packages.",
    )
    parser.add_argument(
        "--module-root",
        default=DEFAULT_MODULE_ROOT,
        help="Go import path root for generated schema packages.",
    )
    parser.add_argument(
        "--only-entrypoints",
        action="store_true",
        help="Generate only manifest entrypoints instead of every declared schema.",
    )
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Do not delete the output root before generation.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generation actions without writing files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    schema_root = args.schema_root.resolve()
    output_root = args.output_root.resolve()

    try:
        manifest = load_manifest(schema_root)
        major = manifest["compatibility_major"]
        schema_set_version = manifest["schema_set_version"]
        schema_keys = selected_schema_keys(manifest, only_entrypoints=args.only_entrypoints)
        definitions = load_schema_definitions(schema_root, schema_keys, major=major)

        if not args.no_clean:
            clean_output_root(output_root, dry_run=args.dry_run)

        write_version_file(
            output_root,
            compatibility_major=major,
            schema_set_version=schema_set_version,
            dry_run=args.dry_run,
        )
        write_shared_package(output_root, dry_run=args.dry_run)
        write_model_files(
            output_root,
            definitions,
            major=major,
            module_root=args.module_root,
            dry_run=args.dry_run,
        )
        run_gofmt(output_root, dry_run=args.dry_run)

    except GenerateGoModelsError as exc:
        print(f"Go model generation failed: {exc}", file=sys.stderr)
        return 1

    print(f"Generated Go schema models for {len(definitions)} schema(s) in {output_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
