// Code generated by generategomodels; DO NOT EDIT.

package rendered

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type RenderedRenderTarget string

const (
	RenderedRenderTargetModelInvocation RenderedRenderTarget = "model_invocation"

	RenderedRenderTargetToolInvocation RenderedRenderTarget = "tool_invocation"

	RenderedRenderTargetOutputProduction RenderedRenderTarget = "output_production"

	RenderedRenderTargetValidation RenderedRenderTarget = "validation"

	RenderedRenderTargetDiagnostic RenderedRenderTarget = "diagnostic"

	RenderedRenderTargetPreview RenderedRenderTarget = "preview"
)

type RenderedTruncationReason string

const (
	RenderedTruncationReasonModelContextLimit RenderedTruncationReason = "model_context_limit"

	RenderedTruncationReasonTargetTokenBudget RenderedTruncationReason = "target_token_budget"

	RenderedTruncationReasonItemSizeLimit RenderedTruncationReason = "item_size_limit"

	RenderedTruncationReasonPolicy RenderedTruncationReason = "policy"

	RenderedTruncationReasonManual RenderedTruncationReason = "manual"
)

type Rendered struct {
	ContentHash             *string                       `json:"content_hash,omitempty" validate:"omitempty,min=1"`
	ContextID               string                        `json:"context_id" validate:"required,min=1"`
	ContextPlanID           *string                       `json:"context_plan_id,omitempty" validate:"omitempty,min=1"`
	ContextStateRevision    int                           `json:"context_state_revision" validate:"required,gte=0"`
	ModelContextLimit       *int                          `json:"model_context_limit,omitempty" validate:"omitempty,gte=1"`
	RenderArtifactReference *artifact_reference.Reference `json:"render_artifact_reference,omitempty" validate:"omitempty"`
	RenderID                string                        `json:"render_id" validate:"required,min=1"`
	RenderTarget            RenderedRenderTarget          `json:"render_target" validate:"required"`
	RenderedAt              time.Time                     `json:"rendered_at" validate:"required"`
	RenderedItemCount       int                           `json:"rendered_item_count" validate:"required,gte=0"`
	RenderedItemIds         []string                      `json:"rendered_item_ids" validate:"required"`
	RenderedItems           []map[string]any              `json:"rendered_items,omitempty" validate:"omitempty"`
	RenderedTokenEstimate   int                           `json:"rendered_token_estimate" validate:"required,gte=0"`
	TargetOperationID       *string                       `json:"target_operation_id,omitempty" validate:"omitempty,min=1"`
	Truncated               *bool                         `json:"truncated,omitempty" validate:"omitempty"`
	TruncationReason        *RenderedTruncationReason     `json:"truncation_reason,omitempty" validate:"omitempty"`
}

func (value Rendered) Validate() error {
	return shared.Validate(value)
}
