// Code generated by generategomodels; DO NOT EDIT.

package initialize_request_payload

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type InitializeRequestPayload struct {
	Client             map[string]any `json:"client" validate:"required"`
	CompatibilityMajor int            `json:"compatibility_major" validate:"required,gte=0"`
	ProtocolVersion    string         `json:"protocol_version" validate:"required,min=1"`
	SchemaSetVersion   string         `json:"schema_set_version" validate:"required,min=1"`
}

func (value InitializeRequestPayload) Validate() error {
	return shared.Validate(value)
}
