// Code generated by generategomodels; DO NOT EDIT.

package exhaustion

import (
	validator "github.com/go-playground/validator/v10"
	budget_limits "github.com/julianstephens/kiln/go/schema/budget/limits"
	budget_state "github.com/julianstephens/kiln/go/schema/budget/state"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	"time"
)

type ExhaustionExhaustedDimensionsItem string

const (
	ExhaustionExhaustedDimensionsItemModelInputTokens ExhaustionExhaustedDimensionsItem = "model_input_tokens"

	ExhaustionExhaustedDimensionsItemModelOutputTokens ExhaustionExhaustedDimensionsItem = "model_output_tokens"

	ExhaustionExhaustedDimensionsItemModelCalls ExhaustionExhaustedDimensionsItem = "model_calls"

	ExhaustionExhaustedDimensionsItemToolCalls ExhaustionExhaustedDimensionsItem = "tool_calls"

	ExhaustionExhaustedDimensionsItemRepositoryRequests ExhaustionExhaustedDimensionsItem = "repository_requests"

	ExhaustionExhaustedDimensionsItemElapsedWallTimeSeconds ExhaustionExhaustedDimensionsItem = "elapsed_wall_time_seconds"

	ExhaustionExhaustedDimensionsItemMonetaryCostUsd ExhaustionExhaustedDimensionsItem = "monetary_cost_usd"

	ExhaustionExhaustedDimensionsItemCommandTimeSeconds ExhaustionExhaustedDimensionsItem = "command_time_seconds"

	ExhaustionExhaustedDimensionsItemCommandOutputSizeBytes ExhaustionExhaustedDimensionsItem = "command_output_size_bytes"

	ExhaustionExhaustedDimensionsItemArtifactSizeBytes ExhaustionExhaustedDimensionsItem = "artifact_size_bytes"

	ExhaustionExhaustedDimensionsItemRepeatedTokenCostUsd ExhaustionExhaustedDimensionsItem = "repeated_token_cost_usd"
)

type ExhaustionExhaustionReason string

const (
	ExhaustionExhaustionReasonReservationExceedsRemaining ExhaustionExhaustionReason = "reservation_exceeds_remaining"

	ExhaustionExhaustionReasonCommittedUsageReachedLimit ExhaustionExhaustionReason = "committed_usage_reached_limit"

	ExhaustionExhaustionReasonReconciliationReachedLimit ExhaustionExhaustionReason = "reconciliation_reached_limit"

	ExhaustionExhaustionReasonExternalLimitReached ExhaustionExhaustionReason = "external_limit_reached"

	ExhaustionExhaustionReasonTimeLimitReached ExhaustionExhaustionReason = "time_limit_reached"

	ExhaustionExhaustionReasonCostLimitReached ExhaustionExhaustionReason = "cost_limit_reached"

	ExhaustionExhaustionReasonUnknown ExhaustionExhaustionReason = "unknown"
)

type ExhaustionExhaustionScope string

const (
	ExhaustionExhaustionScopeRun ExhaustionExhaustionScope = "run"

	ExhaustionExhaustionScopeTurn ExhaustionExhaustionScope = "turn"

	ExhaustionExhaustionScopeOperation ExhaustionExhaustionScope = "operation"

	ExhaustionExhaustionScopeComponent ExhaustionExhaustionScope = "component"
)

type Exhaustion struct {
	BudgetID                   string                              `json:"budget_id" validate:"required,min=1"`
	CommittedUsage             *budget_usage.Usage                 `json:"committed_usage,omitempty" validate:"omitempty"`
	Component                  *string                             `json:"component,omitempty" validate:"omitempty,min=1"`
	ExhaustedAt                time.Time                           `json:"exhausted_at" validate:"required"`
	ExhaustedDimensions        []ExhaustionExhaustedDimensionsItem `json:"exhausted_dimensions" validate:"required,min=1"`
	ExhaustionID               string                              `json:"exhaustion_id" validate:"required,min=1"`
	ExhaustionReason           ExhaustionExhaustionReason          `json:"exhaustion_reason" validate:"required"`
	ExhaustionScope            ExhaustionExhaustionScope           `json:"exhaustion_scope" validate:"required"`
	OperationID                *string                             `json:"operation_id,omitempty" validate:"omitempty,min=1"`
	RequestedAmounts           *budget_limits.Limits               `json:"requested_amounts,omitempty" validate:"omitempty"`
	RunID                      *string                             `json:"run_id,omitempty" validate:"omitempty,min=1"`
	StateAtExhaustion          budget_state.State                  `json:"state_at_exhaustion" validate:"required"`
	TriggeringCommitmentID     *string                             `json:"triggering_commitment_id,omitempty" validate:"omitempty,min=1"`
	TriggeringReconciliationID *string                             `json:"triggering_reconciliation_id,omitempty" validate:"omitempty,min=1"`
	TriggeringReservationID    *string                             `json:"triggering_reservation_id,omitempty" validate:"omitempty,min=1"`
	TurnID                     *string                             `json:"turn_id,omitempty" validate:"omitempty,min=1"`
}

func (value Exhaustion) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
