// Code generated by generategomodels; DO NOT EDIT.

package candidate

import (
	validator "github.com/go-playground/validator/v10"
	repository_alternative_representation "github.com/julianstephens/kiln/go/schema/repository/alternative_representation"
	repository_content "github.com/julianstephens/kiln/go/schema/repository/content"
	repository_cost "github.com/julianstephens/kiln/go/schema/repository/cost"
	repository_identifier "github.com/julianstephens/kiln/go/schema/repository/identifier"
	repository_provenance "github.com/julianstephens/kiln/go/schema/repository/provenance"
	repository_relevance "github.com/julianstephens/kiln/go/schema/repository/relevance"
	repository_source "github.com/julianstephens/kiln/go/schema/repository/source"
	repository_validity "github.com/julianstephens/kiln/go/schema/repository/validity"
)

type Candidate struct {
	AlternativeRepresentations []repository_alternative_representation.AlternativeRepresentation `json:"alternative_representations" validate:"required"`
	Content                    repository_content.Content                                        `json:"content" validate:"required"`
	ContentID                  string                                                            `json:"content_id" validate:"required,min=1"`
	Cost                       repository_cost.Cost                                              `json:"cost" validate:"required"`
	Provenance                 repository_provenance.Provenance                                  `json:"provenance" validate:"required"`
	Relevance                  repository_relevance.Relevance                                    `json:"relevance" validate:"required"`
	Repository                 repository_identifier.IDentifier                                  `json:"repository" validate:"required"`
	RepresentationKind         string                                                            `json:"representation_kind" validate:"required,min=1"`
	SemanticKind               string                                                            `json:"semantic_kind" validate:"required,min=1"`
	Source                     repository_source.Source                                          `json:"source" validate:"required"`
	Validity                   repository_validity.Validity                                      `json:"validity" validate:"required"`
}

func (value Candidate) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
