// Code generated by generategomodels; DO NOT EDIT.

package version

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type Version struct {
	AffectedPaths            []string                      `json:"affected_paths,omitempty" validate:"omitempty,min=1"`
	BaseRepositoryVersionID  *string                       `json:"base_repository_version_id,omitempty" validate:"omitempty,min=1"`
	CreatedAt                *time.Time                    `json:"created_at,omitempty" validate:"omitempty"`
	InvalidatedEvidenceSet   []string                      `json:"invalidated_evidence_set,omitempty" validate:"omitempty"`
	InvalidationReference    *artifact_reference.Reference `json:"invalidation_reference,omitempty" validate:"omitempty"`
	MutationSet              []map[string]any              `json:"mutation_set,omitempty" validate:"omitempty"`
	ParentWorkspaceVersionID *string                       `json:"parent_workspace_version_id,omitempty" validate:"omitempty,min=1"`
	RepositoryID             *string                       `json:"repository_id,omitempty" validate:"omitempty,min=1"`
	Synchronized             *bool                         `json:"synchronized,omitempty" validate:"omitempty"`
	VersionID                *string                       `json:"version_id,omitempty" validate:"omitempty,min=1"`
}

func (value Version) Validate() error {
	return shared.Validate(value)
}
