// Code generated by generategomodels; DO NOT EDIT.

package usage

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type UsageMeasurement string

const (
	UsageMeasurementEstimated UsageMeasurement = "estimated"

	UsageMeasurementActual UsageMeasurement = "actual"

	UsageMeasurementReconciled UsageMeasurement = "reconciled"
)

type Usage struct {
	BillableInputTokens  *int              `json:"billable_input_tokens,omitempty" validate:"omitempty,gte=0"`
	BillableOutputTokens *int              `json:"billable_output_tokens,omitempty" validate:"omitempty,gte=0"`
	CachedInputTokens    *int              `json:"cached_input_tokens,omitempty" validate:"omitempty,gte=0"`
	EstimatedCostUsd     *float64          `json:"estimated_cost_usd,omitempty" validate:"omitempty,gte=0"`
	InputTokens          int               `json:"input_tokens" validate:"required,gte=0"`
	Measurement          *UsageMeasurement `json:"measurement,omitempty" validate:"omitempty"`
	OutputTokens         int               `json:"output_tokens" validate:"required,gte=0"`
	ReasoningTokens      *int              `json:"reasoning_tokens,omitempty" validate:"omitempty,gte=0"`
	TotalTokens          int               `json:"total_tokens" validate:"required,gte=0"`
}

func (value Usage) Validate() error {
	return shared.Validate(value)
}
