// Code generated by generategomodels; DO NOT EDIT.

package budget_committed

import (
	budget_state "github.com/julianstephens/kiln/go/schema/budget/state"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type BudgetCommittedCommitmentReason string

const (
	BudgetCommittedCommitmentReasonModelInvocationCompleted BudgetCommittedCommitmentReason = "model_invocation_completed"

	BudgetCommittedCommitmentReasonModelInvocationFailed BudgetCommittedCommitmentReason = "model_invocation_failed"

	BudgetCommittedCommitmentReasonToolInvocationCompleted BudgetCommittedCommitmentReason = "tool_invocation_completed"

	BudgetCommittedCommitmentReasonToolInvocationFailed BudgetCommittedCommitmentReason = "tool_invocation_failed"

	BudgetCommittedCommitmentReasonRepositoryOperationCompleted BudgetCommittedCommitmentReason = "repository_operation_completed"

	BudgetCommittedCommitmentReasonRepositoryOperationFailed BudgetCommittedCommitmentReason = "repository_operation_failed"

	BudgetCommittedCommitmentReasonArtifactWritten BudgetCommittedCommitmentReason = "artifact_written"

	BudgetCommittedCommitmentReasonOutputProductionCompleted BudgetCommittedCommitmentReason = "output_production_completed"

	BudgetCommittedCommitmentReasonValidationCompleted BudgetCommittedCommitmentReason = "validation_completed"

	BudgetCommittedCommitmentReasonRuntimeOperationCompleted BudgetCommittedCommitmentReason = "runtime_operation_completed"

	BudgetCommittedCommitmentReasonOther BudgetCommittedCommitmentReason = "other"
)

type BudgetCommittedMeasurement string

const (
	BudgetCommittedMeasurementEstimated BudgetCommittedMeasurement = "estimated"

	BudgetCommittedMeasurementActual BudgetCommittedMeasurement = "actual"

	BudgetCommittedMeasurementReconciled BudgetCommittedMeasurement = "reconciled"
)

type BudgetCommitted struct {
	BudgetID         string                           `json:"budget_id" validate:"required,min=1"`
	CommitmentID     string                           `json:"commitment_id" validate:"required,min=1"`
	CommitmentReason *BudgetCommittedCommitmentReason `json:"commitment_reason,omitempty" validate:"omitempty"`
	CommittedAt      time.Time                        `json:"committed_at" validate:"required"`
	Measurement      *BudgetCommittedMeasurement      `json:"measurement,omitempty" validate:"omitempty"`
	ReservationID    *string                          `json:"reservation_id,omitempty" validate:"omitempty,min=1"`
	StateAfter       budget_state.State               `json:"state_after" validate:"required"`
	Usage            budget_usage.Usage               `json:"usage" validate:"required"`
}

func (value BudgetCommitted) Validate() error {
	return shared.Validate(value)
}
