// Code generated by generategomodels; DO NOT EDIT.

package provenance

import (
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type ProvenanceCreationMethod string

const (
	ProvenanceCreationMethodGenerated ProvenanceCreationMethod = "generated"

	ProvenanceCreationMethodExtracted ProvenanceCreationMethod = "extracted"
)

// Provenance provenance metadata describing how repository content or representations were extracted or generated.
type Provenance struct {
	CreatedAt         time.Time                `json:"created_at" validate:"required"`
	CreationMethod    ProvenanceCreationMethod `json:"creation_method" validate:"required"`
	ExtractionMethod  *string                  `json:"extraction_method,omitempty" validate:"omitempty,min=1"`
	GenerationMethod  *string                  `json:"generation_method,omitempty" validate:"omitempty,min=1"`
	ParserVersion     *string                  `json:"parser_version,omitempty" validate:"omitempty,min=1"`
	QueryID           string                   `json:"query_id" validate:"required,min=1"`
	SourceContentIds  []string                 `json:"source_content_ids" validate:"required"`
	SourceOperationID string                   `json:"source_operation_id" validate:"required,min=1"`
	SummarizerVersion *string                  `json:"summarizer_version,omitempty" validate:"omitempty,min=1"`
}

func (value Provenance) Validate() error {
	return shared.Validate(value)
}
