// Code generated by generategomodels; DO NOT EDIT.

// Package model_egress_evaluated contains generated Go models for the Kiln event/payload/model-egress-evaluated schema.
package model_egress_evaluated
