// Code generated by generategomodels; DO NOT EDIT.

package model_egress_evaluated

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	capability_decision "github.com/julianstephens/kiln/go/schema/capability/decision"
	"time"
)

type ModelEgressEvaluatedEgressDecision string

const (
	ModelEgressEvaluatedEgressDecisionAllowed ModelEgressEvaluatedEgressDecision = "allowed"

	ModelEgressEvaluatedEgressDecisionDenied ModelEgressEvaluatedEgressDecision = "denied"

	ModelEgressEvaluatedEgressDecisionRedacted ModelEgressEvaluatedEgressDecision = "redacted"

	ModelEgressEvaluatedEgressDecisionRequiresApproval ModelEgressEvaluatedEgressDecision = "requires_approval"
)

type ModelEgressEvaluated struct {
	EgressDecision           ModelEgressEvaluatedEgressDecision `json:"egress_decision" validate:"required"`
	EvaluatedAt              time.Time                          `json:"evaluated_at" validate:"required"`
	ModelInvocationID        string                             `json:"model_invocation_id" validate:"required,min=1"`
	PolicyDecisionReference  *capability_decision.Decision      `json:"policy_decision_reference,omitempty" validate:"omitempty"`
	RedactionSummary         map[string]any                     `json:"redaction_summary,omitempty" validate:"omitempty"`
	RequestArtifactReference *artifact_reference.Reference      `json:"request_artifact_reference,omitempty" validate:"omitempty"`
}

func (value ModelEgressEvaluated) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
