// Code generated by generategomodels; DO NOT EDIT.

package source_range

import (
	validator "github.com/go-playground/validator/v10"
)

type SourceRange struct {
	End   map[string]any `json:"end" validate:"required"`
	Start map[string]any `json:"start" validate:"required"`
}

func (value SourceRange) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
