// Code generated by generategomodels; DO NOT EDIT.

package source_range

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type SourceRange struct {
	End   map[string]any `json:"end" validate:"required"`
	Start map[string]any `json:"start" validate:"required"`
}

func (value SourceRange) Validate() error {
	return shared.Validate(value)
}
