// Code generated by generategomodels; DO NOT EDIT.

package source_range

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// SourceRange line and column source range within a repository file or generated source representation.
type SourceRange struct {
	End   SourceRangeEnd   `json:"end" validate:"required"`
	Start SourceRangeStart `json:"start" validate:"required"`
}

// SourceRangeEnd is generated from a nested JSON Schema object.
type SourceRangeEnd struct {
	Column int `json:"column" validate:"required,gte=1"`
	Line   int `json:"line" validate:"required,gte=1"`
}

// SourceRangeStart is generated from a nested JSON Schema object.
type SourceRangeStart struct {
	Column int `json:"column" validate:"required,gte=1"`
	Line   int `json:"line" validate:"required,gte=1"`
}

func (value SourceRange) Validate() error {
	return shared.Validate(value)
}
