// Code generated by generategomodels; DO NOT EDIT.

package artifact_events

import (
	validator "github.com/go-playground/validator/v10"
)

type ArtifactEvents struct {
}

func (value ArtifactEvents) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
