// Code generated by generategomodels; DO NOT EDIT.

package artifact_events

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ArtifactEvents struct {
}

func (value ArtifactEvents) Validate() error {
	return shared.Validate(value)
}
