// Code generated by generategomodels; DO NOT EDIT.

package artifact_events

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// ArtifactEvents is generated from a nested JSON Schema object.
type ArtifactEvents struct {
}

func (value ArtifactEvents) Validate() error {
	return shared.Validate(value)
}
