// Code generated by generategomodels; DO NOT EDIT.

// Package repository_query_failed contains generated Go models for the Kiln event/payload/repository-query-failed schema.
package repository_query_failed
