// Code generated by generategomodels; DO NOT EDIT.

package repository_query_failed

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	repository_error "github.com/julianstephens/kiln/go/schema/repository/error"
	repository_usage "github.com/julianstephens/kiln/go/schema/repository/usage"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type RepositoryQueryFailedQueryKind string

const (
	RepositoryQueryFailedQueryKindSearch RepositoryQueryFailedQueryKind = "search"

	RepositoryQueryFailedQueryKindSource RepositoryQueryFailedQueryKind = "source"

	RepositoryQueryFailedQueryKindContent RepositoryQueryFailedQueryKind = "content"

	RepositoryQueryFailedQueryKindVersion RepositoryQueryFailedQueryKind = "version"

	RepositoryQueryFailedQueryKindDiagnostics RepositoryQueryFailedQueryKind = "diagnostics"
)

type RepositoryQueryFailed struct {
	BudgetUsage            *budget_usage.Usage            `json:"budget_usage,omitempty" validate:"omitempty"`
	Error                  repository_error.Error         `json:"error" validate:"required"`
	FailedAt               time.Time                      `json:"failed_at" validate:"required"`
	PartialResultReference *artifact_reference.Reference  `json:"partial_result_reference,omitempty" validate:"omitempty"`
	QueryKind              RepositoryQueryFailedQueryKind `json:"query_kind" validate:"required"`
	QueryOperationID       string                         `json:"query_operation_id" validate:"required,min=1"`
	RepositorySessionID    string                         `json:"repository_session_id" validate:"required,min=1"`
	Usage                  *repository_usage.Usage        `json:"usage,omitempty" validate:"omitempty"`
}

func (value RepositoryQueryFailed) Validate() error {
	return shared.Validate(value)
}
