// Code generated by generategomodels; DO NOT EDIT.

// Package repository_session_opened contains generated Go models for the Kiln event/payload/repository-session-opened schema.
package repository_session_opened
