// Code generated by generategomodels; DO NOT EDIT.

package repository_session_opened

import (
	repository_identifier "github.com/julianstephens/kiln/go/schema/repository/identifier"
	repository_preparation_status "github.com/julianstephens/kiln/go/schema/repository/preparation_status"
	repository_version "github.com/julianstephens/kiln/go/schema/repository/version"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type RepositorySessionOpenedSupportedOperationsItem string

const (
	RepositorySessionOpenedSupportedOperationsItemRepositorySearch RepositorySessionOpenedSupportedOperationsItem = "repository.search"

	RepositorySessionOpenedSupportedOperationsItemRepositorySource RepositorySessionOpenedSupportedOperationsItem = "repository.source"

	RepositorySessionOpenedSupportedOperationsItemRepositoryVersion RepositorySessionOpenedSupportedOperationsItem = "repository.version"

	RepositorySessionOpenedSupportedOperationsItemRepositoryDiagnostics RepositorySessionOpenedSupportedOperationsItem = "repository.diagnostics"
)

// RepositorySessionOpened payload for repository.session_opened events.
type RepositorySessionOpened struct {
	// OpenedAt when the repository session was opened.
	OpenedAt time.Time `json:"opened_at" validate:"required"`
	// PreparationStatus preparation status available for the opened session.
	PreparationStatus repository_preparation_status.PreparationStatus `json:"preparation_status" validate:"required"`
	// Repository repository associated with the opened session.
	Repository repository_identifier.Identifier `json:"repository" validate:"required"`
	// RepositorySessionID repository session that was opened.
	RepositorySessionID string `json:"repository_session_id" validate:"required,min=1"`
	// RepositoryVersion repository version observed when the session was opened.
	RepositoryVersion repository_version.Version `json:"repository_version" validate:"required"`
	// SupportedOperations repository operations available for this session.
	SupportedOperations []RepositorySessionOpenedSupportedOperationsItem `json:"supported_operations,omitempty" validate:"omitempty,min=1"`
}

func (value RepositorySessionOpened) Validate() error {
	return shared.Validate(value)
}
