// Code generated by generategomodels; DO NOT EDIT.

package source_request

import (
	validator "github.com/go-playground/validator/v10"
)

type SourceRequest struct {
}

func (value SourceRequest) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
