// Code generated by generategomodels; DO NOT EDIT.

package source_request

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type SourceRequest struct {
}

func (value SourceRequest) Validate() error {
	return shared.Validate(value)
}
