// Code generated by generategomodels; DO NOT EDIT.

package action

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
)

type ActionActionKind string

const (
	ActionActionKindMakeAvailable ActionActionKind = "make_available"

	ActionActionKindAdmit ActionActionKind = "admit"

	ActionActionKindEvict ActionActionKind = "evict"

	ActionActionKindPin ActionActionKind = "pin"

	ActionActionKindUnpin ActionActionKind = "unpin"

	ActionActionKindMarkStale ActionActionKind = "mark_stale"

	ActionActionKindInvalidate ActionActionKind = "invalidate"

	ActionActionKindCompress ActionActionKind = "compress"

	ActionActionKindReorder ActionActionKind = "reorder"
)

type ActionReason string

const (
	ActionReasonPinned ActionReason = "pinned"

	ActionReasonRecent ActionReason = "recent"

	ActionReasonRelevant ActionReason = "relevant"

	ActionReasonRequired ActionReason = "required"

	ActionReasonDependency ActionReason = "dependency"

	ActionReasonTokenBudget ActionReason = "token_budget"

	ActionReasonStale ActionReason = "stale"

	ActionReasonSuperseded ActionReason = "superseded"

	ActionReasonLowRelevance ActionReason = "low_relevance"

	ActionReasonManual ActionReason = "manual"

	ActionReasonPlanApplied ActionReason = "plan_applied"

	ActionReasonContextReset ActionReason = "context_reset"

	ActionReasonCompressionBudget ActionReason = "compression_budget"

	ActionReasonInvalidSource ActionReason = "invalid_source"
)

type Action struct {
	ActionID              string                        `json:"action_id" validate:"required,min=1"`
	ActionKind            ActionActionKind              `json:"action_kind" validate:"required"`
	ArtifactReference     *artifact_reference.Reference `json:"artifact_reference,omitempty" validate:"omitempty"`
	ContextID             string                        `json:"context_id" validate:"required,min=1"`
	ContextPlanID         *string                       `json:"context_plan_id,omitempty" validate:"omitempty,min=1"`
	EstimatedTokensAfter  *int                          `json:"estimated_tokens_after,omitempty" validate:"omitempty,gte=0"`
	EstimatedTokensBefore *int                          `json:"estimated_tokens_before,omitempty" validate:"omitempty,gte=0"`
	ItemID                string                        `json:"item_id" validate:"required,min=1"`
	Order                 *int                          `json:"order,omitempty" validate:"omitempty,gte=0"`
	PreviousOrder         *int                          `json:"previous_order,omitempty" validate:"omitempty,gte=0"`
	Reason                *ActionReason                 `json:"reason,omitempty" validate:"omitempty"`
	ReplacementItemID     *string                       `json:"replacement_item_id,omitempty" validate:"omitempty,min=1"`
}

func (value Action) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
