// Code generated by generategomodels; DO NOT EDIT.

// Package open_session_request_payload contains generated Go models for the Kiln repository/open-session-request-payload schema.
package open_session_request_payload
