// Code generated by generategomodels; DO NOT EDIT.

package open_session_request_payload

import (
	repository_identifier "github.com/julianstephens/kiln/go/schema/repository/identifier"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type OpenSessionRequestPayloadAllowedOperationsItem string

const (
	OpenSessionRequestPayloadAllowedOperationsItemRepositorySearch OpenSessionRequestPayloadAllowedOperationsItem = "repository.search"

	OpenSessionRequestPayloadAllowedOperationsItemRepositoryGetSource OpenSessionRequestPayloadAllowedOperationsItem = "repository.get_source"

	OpenSessionRequestPayloadAllowedOperationsItemRepositoryGetContent OpenSessionRequestPayloadAllowedOperationsItem = "repository.get_content"

	OpenSessionRequestPayloadAllowedOperationsItemRepositoryGetVersion OpenSessionRequestPayloadAllowedOperationsItem = "repository.get_version"

	OpenSessionRequestPayloadAllowedOperationsItemRepositoryGetDiagnostics OpenSessionRequestPayloadAllowedOperationsItem = "repository.get_diagnostics"
)

type OpenSessionRequestPayload struct {
	AllowedOperations []OpenSessionRequestPayloadAllowedOperationsItem `json:"allowed_operations" validate:"required,min=1"`
	Repository        repository_identifier.Identifier                 `json:"repository" validate:"required"`
	RunID             string                                           `json:"run_id" validate:"required,min=1"`
}

func (value OpenSessionRequestPayload) Validate() error {
	return shared.Validate(value)
}
