// Code generated by generategomodels; DO NOT EDIT.

// Package model_invocation_failed contains generated Go models for the Kiln event/payload/model-invocation-failed schema.
package model_invocation_failed
