// Code generated by generategomodels; DO NOT EDIT.

package model_invocation_failed

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	run_error "github.com/julianstephens/kiln/go/schema/run/error"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type ModelInvocationFailedFailureCategory string

const (
	ModelInvocationFailedFailureCategoryProviderError ModelInvocationFailedFailureCategory = "provider_error"

	ModelInvocationFailedFailureCategoryTimeout ModelInvocationFailedFailureCategory = "timeout"

	ModelInvocationFailedFailureCategoryRateLimited ModelInvocationFailedFailureCategory = "rate_limited"

	ModelInvocationFailedFailureCategoryQuotaExceeded ModelInvocationFailedFailureCategory = "quota_exceeded"

	ModelInvocationFailedFailureCategoryContentFilter ModelInvocationFailedFailureCategory = "content_filter"

	ModelInvocationFailedFailureCategoryEgressDenied ModelInvocationFailedFailureCategory = "egress_denied"

	ModelInvocationFailedFailureCategoryInvalidRequest ModelInvocationFailedFailureCategory = "invalid_request"

	ModelInvocationFailedFailureCategoryAdapterError ModelInvocationFailedFailureCategory = "adapter_error"

	ModelInvocationFailedFailureCategoryCanceled ModelInvocationFailedFailureCategory = "canceled"

	ModelInvocationFailedFailureCategoryUnknown ModelInvocationFailedFailureCategory = "unknown"
)

// ModelInvocationFailed payload for model.invocation_failed events.
type ModelInvocationFailed struct {
	// BudgetUsage budget usage committed before this invocation failed.
	BudgetUsage *budget_usage.Usage `json:"budget_usage,omitempty" validate:"omitempty"`
	// Error run-level error describing the failed model invocation.
	Error run_error.Error `json:"error" validate:"required"`
	// FailedAt when the model invocation failed.
	FailedAt time.Time `json:"failed_at" validate:"required"`
	// FailureCategory normalized model invocation failure category.
	FailureCategory ModelInvocationFailedFailureCategory `json:"failure_category" validate:"required"`
	// LatencyMs elapsed invocation latency before failure in milliseconds.
	LatencyMs *int `json:"latency_ms,omitempty" validate:"omitempty,gte=0"`
	// ModelInvocationID model invocation that failed.
	ModelInvocationID string `json:"model_invocation_id" validate:"required,min=1"`
	// PartialResponseArtifactReference optional artifact reference for partial model output received before failure.
	PartialResponseArtifactReference *artifact_reference.Reference `json:"partial_response_artifact_reference,omitempty" validate:"omitempty"`
	// Retryable whether this failure may be retried by the runtime.
	Retryable *bool `json:"retryable,omitempty" validate:"omitempty"`
}

func (value ModelInvocationFailed) Validate() error {
	return shared.Validate(value)
}
