// Code generated by generategomodels; DO NOT EDIT.

package budget_denied

import (
	budget_limits "github.com/julianstephens/kiln/go/schema/budget/limits"
	budget_state "github.com/julianstephens/kiln/go/schema/budget/state"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type BudgetDeniedDenialReason string

const (
	BudgetDeniedDenialReasonLimitExceeded BudgetDeniedDenialReason = "limit_exceeded"

	BudgetDeniedDenialReasonReservationExceedsRemaining BudgetDeniedDenialReason = "reservation_exceeds_remaining"

	BudgetDeniedDenialReasonBudgetExhausted BudgetDeniedDenialReason = "budget_exhausted"

	BudgetDeniedDenialReasonBudgetNotInitialized BudgetDeniedDenialReason = "budget_not_initialized"

	BudgetDeniedDenialReasonInvalidRequest BudgetDeniedDenialReason = "invalid_request"

	BudgetDeniedDenialReasonPolicyDenied BudgetDeniedDenialReason = "policy_denied"

	BudgetDeniedDenialReasonUnknown BudgetDeniedDenialReason = "unknown"
)

type BudgetDeniedDeniedDimensionsItem string

const (
	BudgetDeniedDeniedDimensionsItemModelInputTokens BudgetDeniedDeniedDimensionsItem = "model_input_tokens"

	BudgetDeniedDeniedDimensionsItemModelOutputTokens BudgetDeniedDeniedDimensionsItem = "model_output_tokens"

	BudgetDeniedDeniedDimensionsItemModelCalls BudgetDeniedDeniedDimensionsItem = "model_calls"

	BudgetDeniedDeniedDimensionsItemToolCalls BudgetDeniedDeniedDimensionsItem = "tool_calls"

	BudgetDeniedDeniedDimensionsItemRepositoryRequests BudgetDeniedDeniedDimensionsItem = "repository_requests"

	BudgetDeniedDeniedDimensionsItemElapsedWallTimeSeconds BudgetDeniedDeniedDimensionsItem = "elapsed_wall_time_seconds"

	BudgetDeniedDeniedDimensionsItemMonetaryCostUsd BudgetDeniedDeniedDimensionsItem = "monetary_cost_usd"

	BudgetDeniedDeniedDimensionsItemCommandTimeSeconds BudgetDeniedDeniedDimensionsItem = "command_time_seconds"

	BudgetDeniedDeniedDimensionsItemCommandOutputSizeBytes BudgetDeniedDeniedDimensionsItem = "command_output_size_bytes"

	BudgetDeniedDeniedDimensionsItemArtifactSizeBytes BudgetDeniedDeniedDimensionsItem = "artifact_size_bytes"

	BudgetDeniedDeniedDimensionsItemRepeatedTokenCostUsd BudgetDeniedDeniedDimensionsItem = "repeated_token_cost_usd"
)

// BudgetDenied payload for budget.denied events.
type BudgetDenied struct {
	BudgetID string `json:"budget_id" validate:"required,min=1"`
	// DenialID identity for this budget denial decision.
	DenialID string `json:"denial_id" validate:"required,min=1"`
	// DenialReason reason the budget request was denied.
	DenialReason BudgetDeniedDenialReason `json:"denial_reason" validate:"required"`
	// DeniedAt when budget was denied.
	DeniedAt time.Time `json:"denied_at" validate:"required"`
	// DeniedDimensions budget dimensions that caused or contributed to denial.
	DeniedDimensions []BudgetDeniedDeniedDimensionsItem `json:"denied_dimensions,omitempty" validate:"omitempty,min=1"`
	// RequestedAmounts budget amounts requested but denied.
	RequestedAmounts budget_limits.Limits `json:"requested_amounts" validate:"required"`
	// ReservationID reservation identity that was denied, when the denial occurred during reservation.
	ReservationID *string `json:"reservation_id,omitempty" validate:"omitempty,min=1"`
	// StateAtDenial budget state when the request was denied.
	StateAtDenial budget_state.State `json:"state_at_denial" validate:"required"`
}

func (value BudgetDenied) Validate() error {
	return shared.Validate(value)
}
