// Code generated by generategomodels; DO NOT EDIT.

// Package model_invocation_started contains generated Go models for the Kiln event/payload/model-invocation-started schema.
package model_invocation_started
