// Code generated by generategomodels; DO NOT EDIT.

// Package run_output_production_started contains generated Go models for the Kiln event/payload/run-output-production-started schema.
package run_output_production_started
