// Code generated by generategomodels; DO NOT EDIT.

package run_output_production_started

import (
	run_output_mode "github.com/julianstephens/kiln/go/schema/run/output_mode"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type RunOutputProductionStartedExpectedArtifactKindsItem string

const (
	RunOutputProductionStartedExpectedArtifactKindsItemAnswer RunOutputProductionStartedExpectedArtifactKindsItem = "answer"

	RunOutputProductionStartedExpectedArtifactKindsItemPatch RunOutputProductionStartedExpectedArtifactKindsItem = "patch"

	RunOutputProductionStartedExpectedArtifactKindsItemReport RunOutputProductionStartedExpectedArtifactKindsItem = "report"

	RunOutputProductionStartedExpectedArtifactKindsItemChangedFileManifest RunOutputProductionStartedExpectedArtifactKindsItem = "changed_file_manifest"

	RunOutputProductionStartedExpectedArtifactKindsItemValidationReport RunOutputProductionStartedExpectedArtifactKindsItem = "validation_report"
)

// RunOutputProductionStarted is generated from a nested JSON Schema object.
type RunOutputProductionStarted struct {
	// CompletionProposalID the proposal that is being used to produce the output for this run.
	CompletionProposalID string `json:"completion_proposal_id" validate:"required,min=1"`
	// ExpectedArtifactKinds the artifact kinds that are expected to be produced by this run.
	ExpectedArtifactKinds []RunOutputProductionStartedExpectedArtifactKindsItem `json:"expected_artifact_kinds" validate:"required,min=1"`
	// OutputMode the output mode that is being used to produce the output for this run.
	OutputMode run_output_mode.OutputMode `json:"output_mode" validate:"required"`
}

func (value RunOutputProductionStarted) Validate() error {
	return shared.Validate(value)
}
