// Code generated by generategomodels; DO NOT EDIT.

package run_output_production_started

import (
	validator "github.com/go-playground/validator/v10"
	run_output_mode "github.com/julianstephens/kiln/go/schema/run/output_mode"
)

type RunOutputProductionStartedExpectedArtifactKindsItem string

const (
	RunOutputProductionStartedExpectedArtifactKindsItemAnswer RunOutputProductionStartedExpectedArtifactKindsItem = "answer"

	RunOutputProductionStartedExpectedArtifactKindsItemPatch RunOutputProductionStartedExpectedArtifactKindsItem = "patch"

	RunOutputProductionStartedExpectedArtifactKindsItemReport RunOutputProductionStartedExpectedArtifactKindsItem = "report"

	RunOutputProductionStartedExpectedArtifactKindsItemChangedFileManifest RunOutputProductionStartedExpectedArtifactKindsItem = "changed_file_manifest"

	RunOutputProductionStartedExpectedArtifactKindsItemValidationReport RunOutputProductionStartedExpectedArtifactKindsItem = "validation_report"
)

type RunOutputProductionStarted struct {
	CompletionProposalID  string                                                `json:"completion_proposal_id" validate:"required,min=1"`
	ExpectedArtifactKinds []RunOutputProductionStartedExpectedArtifactKindsItem `json:"expected_artifact_kinds" validate:"required,min=1"`
	OutputMode            run_output_mode.OutputMode                            `json:"output_mode" validate:"required"`
}

func (value RunOutputProductionStarted) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
