// Code generated by generategomodels; DO NOT EDIT.

package budget_reserved

import (
	budget_limits "github.com/julianstephens/kiln/go/schema/budget/limits"
	budget_state "github.com/julianstephens/kiln/go/schema/budget/state"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type BudgetReservedReservationReason string

const (
	BudgetReservedReservationReasonModelInvocation BudgetReservedReservationReason = "model_invocation"

	BudgetReservedReservationReasonToolInvocation BudgetReservedReservationReason = "tool_invocation"

	BudgetReservedReservationReasonRepositoryOperation BudgetReservedReservationReason = "repository_operation"

	BudgetReservedReservationReasonOutputProduction BudgetReservedReservationReason = "output_production"

	BudgetReservedReservationReasonValidation BudgetReservedReservationReason = "validation"

	BudgetReservedReservationReasonRuntimeOperation BudgetReservedReservationReason = "runtime_operation"

	BudgetReservedReservationReasonOther BudgetReservedReservationReason = "other"
)

type BudgetReservedReservationScope string

const (
	BudgetReservedReservationScopeRun BudgetReservedReservationScope = "run"

	BudgetReservedReservationScopeTurn BudgetReservedReservationScope = "turn"

	BudgetReservedReservationScopeOperation BudgetReservedReservationScope = "operation"

	BudgetReservedReservationScopeComponent BudgetReservedReservationScope = "component"
)

type BudgetReserved struct {
	BudgetID          string                           `json:"budget_id" validate:"required,min=1"`
	Component         *string                          `json:"component,omitempty" validate:"omitempty,min=1"`
	ExpiresAt         *time.Time                       `json:"expires_at,omitempty" validate:"omitempty"`
	OperationID       *string                          `json:"operation_id,omitempty" validate:"omitempty,min=1"`
	ReservationID     string                           `json:"reservation_id" validate:"required,min=1"`
	ReservationReason *BudgetReservedReservationReason `json:"reservation_reason,omitempty" validate:"omitempty"`
	ReservationScope  BudgetReservedReservationScope   `json:"reservation_scope" validate:"required"`
	ReservedAmounts   budget_limits.Limits             `json:"reserved_amounts" validate:"required"`
	ReservedAt        time.Time                        `json:"reserved_at" validate:"required"`
	RunID             *string                          `json:"run_id,omitempty" validate:"omitempty,min=1"`
	StateAfter        budget_state.State               `json:"state_after" validate:"required"`
	TurnID            *string                          `json:"turn_id,omitempty" validate:"omitempty,min=1"`
}

func (value BudgetReserved) Validate() error {
	return shared.Validate(value)
}
