// Code generated by generategomodels; DO NOT EDIT.

package limits

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type LimitsMode string

const (
	LimitsModeInstallationDefault LimitsMode = "installation_default"

	LimitsModeUnlimited LimitsMode = "unlimited"

	LimitsModeCustom LimitsMode = "custom"
)

// Limits is generated from a nested JSON Schema object.
type Limits struct {
	ArtifactSizeBytes      *int       `json:"artifact_size_bytes,omitempty" validate:"omitempty,gte=0"`
	CommandOutputSizeBytes *int       `json:"command_output_size_bytes,omitempty" validate:"omitempty,gte=0"`
	CommandTimeSeconds     *float64   `json:"command_time_seconds,omitempty" validate:"omitempty,gte=0"`
	ElapsedWallTimeSeconds *float64   `json:"elapsed_wall_time_seconds,omitempty" validate:"omitempty,gte=0"`
	Mode                   LimitsMode `json:"mode" validate:"required"`
	ModelCalls             *int       `json:"model_calls,omitempty" validate:"omitempty,gte=0"`
	ModelInputTokens       *int       `json:"model_input_tokens,omitempty" validate:"omitempty,gte=0"`
	ModelOutputTokens      *int       `json:"model_output_tokens,omitempty" validate:"omitempty,gte=0"`
	MonetaryCostUsd        *float64   `json:"monetary_cost_usd,omitempty" validate:"omitempty,gte=0"`
	RepeatedTokenCostUsd   *float64   `json:"repeated_token_cost_usd,omitempty" validate:"omitempty,gte=0"`
	RepositoryRequests     *int       `json:"repository_requests,omitempty" validate:"omitempty,gte=0"`
	ToolCalls              *int       `json:"tool_calls,omitempty" validate:"omitempty,gte=0"`
}

func (value Limits) Validate() error {
	return shared.Validate(value)
}
