// Code generated by generategomodels; DO NOT EDIT.

package content

import (
	artifact_repository_snapshot_reference "github.com/julianstephens/kiln/go/schema/artifact/repository_snapshot_reference"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ContentContentType string

const (
	ContentContentTypeInline ContentContentType = "inline"

	ContentContentTypeArtifact ContentContentType = "artifact"

	ContentContentTypeStructuredRepresentation ContentContentType = "structured_representation"
)

// Content repository content payload represented inline, by artifact reference, or as a structured representation.
type Content struct {
	ArtifactReference        *artifact_repository_snapshot_reference.RepositorySnapshotReference `json:"artifact_reference,omitempty" validate:"omitempty"`
	ContentType              ContentContentType                                                  `json:"content_type" validate:"required"`
	Inline                   *string                                                             `json:"inline,omitempty" validate:"omitempty,min=1"`
	StructuredRepresentation map[string]any                                                      `json:"structured_representation,omitempty" validate:"omitempty"`
}

func (value Content) Validate() error {
	return shared.Validate(value)
}
