// Code generated by generategomodels; DO NOT EDIT.

// Package context_item_admitted contains generated Go models for the Kiln event/payload/context-item-admitted schema.
package context_item_admitted
