// Code generated by generategomodels; DO NOT EDIT.

package context_item_admitted

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ContextItemAdmittedAdmissionReason string

const (
	ContextItemAdmittedAdmissionReasonPinned ContextItemAdmittedAdmissionReason = "pinned"

	ContextItemAdmittedAdmissionReasonRecent ContextItemAdmittedAdmissionReason = "recent"

	ContextItemAdmittedAdmissionReasonRelevant ContextItemAdmittedAdmissionReason = "relevant"

	ContextItemAdmittedAdmissionReasonRequired ContextItemAdmittedAdmissionReason = "required"

	ContextItemAdmittedAdmissionReasonDependency ContextItemAdmittedAdmissionReason = "dependency"

	ContextItemAdmittedAdmissionReasonManual ContextItemAdmittedAdmissionReason = "manual"

	ContextItemAdmittedAdmissionReasonPlanApplied ContextItemAdmittedAdmissionReason = "plan_applied"
)

// ContextItemAdmitted payload for context.item_admitted events.
type ContextItemAdmitted struct {
	AdmissionReason      ContextItemAdmittedAdmissionReason `json:"admission_reason" validate:"required"`
	ContextID            string                             `json:"context_id" validate:"required,min=1"`
	ContextPlanID        *string                            `json:"context_plan_id,omitempty" validate:"omitempty,min=1"`
	ContextStateRevision int                                `json:"context_state_revision" validate:"required,gte=0"`
	CurrentTokenEstimate *int                               `json:"current_token_estimate,omitempty" validate:"omitempty,gte=0"`
	EstimatedTokens      *int                               `json:"estimated_tokens,omitempty" validate:"omitempty,gte=0"`
	ItemID               string                             `json:"item_id" validate:"required,min=1"`
	// Order position of the admitted item in active context order.
	Order int `json:"order" validate:"required,gte=0"`
}

func (value ContextItemAdmitted) Validate() error {
	return shared.Validate(value)
}
