// Code generated by generategomodels; DO NOT EDIT.

package patch_reference

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// PatchReference is generated from a nested JSON Schema object.
type PatchReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value PatchReference) Validate() error {
	return shared.Validate(value)
}
