// Code generated by generategomodels; DO NOT EDIT.

package patch_reference

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type PatchReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value PatchReference) Validate() error {
	return shared.Validate(value)
}
