// Code generated by generategomodels; DO NOT EDIT.

package task_state

import (
	validator "github.com/go-playground/validator/v10"
)

type TaskState struct {
	CompletedSteps      []string         `json:"completed_steps" validate:"required"`
	CompletionEvidence  []string         `json:"completion_evidence" validate:"required"`
	CurrentObjective    string           `json:"current_objective" validate:"required,min=1"`
	CurrentPlan         string           `json:"current_plan" validate:"required,min=1"`
	Hypotheses          []string         `json:"hypotheses" validate:"required"`
	KnownFailures       []string         `json:"known_failures,omitempty" validate:"omitempty"`
	ProposedChanges     []map[string]any `json:"proposed_changes,omitempty" validate:"omitempty"`
	StateRevision       string           `json:"state_revision" validate:"required,min=1"`
	UnresolvedQuestions []string         `json:"unresolved_questions" validate:"required"`
}

func (value TaskState) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
