// Code generated by generategomodels; DO NOT EDIT.

package repository_events

import (
	validator "github.com/go-playground/validator/v10"
)

type RepositoryEvents struct {
}

func (value RepositoryEvents) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
