// Code generated by generategomodels; DO NOT EDIT.

package repository_events

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// RepositoryEvents is generated from a nested JSON Schema object.
type RepositoryEvents struct {
}

func (value RepositoryEvents) Validate() error {
	return shared.Validate(value)
}
