// Code generated by generategomodels; DO NOT EDIT.

package budget_reconciled

import (
	validator "github.com/go-playground/validator/v10"
	budget_state "github.com/julianstephens/kiln/go/schema/budget/state"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	"time"
)

type BudgetReconciledReconciliationReason string

const (
	BudgetReconciledReconciliationReasonEstimatedToActual BudgetReconciledReconciliationReason = "estimated_to_actual"

	BudgetReconciledReconciliationReasonProviderUsageReported BudgetReconciledReconciliationReason = "provider_usage_reported"

	BudgetReconciledReconciliationReasonReservationExpired BudgetReconciledReconciliationReason = "reservation_expired"

	BudgetReconciledReconciliationReasonReservationReleased BudgetReconciledReconciliationReason = "reservation_released"

	BudgetReconciledReconciliationReasonManualAdjustment BudgetReconciledReconciliationReason = "manual_adjustment"

	BudgetReconciledReconciliationReasonLedgerRepair BudgetReconciledReconciliationReason = "ledger_repair"

	BudgetReconciledReconciliationReasonRunFinalization BudgetReconciledReconciliationReason = "run_finalization"

	BudgetReconciledReconciliationReasonUnknown BudgetReconciledReconciliationReason = "unknown"
)

type BudgetReconciled struct {
	Adjustments          []map[string]any                     `json:"adjustments,omitempty" validate:"omitempty,min=1"`
	BudgetID             string                               `json:"budget_id" validate:"required,min=1"`
	ReconciledAt         time.Time                            `json:"reconciled_at" validate:"required"`
	ReconciledUsage      *budget_usage.Usage                  `json:"reconciled_usage,omitempty" validate:"omitempty"`
	ReconciliationID     string                               `json:"reconciliation_id" validate:"required,min=1"`
	ReconciliationReason BudgetReconciledReconciliationReason `json:"reconciliation_reason" validate:"required"`
	StateAfter           budget_state.State                   `json:"state_after" validate:"required"`
	StateBefore          budget_state.State                   `json:"state_before" validate:"required"`
}

func (value BudgetReconciled) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
