// Code generated by generategomodels; DO NOT EDIT.

package security_profile

import (
	capability_scope "github.com/julianstephens/kiln/go/schema/capability/scope"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type SecurityProfile struct {
	ArtifactAccessRules      []any                    `json:"artifact_access_rules,omitempty" validate:"omitempty,min=1"`
	DefaultDenySettings      map[string]any           `json:"default_deny_settings,omitempty" validate:"omitempty"`
	ExternalIntegrationRules []any                    `json:"external_integration_rules,omitempty" validate:"omitempty,min=1"`
	FilesystemReadScopes     []capability_scope.Scope `json:"filesystem_read_scopes,omitempty" validate:"omitempty,min=1"`
	FilesystemWriteScopes    []capability_scope.Scope `json:"filesystem_write_scopes,omitempty" validate:"omitempty,min=1"`
	ModelEgressRules         []any                    `json:"model_egress_rules,omitempty" validate:"omitempty,min=1"`
	NetworkRules             []any                    `json:"network_rules,omitempty" validate:"omitempty,min=1"`
	ProcessExecutionRules    []any                    `json:"process_execution_rules,omitempty" validate:"omitempty,min=1"`
	ValidationRules          []any                    `json:"validation_rules,omitempty" validate:"omitempty,min=1"`
}

func (value SecurityProfile) Validate() error {
	return shared.Validate(value)
}
