// Code generated by generategomodels; DO NOT EDIT.

package source_request_payload

import (
	common_source_range "github.com/julianstephens/kiln/go/schema/common/source_range"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type SourceRequestPayload struct {
	MaxResultSize            int                              `json:"max_result_size" validate:"required,gte=1"`
	QualifiedName            *string                          `json:"qualified_name,omitempty" validate:"omitempty,min=1"`
	RepresentationPreference string                           `json:"representation_preference" validate:"required,min=1"`
	SourceRange              *common_source_range.SourceRange `json:"source_range,omitempty" validate:"omitempty"`
	TargetSource             string                           `json:"target_source" validate:"required,min=1"`
}

func (value SourceRequestPayload) Validate() error {
	return shared.Validate(value)
}
