// Code generated by generategomodels; DO NOT EDIT.

// Package repository_session_closed contains generated Go models for the Kiln event/payload/repository-session-closed schema.
package repository_session_closed
