// Code generated by generategomodels; DO NOT EDIT.

package repository_session_closed

import (
	validator "github.com/go-playground/validator/v10"
	artifact_diagnostic_log_reference "github.com/julianstephens/kiln/go/schema/artifact/diagnostic_log_reference"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	repository_error "github.com/julianstephens/kiln/go/schema/repository/error"
	repository_preparation_status "github.com/julianstephens/kiln/go/schema/repository/preparation_status"
	repository_usage "github.com/julianstephens/kiln/go/schema/repository/usage"
	repository_version "github.com/julianstephens/kiln/go/schema/repository/version"
	"time"
)

type RepositorySessionClosedCloseReason string

const (
	RepositorySessionClosedCloseReasonCompleted RepositorySessionClosedCloseReason = "completed"

	RepositorySessionClosedCloseReasonCanceled RepositorySessionClosedCloseReason = "canceled"

	RepositorySessionClosedCloseReasonFailed RepositorySessionClosedCloseReason = "failed"

	RepositorySessionClosedCloseReasonExpired RepositorySessionClosedCloseReason = "expired"

	RepositorySessionClosedCloseReasonSuperseded RepositorySessionClosedCloseReason = "superseded"

	RepositorySessionClosedCloseReasonRuntimeShutdown RepositorySessionClosedCloseReason = "runtime_shutdown"

	RepositorySessionClosedCloseReasonUnknown RepositorySessionClosedCloseReason = "unknown"
)

type RepositorySessionClosed struct {
	BudgetUsage            *budget_usage.Usage                                       `json:"budget_usage,omitempty" validate:"omitempty"`
	CloseReason            RepositorySessionClosedCloseReason                        `json:"close_reason" validate:"required"`
	ClosedAt               time.Time                                                 `json:"closed_at" validate:"required"`
	DiagnosticLogReference *artifact_diagnostic_log_reference.DiagnosticLogReference `json:"diagnostic_log_reference,omitempty" validate:"omitempty"`
	Error                  *repository_error.Error                                   `json:"error,omitempty" validate:"omitempty"`
	FinalPreparationStatus *repository_preparation_status.PreparationStatus          `json:"final_preparation_status,omitempty" validate:"omitempty"`
	FinalRepositoryVersion *repository_version.Version                               `json:"final_repository_version,omitempty" validate:"omitempty"`
	RepositorySessionID    string                                                    `json:"repository_session_id" validate:"required,min=1"`
	Usage                  *repository_usage.Usage                                   `json:"usage,omitempty" validate:"omitempty"`
}

func (value RepositorySessionClosed) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
