// Code generated by generategomodels; DO NOT EDIT.

// Package repository_preparation_completed contains generated Go models for the Kiln event/payload/repository-preparation-completed schema.
package repository_preparation_completed
