// Code generated by generategomodels; DO NOT EDIT.

package repository_preparation_completed

import (
	artifact_diagnostic_log_reference "github.com/julianstephens/kiln/go/schema/artifact/diagnostic_log_reference"
	artifact_repository_snapshot_reference "github.com/julianstephens/kiln/go/schema/artifact/repository_snapshot_reference"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	repository_identifier "github.com/julianstephens/kiln/go/schema/repository/identifier"
	repository_preparation_status "github.com/julianstephens/kiln/go/schema/repository/preparation_status"
	repository_usage "github.com/julianstephens/kiln/go/schema/repository/usage"
	repository_version "github.com/julianstephens/kiln/go/schema/repository/version"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type RepositoryPreparationCompletedPreparedCapabilitiesItem string

const (
	RepositoryPreparationCompletedPreparedCapabilitiesItemSearch RepositoryPreparationCompletedPreparedCapabilitiesItem = "search"

	RepositoryPreparationCompletedPreparedCapabilitiesItemSource RepositoryPreparationCompletedPreparedCapabilitiesItem = "source"

	RepositoryPreparationCompletedPreparedCapabilitiesItemOpenSession RepositoryPreparationCompletedPreparedCapabilitiesItem = "open_session"

	RepositoryPreparationCompletedPreparedCapabilitiesItemCloseSession RepositoryPreparationCompletedPreparedCapabilitiesItem = "close_session"

	RepositoryPreparationCompletedPreparedCapabilitiesItemVersion RepositoryPreparationCompletedPreparedCapabilitiesItem = "version"

	RepositoryPreparationCompletedPreparedCapabilitiesItemDiagnostics RepositoryPreparationCompletedPreparedCapabilitiesItem = "diagnostics"
)

type RepositoryPreparationCompleted struct {
	BudgetUsage                *budget_usage.Usage                                                 `json:"budget_usage,omitempty" validate:"omitempty"`
	DiagnosticLogReference     *artifact_diagnostic_log_reference.DiagnosticLogReference           `json:"diagnostic_log_reference,omitempty" validate:"omitempty"`
	PreparationDurationSeconds float64                                                             `json:"preparation_duration_seconds" validate:"required,gte=0"`
	PreparationStatus          repository_preparation_status.PreparationStatus                     `json:"preparation_status" validate:"required"`
	PreparedCapabilities       []RepositoryPreparationCompletedPreparedCapabilitiesItem            `json:"prepared_capabilities" validate:"required,min=1"`
	Repository                 repository_identifier.Identifier                                    `json:"repository" validate:"required"`
	RepositorySessionID        string                                                              `json:"repository_session_id" validate:"required,min=1"`
	RepositoryVersion          repository_version.Version                                          `json:"repository_version" validate:"required"`
	SourceSnapshotReference    *artifact_repository_snapshot_reference.RepositorySnapshotReference `json:"source_snapshot_reference,omitempty" validate:"omitempty"`
	Usage                      *repository_usage.Usage                                             `json:"usage,omitempty" validate:"omitempty"`
}

func (value RepositoryPreparationCompleted) Validate() error {
	return shared.Validate(value)
}
