// Code generated by generategomodels; DO NOT EDIT.

// Package runtime_session_ready contains generated Go models for the Kiln event/payload/runtime-session-ready schema.
package runtime_session_ready
