// Code generated by generategomodels; DO NOT EDIT.

package runtime_session_ready

import (
	validator "github.com/go-playground/validator/v10"
)

type RuntimeSessionReadySupportedProtocolCapabilitiesItem string

const (
	RuntimeSessionReadySupportedProtocolCapabilitiesItemRepositoryOpenSession RuntimeSessionReadySupportedProtocolCapabilitiesItem = "repository.open_session"

	RuntimeSessionReadySupportedProtocolCapabilitiesItemRepositorySearch RuntimeSessionReadySupportedProtocolCapabilitiesItem = "repository.search"

	RuntimeSessionReadySupportedProtocolCapabilitiesItemRepositoryGetSource RuntimeSessionReadySupportedProtocolCapabilitiesItem = "repository.get_source"

	RuntimeSessionReadySupportedProtocolCapabilitiesItemModelGenerate RuntimeSessionReadySupportedProtocolCapabilitiesItem = "model.generate"

	RuntimeSessionReadySupportedProtocolCapabilitiesItemCapabilityCheck RuntimeSessionReadySupportedProtocolCapabilitiesItem = "capability.check"

	RuntimeSessionReadySupportedProtocolCapabilitiesItemBudgetReserve RuntimeSessionReadySupportedProtocolCapabilitiesItem = "budget.reserve"

	RuntimeSessionReadySupportedProtocolCapabilitiesItemBudgetCommit RuntimeSessionReadySupportedProtocolCapabilitiesItem = "budget.commit"

	RuntimeSessionReadySupportedProtocolCapabilitiesItemArtifactCreate RuntimeSessionReadySupportedProtocolCapabilitiesItem = "artifact.create"

	RuntimeSessionReadySupportedProtocolCapabilitiesItemArtifactRead RuntimeSessionReadySupportedProtocolCapabilitiesItem = "artifact.read"

	RuntimeSessionReadySupportedProtocolCapabilitiesItemValidationRequest RuntimeSessionReadySupportedProtocolCapabilitiesItem = "validation.request"

	RuntimeSessionReadySupportedProtocolCapabilitiesItemWorkspaceRead RuntimeSessionReadySupportedProtocolCapabilitiesItem = "workspace.read"

	RuntimeSessionReadySupportedProtocolCapabilitiesItemWorkspacePatch RuntimeSessionReadySupportedProtocolCapabilitiesItem = "workspace.patch"
)

type RuntimeSessionReady struct {
	AvailableAdapters             []map[string]any                                       `json:"available_adapters" validate:"required,min=1"`
	DatabaseSchemaVersion         string                                                 `json:"database_schema_version" validate:"required,min=1"`
	RuntimeSessionID              string                                                 `json:"runtime_session_id" validate:"required,min=1"`
	SupportedProtocolCapabilities []RuntimeSessionReadySupportedProtocolCapabilitiesItem `json:"supported_protocol_capabilities" validate:"required,min=1"`
}

func (value RuntimeSessionReady) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
