// Code generated by generategomodels; DO NOT EDIT.

// Package alternative_representation contains generated Go models for the Kiln repository/alternative-representation schema.
package alternative_representation
