// Code generated by generategomodels; DO NOT EDIT.

package alternative_representation

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type AlternativeRepresentationAvailability string

const (
	AlternativeRepresentationAvailabilityAvailable AlternativeRepresentationAvailability = "available"

	AlternativeRepresentationAvailabilityUnavailable AlternativeRepresentationAvailability = "unavailable"
)

// AlternativeRepresentation metadata for an alternate representation of repository content, including availability, estimated cost, and quality metadata.
type AlternativeRepresentation struct {
	Availability       AlternativeRepresentationAvailability `json:"availability" validate:"required"`
	EstimatedTokens    int                                   `json:"estimated_tokens" validate:"required,gte=0"`
	GenerationRequired bool                                  `json:"generation_required" validate:"required"`
	QualityMetadata    map[string]any                        `json:"quality_metadata" validate:"required"`
	RepresentationKind string                                `json:"representation_kind" validate:"required,min=1"`
}

func (value AlternativeRepresentation) Validate() error {
	return shared.Validate(value)
}
