// Code generated by generategomodels; DO NOT EDIT.

package alternative_representation

import (
	validator "github.com/go-playground/validator/v10"
)

type AlternativeRepresentationAvailability string

const (
	AlternativeRepresentationAvailabilityAvailable AlternativeRepresentationAvailability = "available"

	AlternativeRepresentationAvailabilityUnavailable AlternativeRepresentationAvailability = "unavailable"
)

type AlternativeRepresentation struct {
	Availability       AlternativeRepresentationAvailability `json:"availability" validate:"required"`
	EstimatedTokens    int                                   `json:"estimated_tokens" validate:"required,gte=0"`
	GenerationRequired bool                                  `json:"generation_required" validate:"required"`
	QualityMetadata    map[string]any                        `json:"quality_metadata" validate:"required"`
	RepresentationKind string                                `json:"representation_kind" validate:"required,min=1"`
}

func (value AlternativeRepresentation) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
