// Code generated by generategomodels; DO NOT EDIT.

// Package context_plan_produced contains generated Go models for the Kiln event/payload/context-plan-produced schema.
package context_plan_produced
