// Code generated by generategomodels; DO NOT EDIT.

package context_plan_produced

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
)

type ContextPlanProducedPlanningStrategy string

const (
	ContextPlanProducedPlanningStrategyRecency ContextPlanProducedPlanningStrategy = "recency"

	ContextPlanProducedPlanningStrategyRelevance ContextPlanProducedPlanningStrategy = "relevance"

	ContextPlanProducedPlanningStrategyPinnedFirst ContextPlanProducedPlanningStrategy = "pinned_first"

	ContextPlanProducedPlanningStrategyBudgetFit ContextPlanProducedPlanningStrategy = "budget_fit"

	ContextPlanProducedPlanningStrategyHybrid ContextPlanProducedPlanningStrategy = "hybrid"

	ContextPlanProducedPlanningStrategyManual ContextPlanProducedPlanningStrategy = "manual"
)

type ContextPlanProduced struct {
	ContextID             string                               `json:"context_id" validate:"required,min=1"`
	ContextPlanID         string                               `json:"context_plan_id" validate:"required,min=1"`
	ContextPlanRequestID  string                               `json:"context_plan_request_id" validate:"required,min=1"`
	EstimatedTokenCount   int                                  `json:"estimated_token_count" validate:"required,gte=0"`
	ModelContextLimit     *int                                 `json:"model_context_limit,omitempty" validate:"omitempty,gte=0"`
	PlanArtifactReference *artifact_reference.Reference        `json:"plan_artifact_reference,omitempty" validate:"omitempty"`
	PlannedActiveItems    []map[string]any                     `json:"planned_active_items" validate:"required,min=1"`
	PlannedEvictions      []map[string]any                     `json:"planned_evictions,omitempty" validate:"omitempty"`
	PlanningStrategy      *ContextPlanProducedPlanningStrategy `json:"planning_strategy,omitempty" validate:"omitempty"`
}

func (value ContextPlanProduced) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
