// Code generated by generategomodels; DO NOT EDIT.

package context_item_evicted

import (
	validator "github.com/go-playground/validator/v10"
)

type ContextItemEvictedEvictionReason string

const (
	ContextItemEvictedEvictionReasonTokenBudget ContextItemEvictedEvictionReason = "token_budget"

	ContextItemEvictedEvictionReasonStale ContextItemEvictedEvictionReason = "stale"

	ContextItemEvictedEvictionReasonSuperseded ContextItemEvictedEvictionReason = "superseded"

	ContextItemEvictedEvictionReasonLowRelevance ContextItemEvictedEvictionReason = "low_relevance"

	ContextItemEvictedEvictionReasonManual ContextItemEvictedEvictionReason = "manual"

	ContextItemEvictedEvictionReasonPlanApplied ContextItemEvictedEvictionReason = "plan_applied"

	ContextItemEvictedEvictionReasonContextReset ContextItemEvictedEvictionReason = "context_reset"
)

type ContextItemEvicted struct {
	ContextID            string                           `json:"context_id" validate:"required,min=1"`
	ContextPlanID        *string                          `json:"context_plan_id,omitempty" validate:"omitempty,min=1"`
	ContextStateRevision int                              `json:"context_state_revision" validate:"required,gte=0"`
	CurrentTokenEstimate *int                             `json:"current_token_estimate,omitempty" validate:"omitempty,gte=0"`
	EstimatedTokensFreed *int                             `json:"estimated_tokens_freed,omitempty" validate:"omitempty,gte=0"`
	EvictionReason       ContextItemEvictedEvictionReason `json:"eviction_reason" validate:"required"`
	ItemID               string                           `json:"item_id" validate:"required,min=1"`
	PreviousOrder        *int                             `json:"previous_order,omitempty" validate:"omitempty,gte=0"`
}

func (value ContextItemEvicted) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
