// Code generated by generategomodels; DO NOT EDIT.

package reference

import (
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type ReferenceArtifactKind string

const (
	ReferenceArtifactKindAnswer ReferenceArtifactKind = "answer"

	ReferenceArtifactKindChangedFileManifest ReferenceArtifactKind = "changed_file_manifest"

	ReferenceArtifactKindDiagnosticLog ReferenceArtifactKind = "diagnostic_log"

	ReferenceArtifactKindPatch ReferenceArtifactKind = "patch"

	ReferenceArtifactKindRepositorySnapshot ReferenceArtifactKind = "repository_snapshot"

	ReferenceArtifactKindValidationReport ReferenceArtifactKind = "validation_report"

	ReferenceArtifactKindModelRequest ReferenceArtifactKind = "model_request"

	ReferenceArtifactKindModelResponse ReferenceArtifactKind = "model_response"

	ReferenceArtifactKindCandidateBatch ReferenceArtifactKind = "candidate_batch"

	ReferenceArtifactKindFinalResultBundle ReferenceArtifactKind = "final_result_bundle"
)

type ReferenceScope string

const (
	ReferenceScopeInstallation ReferenceScope = "installation"

	ReferenceScopeTenant ReferenceScope = "tenant"
)

type Reference struct {
	ArtifactID         string                `json:"artifact_id" validate:"required,min=1"`
	ArtifactKind       ReferenceArtifactKind `json:"artifact_kind" validate:"required"`
	CompressionMethod  string                `json:"compression_method" validate:"required,min=1"`
	ContentHash        string                `json:"content_hash" validate:"required,min=1"`
	ContentType        string                `json:"content_type" validate:"required,min=1"`
	CreatedAt          time.Time             `json:"created_at" validate:"required"`
	EncryptionMetadata map[string]any        `json:"encryption_metadata,omitempty" validate:"omitempty"`
	RetentionClass     string                `json:"retention_class" validate:"required,min=1"`
	RunID              *string               `json:"run_id,omitempty" validate:"omitempty,min=1"`
	Scope              ReferenceScope        `json:"scope" validate:"required"`
	StoredSize         int                   `json:"stored_size" validate:"required,gte=0"`
	UncompressedSize   int                   `json:"uncompressed_size" validate:"required,gte=0"`
}

func (value Reference) Validate() error {
	return shared.Validate(value)
}
