// Code generated by generategomodels; DO NOT EDIT.

package open_session_request

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type OpenSessionRequest struct {
}

func (value OpenSessionRequest) Validate() error {
	return shared.Validate(value)
}
