// Code generated by generategomodels; DO NOT EDIT.

package open_session_request

import (
	validator "github.com/go-playground/validator/v10"
)

type OpenSessionRequest struct {
}

func (value OpenSessionRequest) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
