// Code generated by generategomodels; DO NOT EDIT.

package session

import (
	repository_identifier "github.com/julianstephens/kiln/go/schema/repository/identifier"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type Session struct {
	Capabilities []string                          `json:"capabilities" validate:"required,min=1"`
	IndexStatus  string                            `json:"index_status" validate:"required,min=1"`
	Repository   *repository_identifier.Identifier `json:"repository,omitempty" validate:"omitempty"`
	SessionID    string                            `json:"session_id" validate:"required,min=1"`
}

func (value Session) Validate() error {
	return shared.Validate(value)
}
