// Code generated by generategomodels; DO NOT EDIT.

package protocol_request

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ProtocolRequest struct {
}

func (value ProtocolRequest) Validate() error {
	return shared.Validate(value)
}
