// Code generated by generategomodels; DO NOT EDIT.

// Package run_output_production_completed contains generated Go models for the Kiln event/payload/run-output-production-completed schema.
package run_output_production_completed
