// Code generated by generategomodels; DO NOT EDIT.

package turn_started

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	"time"
)

type TurnStartedTurnKind string

const (
	TurnStartedTurnKindInitial TurnStartedTurnKind = "initial"

	TurnStartedTurnKindUserFollowup TurnStartedTurnKind = "user_followup"

	TurnStartedTurnKindToolFollowup TurnStartedTurnKind = "tool_followup"

	TurnStartedTurnKindRecovery TurnStartedTurnKind = "recovery"

	TurnStartedTurnKindValidation TurnStartedTurnKind = "validation"

	TurnStartedTurnKindOutputProduction TurnStartedTurnKind = "output_production"
)

type TurnStarted struct {
	BudgetID             *string                       `json:"budget_id,omitempty" validate:"omitempty,min=1"`
	ContextID            string                        `json:"context_id" validate:"required,min=1"`
	ContextStateRevision *int                          `json:"context_state_revision,omitempty" validate:"omitempty,gte=0"`
	InputReference       *artifact_reference.Reference `json:"input_reference,omitempty" validate:"omitempty"`
	ParentTurnID         *string                       `json:"parent_turn_id,omitempty" validate:"omitempty,min=1"`
	StartedAt            time.Time                     `json:"started_at" validate:"required"`
	TurnID               string                        `json:"turn_id" validate:"required,min=1"`
	TurnIndex            int                           `json:"turn_index" validate:"required,gte=0"`
	TurnKind             TurnStartedTurnKind           `json:"turn_kind" validate:"required"`
}

func (value TurnStarted) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
