// Code generated by generategomodels; DO NOT EDIT.

package citation_requirement

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type CitationRequirementMinimumSupportLevel string

const (
	CitationRequirementMinimumSupportLevelDirect CitationRequirementMinimumSupportLevel = "direct"

	CitationRequirementMinimumSupportLevelIndirect CitationRequirementMinimumSupportLevel = "indirect"
)

// CitationRequirement is generated from a nested JSON Schema object.
type CitationRequirement struct {
	AllowedSourceKinds  []string                               `json:"allowed_source_kinds" validate:"required,min=1"`
	CitationModel       string                                 `json:"citation_model" validate:"required,min=1"`
	MinimumSupportLevel CitationRequirementMinimumSupportLevel `json:"minimum_support_level" validate:"required"`
}

func (value CitationRequirement) Validate() error {
	return shared.Validate(value)
}
