// Code generated by generategomodels; DO NOT EDIT.

package approval_requirement

import (
	validator "github.com/go-playground/validator/v10"
)

type ApprovalRequirementApprovalKind string

const (
	ApprovalRequirementApprovalKindHuman ApprovalRequirementApprovalKind = "human"

	ApprovalRequirementApprovalKindAutomated ApprovalRequirementApprovalKind = "automated"
)

type ApprovalRequirement struct {
	ApprovalKind ApprovalRequirementApprovalKind `json:"approval_kind" validate:"required"`
	ApproverRole string                          `json:"approver_role" validate:"required,min=1"`
	Reason       string                          `json:"reason" validate:"required,min=1"`
}

func (value ApprovalRequirement) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
