// Code generated by generategomodels; DO NOT EDIT.

package approval_requirement

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ApprovalRequirementApprovalKind string

const (
	ApprovalRequirementApprovalKindHuman ApprovalRequirementApprovalKind = "human"

	ApprovalRequirementApprovalKindAutomated ApprovalRequirementApprovalKind = "automated"
)

// ApprovalRequirement is generated from a nested JSON Schema object.
type ApprovalRequirement struct {
	ApprovalKind ApprovalRequirementApprovalKind `json:"approval_kind" validate:"required"`
	ApproverRole string                          `json:"approver_role" validate:"required,min=1"`
	Reason       string                          `json:"reason" validate:"required,min=1"`
}

func (value ApprovalRequirement) Validate() error {
	return shared.Validate(value)
}
