// Code generated by generategomodels; DO NOT EDIT.

package generate_response

import (
	validator "github.com/go-playground/validator/v10"
)

type GenerateResponse struct {
}

func (value GenerateResponse) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
