// Code generated by generategomodels; DO NOT EDIT.

package generate_response

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type GenerateResponse struct {
}

func (value GenerateResponse) Validate() error {
	return shared.Validate(value)
}
