// Code generated by generategomodels; DO NOT EDIT.

package requirement

import (
	budget_limits "github.com/julianstephens/kiln/go/schema/budget/limits"
	capability_scope "github.com/julianstephens/kiln/go/schema/capability/scope"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type RequirementRequirementKind string

const (
	RequirementRequirementKindSchema RequirementRequirementKind = "schema"

	RequirementRequirementKindPolicy RequirementRequirementKind = "policy"

	RequirementRequirementKindApproval RequirementRequirementKind = "approval"

	RequirementRequirementKindCitation RequirementRequirementKind = "citation"
)

type RequirementSeverity string

const (
	RequirementSeverityAdvisory RequirementSeverity = "advisory"

	RequirementSeverityBlocking RequirementSeverity = "blocking"
)

type RequirementTrigger string

const (
	RequirementTriggerBeforeModel RequirementTrigger = "before_model"

	RequirementTriggerAfterModel RequirementTrigger = "after_model"

	RequirementTriggerBeforeOutput RequirementTrigger = "before_output"

	RequirementTriggerBeforePublication RequirementTrigger = "before_publication"

	RequirementTriggerOnDemand RequirementTrigger = "on_demand"
)

// Requirement is generated from a nested JSON Schema object.
type Requirement struct {
	BudgetLimits           *budget_limits.Limits      `json:"budget_limits,omitempty" validate:"omitempty"`
	CapabilityRequirements []string                   `json:"capability_requirements,omitempty" validate:"omitempty,min=1"`
	Config                 map[string]any             `json:"config" validate:"required"`
	RequirementID          string                     `json:"requirement_id" validate:"required,min=1"`
	RequirementKind        RequirementRequirementKind `json:"requirement_kind" validate:"required"`
	Scope                  *capability_scope.Scope    `json:"scope,omitempty" validate:"omitempty"`
	Severity               RequirementSeverity        `json:"severity" validate:"required"`
	Trigger                RequirementTrigger         `json:"trigger" validate:"required"`
}

func (value Requirement) Validate() error {
	return shared.Validate(value)
}
