// Code generated by generategomodels; DO NOT EDIT.

package turn_completed

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	budget_usage "github.com/julianstephens/kiln/go/schema/budget/usage"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type TurnCompletedTurnOutcome string

const (
	TurnCompletedTurnOutcomeAssistantMessageProduced TurnCompletedTurnOutcome = "assistant_message_produced"

	TurnCompletedTurnOutcomeToolCallsRequested TurnCompletedTurnOutcome = "tool_calls_requested"

	TurnCompletedTurnOutcomeToolResultsProcessed TurnCompletedTurnOutcome = "tool_results_processed"

	TurnCompletedTurnOutcomeOutputCandidateProduced TurnCompletedTurnOutcome = "output_candidate_produced"

	TurnCompletedTurnOutcomeValidationJudgmentProduced TurnCompletedTurnOutcome = "validation_judgment_produced"

	TurnCompletedTurnOutcomeNoOp TurnCompletedTurnOutcome = "no_op"
)

type TurnCompleted struct {
	BudgetUsage          *budget_usage.Usage           `json:"budget_usage,omitempty" validate:"omitempty"`
	CompletedAt          time.Time                     `json:"completed_at" validate:"required"`
	ContextStateRevision *int                          `json:"context_state_revision,omitempty" validate:"omitempty,gte=0"`
	ModelInvocationIds   []string                      `json:"model_invocation_ids,omitempty" validate:"omitempty"`
	OutputReference      *artifact_reference.Reference `json:"output_reference,omitempty" validate:"omitempty"`
	ToolCallIds          []string                      `json:"tool_call_ids,omitempty" validate:"omitempty"`
	TurnID               string                        `json:"turn_id" validate:"required,min=1"`
	TurnIndex            int                           `json:"turn_index" validate:"required,gte=0"`
	TurnOutcome          TurnCompletedTurnOutcome      `json:"turn_outcome" validate:"required"`
}

func (value TurnCompleted) Validate() error {
	return shared.Validate(value)
}
