// Code generated by generategomodels; DO NOT EDIT.

package protocol_response

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ProtocolResponseStatus string

const (
	ProtocolResponseStatusOk ProtocolResponseStatus = "ok"

	ProtocolResponseStatusNotFound ProtocolResponseStatus = "not_found"

	ProtocolResponseStatusInvalidRequest ProtocolResponseStatus = "invalid_request"

	ProtocolResponseStatusDenied ProtocolResponseStatus = "denied"

	ProtocolResponseStatusStaleSession ProtocolResponseStatus = "stale_session"

	ProtocolResponseStatusConflict ProtocolResponseStatus = "conflict"

	ProtocolResponseStatusCanceled ProtocolResponseStatus = "canceled"

	ProtocolResponseStatusExhausted ProtocolResponseStatus = "exhausted"

	ProtocolResponseStatusRetryableError ProtocolResponseStatus = "retryable_error"

	ProtocolResponseStatusFatalError ProtocolResponseStatus = "fatal_error"
)

type ProtocolResponse struct {
	CorrelationID   *string                `json:"correlation_id,omitempty" validate:"omitempty,min=1"`
	Error           map[string]any         `json:"error,omitempty" validate:"omitempty"`
	Operation       string                 `json:"operation" validate:"required,min=1"`
	ProtocolVersion string                 `json:"protocol_version" validate:"required"`
	RequestID       string                 `json:"request_id" validate:"required,min=1"`
	Result          map[string]any         `json:"result,omitempty" validate:"omitempty"`
	Status          ProtocolResponseStatus `json:"status" validate:"required"`
}

func (value ProtocolResponse) Validate() error {
	return shared.Validate(value)
}
