// Code generated by generategomodels; DO NOT EDIT.

package answer_reference

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// AnswerReference is generated from a nested JSON Schema object.
type AnswerReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value AnswerReference) Validate() error {
	return shared.Validate(value)
}
