// Code generated by generategomodels; DO NOT EDIT.

package grant

import (
	capability_scope "github.com/julianstephens/kiln/go/schema/capability/scope"
	"github.com/julianstephens/kiln/go/schema/shared"
	"time"
)

type GrantCapabilityType string

const (
	GrantCapabilityTypeTool GrantCapabilityType = "tool"

	GrantCapabilityTypeWorkflow GrantCapabilityType = "workflow"

	GrantCapabilityTypeResource GrantCapabilityType = "resource"

	GrantCapabilityTypePolicy GrantCapabilityType = "policy"

	GrantCapabilityTypeCredential GrantCapabilityType = "credential"

	GrantCapabilityTypeIntegration GrantCapabilityType = "integration"
)

type GrantCreationSource string

const (
	GrantCreationSourceSystem GrantCreationSource = "system"

	GrantCreationSourceUser GrantCreationSource = "user"

	GrantCreationSourcePolicy GrantCreationSource = "policy"

	GrantCreationSourceMigration GrantCreationSource = "migration"

	GrantCreationSourceImport GrantCreationSource = "import"
)

type Grant struct {
	AllowedOperations []string               `json:"allowed_operations" validate:"required"`
	ApprovalMetadata  map[string]any         `json:"approval_metadata" validate:"required"`
	CapabilityScope   capability_scope.Scope `json:"capability_scope" validate:"required"`
	CapabilityType    GrantCapabilityType    `json:"capability_type" validate:"required"`
	CreationSource    GrantCreationSource    `json:"creation_source" validate:"required"`
	ExpiresAt         time.Time              `json:"expires_at" validate:"required"`
	GrantID           string                 `json:"grant_id" validate:"required,min=1"`
	Revoked           bool                   `json:"revoked" validate:"required"`
	RunID             string                 `json:"run_id" validate:"required,min=1"`
	StartsAt          time.Time              `json:"starts_at" validate:"required"`
}

func (value Grant) Validate() error {
	return shared.Validate(value)
}
