// Code generated by generategomodels; DO NOT EDIT.

package diagnostic

import (
	validator "github.com/go-playground/validator/v10"
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	common_source_range "github.com/julianstephens/kiln/go/schema/common/source_range"
)

type DiagnosticDiagnosticCode string

const (
	DiagnosticDiagnosticCodeParseFailure DiagnosticDiagnosticCode = "parse_failure"

	DiagnosticDiagnosticCodeUnsupportedLanguage DiagnosticDiagnosticCode = "unsupported_language"

	DiagnosticDiagnosticCodeUnresolvedReference DiagnosticDiagnosticCode = "unresolved_reference"

	DiagnosticDiagnosticCodeTruncatedSource DiagnosticDiagnosticCode = "truncated_source"

	DiagnosticDiagnosticCodeGraphConfidenceWarning DiagnosticDiagnosticCode = "graph_confidence_warning"

	DiagnosticDiagnosticCodeSummaryGenerationWarning DiagnosticDiagnosticCode = "summary_generation_warning"

	DiagnosticDiagnosticCodeIgnoredFile DiagnosticDiagnosticCode = "ignored_file"

	DiagnosticDiagnosticCodeOversizedFileSkipped DiagnosticDiagnosticCode = "oversized_file_skipped"
)

type DiagnosticSeverity string

const (
	DiagnosticSeverityError DiagnosticSeverity = "error"

	DiagnosticSeverityWarning DiagnosticSeverity = "warning"

	DiagnosticSeverityInfo DiagnosticSeverity = "info"
)

type Diagnostic struct {
	ContentID        string                           `json:"content_id" validate:"required,min=1"`
	DiagnosticCode   DiagnosticDiagnosticCode         `json:"diagnostic_code" validate:"required"`
	Message          string                           `json:"message" validate:"required,min=1"`
	Path             *string                          `json:"path,omitempty" validate:"omitempty,min=1"`
	Range            *common_source_range.SourceRange `json:"range,omitempty" validate:"omitempty"`
	RelatedArtifacts []artifact_reference.Reference   `json:"related_artifacts,omitempty" validate:"omitempty"`
	Severity         DiagnosticSeverity               `json:"severity" validate:"required"`
}

func (value Diagnostic) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
