// Code generated by generategomodels; DO NOT EDIT.

// Package repository_version_pinned contains generated Go models for the Kiln event/payload/repository-version-pinned schema.
package repository_version_pinned
