// Code generated by generategomodels; DO NOT EDIT.

package repository_version_pinned

import (
	validator "github.com/go-playground/validator/v10"
)

type RepositoryVersionPinned struct {
	ContentDigest       string `json:"content_digest" validate:"required,min=1"`
	RepositoryVersionID string `json:"repository_version_id" validate:"required,min=1"`
	SourceRevision      string `json:"source_revision" validate:"required,min=1"`
}

func (value RepositoryVersionPinned) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
