// Code generated by generategomodels; DO NOT EDIT.

package repository_version_pinned

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type RepositoryVersionPinned struct {
	ContentDigest       string `json:"content_digest" validate:"required,min=1"`
	RepositoryVersionID string `json:"repository_version_id" validate:"required,min=1"`
	SourceRevision      string `json:"source_revision" validate:"required,min=1"`
}

func (value RepositoryVersionPinned) Validate() error {
	return shared.Validate(value)
}
