// Code generated by generategomodels; DO NOT EDIT.

package specification

import (
	budget_limits "github.com/julianstephens/kiln/go/schema/budget/limits"
	capability_security_profile "github.com/julianstephens/kiln/go/schema/capability/security_profile"
	model_configuration "github.com/julianstephens/kiln/go/schema/model/configuration"
	repository_identifier "github.com/julianstephens/kiln/go/schema/repository/identifier"
	run_task_specification "github.com/julianstephens/kiln/go/schema/run/task_specification"
	"github.com/julianstephens/kiln/go/schema/shared"
	validation_requirement "github.com/julianstephens/kiln/go/schema/validation/requirement"
)

type SpecificationOutputMode string

const (
	SpecificationOutputModeAnswer SpecificationOutputMode = "answer"

	SpecificationOutputModePatch SpecificationOutputMode = "patch"

	SpecificationOutputModeAnswerWithPatch SpecificationOutputMode = "answer_with_patch"

	SpecificationOutputModeReport SpecificationOutputMode = "report"
)

// Specification is generated from a nested JSON Schema object.
type Specification struct {
	BudgetLimits budget_limits.Limits `json:"budget_limits" validate:"required"`
	// CallerMetadata caller-supplied opaque metadata. Kiln does not interpret this object.
	CallerMetadata     map[string]any                              `json:"caller_metadata" validate:"required"`
	IdempotencyKey     *string                                     `json:"idempotency_key,omitempty" validate:"omitempty,min=1"`
	ModelConfiguration model_configuration.Configuration           `json:"model_configuration" validate:"required"`
	OutputMode         SpecificationOutputMode                     `json:"output_mode" validate:"required"`
	Repository         repository_identifier.Identifier            `json:"repository" validate:"required"`
	SecurityProfile    capability_security_profile.SecurityProfile `json:"security_profile" validate:"required"`
	TaskSpecification  run_task_specification.TaskSpecification    `json:"task_specification" validate:"required"`
	Validation         *SpecificationValidation                    `json:"validation,omitempty" validate:"omitempty"`
}

// SpecificationValidation is generated from a nested JSON Schema object.
type SpecificationValidation struct {
	ProfileID    *string                              `json:"profile_id,omitempty" validate:"omitempty,min=1"`
	Requirements []validation_requirement.Requirement `json:"requirements,omitempty" validate:"omitempty,min=1"`
}

func (value Specification) Validate() error {
	return shared.Validate(value)
}
