// Code generated by generategomodels; DO NOT EDIT.

// Package diagnostic_log_reference contains generated Go models for the Kiln artifact/diagnostic-log-reference schema.
package diagnostic_log_reference
