// Code generated by generategomodels; DO NOT EDIT.

package diagnostic_log_reference

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// DiagnosticLogReference is generated from a nested JSON Schema object.
type DiagnosticLogReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value DiagnosticLogReference) Validate() error {
	return shared.Validate(value)
}
