// Code generated by generategomodels; DO NOT EDIT.

package diagnostic_log_reference

import (
	validator "github.com/go-playground/validator/v10"
)

type DiagnosticLogReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value DiagnosticLogReference) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
