// Code generated by generategomodels; DO NOT EDIT.

// Package repository_preparation_started contains generated Go models for the Kiln event/payload/repository-preparation-started schema.
package repository_preparation_started
