// Code generated by generategomodels; DO NOT EDIT.

// Package changed_file_manifest_reference contains generated Go models for the Kiln artifact/changed-file-manifest-reference schema.
package changed_file_manifest_reference
