// Code generated by generategomodels; DO NOT EDIT.

package changed_file_manifest_reference

import (
	validator "github.com/go-playground/validator/v10"
)

type ChangedFileManifestReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value ChangedFileManifestReference) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
