// Code generated by generategomodels; DO NOT EDIT.

package changed_file_manifest_reference

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type ChangedFileManifestReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value ChangedFileManifestReference) Validate() error {
	return shared.Validate(value)
}
