// Code generated by generategomodels; DO NOT EDIT.

package report_reference

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

// ReportReference is generated from a nested JSON Schema object.
type ReportReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value ReportReference) Validate() error {
	return shared.Validate(value)
}
