// Code generated by generategomodels; DO NOT EDIT.

package report_reference

import (
	validator "github.com/go-playground/validator/v10"
)

type ReportReference struct {
	ArtifactKind any `json:"artifact_kind,omitempty" validate:"omitempty"`
}

func (value ReportReference) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
