// Code generated by generategomodels; DO NOT EDIT.

package stop_reason

import (
	validator "github.com/go-playground/validator/v10"
)

type StopReasonCategory string

const (
	StopReasonCategoryCompleted StopReasonCategory = "completed"

	StopReasonCategoryFailed StopReasonCategory = "failed"

	StopReasonCategoryCanceled StopReasonCategory = "canceled"

	StopReasonCategoryExhausted StopReasonCategory = "exhausted"
)

type StopReasonCode string

const (
	StopReasonCodeCompletedSuccessfully StopReasonCode = "completed_successfully"

	StopReasonCodeUserCanceled StopReasonCode = "user_canceled"

	StopReasonCodeSystemCanceled StopReasonCode = "system_canceled"

	StopReasonCodePolicyCanceled StopReasonCode = "policy_canceled"

	StopReasonCodeBudgetExhausted StopReasonCode = "budget_exhausted"

	StopReasonCodeTurnLimitExhausted StopReasonCode = "turn_limit_exhausted"

	StopReasonCodeTimeLimitExhausted StopReasonCode = "time_limit_exhausted"

	StopReasonCodeContextLimitExhausted StopReasonCode = "context_limit_exhausted"

	StopReasonCodeRetryLimitExhausted StopReasonCode = "retry_limit_exhausted"

	StopReasonCodeValidationFailed StopReasonCode = "validation_failed"

	StopReasonCodeCapabilityDenied StopReasonCode = "capability_denied"

	StopReasonCodeCapabilityUnavailable StopReasonCode = "capability_unavailable"

	StopReasonCodeRepositoryUnavailable StopReasonCode = "repository_unavailable"

	StopReasonCodeRepositoryDirty StopReasonCode = "repository_dirty"

	StopReasonCodeToolFailed StopReasonCode = "tool_failed"

	StopReasonCodeExternalOperationFailed StopReasonCode = "external_operation_failed"

	StopReasonCodeOutputProductionFailed StopReasonCode = "output_production_failed"

	StopReasonCodeInternalError StopReasonCode = "internal_error"

	StopReasonCodeRuntimeInterrupted StopReasonCode = "runtime_interrupted"

	StopReasonCodeWorkerInterrupted StopReasonCode = "worker_interrupted"

	StopReasonCodeShutdownInterrupted StopReasonCode = "shutdown_interrupted"

	StopReasonCodeLeaseLost StopReasonCode = "lease_lost"

	StopReasonCodeValidationError StopReasonCode = "validation_error"
)

type StopReason struct {
	Category StopReasonCategory `json:"category" validate:"required"`
	Code     StopReasonCode     `json:"code" validate:"required"`
	Details  map[string]any     `json:"details,omitempty" validate:"omitempty"`
	Message  *string            `json:"message,omitempty" validate:"omitempty,min=1"`
}

func (value StopReason) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
