// Code generated by generategomodels; DO NOT EDIT.

package stop_reason

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type StopReasonCategory string

const (
	StopReasonCategoryCompleted StopReasonCategory = "completed"

	StopReasonCategoryFailed StopReasonCategory = "failed"

	StopReasonCategoryCanceled StopReasonCategory = "canceled"

	StopReasonCategoryExhausted StopReasonCategory = "exhausted"
)

type StopReasonCode string

const (
	StopReasonCodeCompletedSuccessfully StopReasonCode = "completed_successfully"

	StopReasonCodeUserCanceled StopReasonCode = "user_canceled"

	StopReasonCodeSystemCanceled StopReasonCode = "system_canceled"

	StopReasonCodePolicyCanceled StopReasonCode = "policy_canceled"

	StopReasonCodeBudgetExhausted StopReasonCode = "budget_exhausted"

	StopReasonCodeTurnLimitExhausted StopReasonCode = "turn_limit_exhausted"

	StopReasonCodeTimeLimitExhausted StopReasonCode = "time_limit_exhausted"

	StopReasonCodeContextLimitExhausted StopReasonCode = "context_limit_exhausted"

	StopReasonCodeRetryLimitExhausted StopReasonCode = "retry_limit_exhausted"

	StopReasonCodeValidationFailed StopReasonCode = "validation_failed"

	StopReasonCodeCapabilityDenied StopReasonCode = "capability_denied"

	StopReasonCodeCapabilityUnavailable StopReasonCode = "capability_unavailable"

	StopReasonCodeRepositoryUnavailable StopReasonCode = "repository_unavailable"

	StopReasonCodeRepositoryDirty StopReasonCode = "repository_dirty"

	StopReasonCodeToolFailed StopReasonCode = "tool_failed"

	StopReasonCodeExternalOperationFailed StopReasonCode = "external_operation_failed"

	StopReasonCodeOutputProductionFailed StopReasonCode = "output_production_failed"

	StopReasonCodeInternalError StopReasonCode = "internal_error"

	StopReasonCodeRuntimeInterrupted StopReasonCode = "runtime_interrupted"

	StopReasonCodeWorkerInterrupted StopReasonCode = "worker_interrupted"

	StopReasonCodeShutdownInterrupted StopReasonCode = "shutdown_interrupted"

	StopReasonCodeLeaseLost StopReasonCode = "lease_lost"

	StopReasonCodeValidationError StopReasonCode = "validation_error"
)

// StopReason describes why a run stopped executing.
type StopReason struct {
	// Category broad class of reason the run stopped.
	Category StopReasonCategory `json:"category" validate:"required"`
	// Code specific machine-readable stop reason.
	Code StopReasonCode `json:"code" validate:"required"`
	// Details optional structured diagnostic details for the stop reason.
	Details map[string]any `json:"details,omitempty" validate:"omitempty"`
	// Message optional human-readable explanation of the stop reason.
	Message *string `json:"message,omitempty" validate:"omitempty,min=1"`
}

func (value StopReason) Validate() error {
	return shared.Validate(value)
}
