// Code generated by generategomodels; DO NOT EDIT.

package run_failed

import (
	artifact_reference "github.com/julianstephens/kiln/go/schema/artifact/reference"
	run_error "github.com/julianstephens/kiln/go/schema/run/error"
	run_error_category "github.com/julianstephens/kiln/go/schema/run/error_category"
	run_lifecycle_state "github.com/julianstephens/kiln/go/schema/run/lifecycle_state"
	run_stop_reason "github.com/julianstephens/kiln/go/schema/run/stop_reason"
	"github.com/julianstephens/kiln/go/schema/shared"
)

type RunFailedCleanupStatus string

const (
	RunFailedCleanupStatusNotRequired RunFailedCleanupStatus = "not_required"

	RunFailedCleanupStatusPending RunFailedCleanupStatus = "pending"

	RunFailedCleanupStatusCompleted RunFailedCleanupStatus = "completed"

	RunFailedCleanupStatusFailed RunFailedCleanupStatus = "failed"

	RunFailedCleanupStatusUnknown RunFailedCleanupStatus = "unknown"
)

type RunFailed struct {
	CleanupStatus                RunFailedCleanupStatus             `json:"cleanup_status" validate:"required"`
	FailureCategory              run_error_category.ErrorCategory   `json:"failure_category" validate:"required"`
	FailureDetail                *run_error.Error                   `json:"failure_detail,omitempty" validate:"omitempty"`
	LastSuccessfulLifecycleState run_lifecycle_state.LifecycleState `json:"last_successful_lifecycle_state" validate:"required"`
	PartialResultReferences      []artifact_reference.Reference     `json:"partial_result_references,omitempty" validate:"omitempty"`
	StopReason                   run_stop_reason.StopReason         `json:"stop_reason" validate:"required"`
}

func (value RunFailed) Validate() error {
	return shared.Validate(value)
}
