// Code generated by generategomodels; DO NOT EDIT.

package cost

import (
	"github.com/julianstephens/kiln/go/schema/shared"
)

type Cost struct {
	EstimatedBytes      int     `json:"estimated_bytes" validate:"required,gte=0"`
	EstimatedConfidence *int    `json:"estimated_confidence,omitempty" validate:"omitempty,gte=0"`
	EstimatedTokens     int     `json:"estimated_tokens" validate:"required,gte=0"`
	EstimationMethod    string  `json:"estimation_method" validate:"required,min=1"`
	TokenizerFamily     *string `json:"tokenizer_family,omitempty" validate:"omitempty,min=1"`
}

func (value Cost) Validate() error {
	return shared.Validate(value)
}
