// Code generated by generategomodels; DO NOT EDIT.

package usage

import (
	validator "github.com/go-playground/validator/v10"
)

type Usage struct {
	BytesReturned            int     `json:"bytes_returned" validate:"required,gte=0"`
	CandidatesReturned       int     `json:"candidates_returned" validate:"required,gte=0"`
	ElapsedTime              float64 `json:"elapsed_time" validate:"required,gte=0"`
	EstimatedTokensReturned  int     `json:"estimated_tokens_returned" validate:"required,gte=0"`
	FilesScanned             int     `json:"files_scanned" validate:"required,gte=0"`
	GraphNodesVisited        int     `json:"graph_nodes_visited" validate:"required,gte=0"`
	RepresentationsGenerated *int    `json:"representations_generated,omitempty" validate:"omitempty,gte=0"`
}

func (value Usage) Validate() error {
	return validate.Struct(value)
}

var validate = validator.New()
